ARCHITECTURE.md
CHANGELOG.md
CONTRIBUTING.md
README.md

Also removes trademarked phrases, and fixes #2

Update docs to set a clear "we are a new project" stance

---

.circleci/config.yml

Remove deployment code from circleci config

---

README.md

We need an example/demo to show that its real and works: https://codepen.io/snickell/pen/dypOWzj
I refactored this from Curran Kelleher's awesome work: https://vizhub.com/curran/b2df51fad8754d7197dd60fb55258a97

Link to a brief example showing it working on codepen.io

---

.github/workflows/node.js.yml

automate build testing on commit to branch or pull request

github action CI

---

COMMUNITY.md
README.md

This adds a simple documentation of the community structure and steering committee status.

Add initial community document.

---

.github/workflows/ci.yml

Fix #66 by forcing the chromedriver to version 87 because 88 is causing problems.

force chrome version in browser tests

---

LICENSE.txt

Change copyright to MapLibre and add mapbox-gl-js <= 1.13 license to the list of dependencies

Fix copyright

---

package.json

This version has already been published to NPM. Note that somehow the ver 4 was never updated in the main branch.

Published to NPM version v1.13.0-rc.5

---

.github/workflows/ci.yml

Ensure the version of the ChromeDriver is the same as the Chrome version installed locally.

Fix CI - match ChromeDriver version with Chrome

---

.github/workflows/release.yml
RELEASE-PROCESS.md

Release process documentation

---

.github/PULL_REQUEST_TEMPLATE.md

As recommended by open source lawyer

Forbid Mapbox backports in PR template

---

.github/workflows/publish-style-spec.yml
CHANGELOG.md
src/style-spec/package.json

This pull request prepares the publication of the maplibre style spec to NPM. It updates ```src/style-spec/package.json``` and adds a GitHub Actions Workflow file to build and publish the style spec to NPM.
- ✅  confirm your changes do not include backports from Mapbox projects (unless with compliant license)
- ✅  briefly describe the changes in this PR
- ✅ add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`

Publish style spec

---

CHANGELOG.md

- Added missing changelog entry for https://github.com/maplibre/maplibre-gl-js/pull/159

Updated CHANGELOG for setTransformRequest

---

src/ui/camera.js

Update documentation with correct working sample code.
Closes #169

Fix documentation sample code error for map.getCenter

---

README.md

We have react and angular bindings now, so let's tell everyone 🐕 
- 🐳 confirm your changes do not include backports from Mapbox projects (unless with compliant license)
- 💾 briefly describe the changes in this PR

Hint to react and angular wrappers

---

.gitignore

This adds the `*.iml` exception to `.gitignore`. These are project files from the IntelliJ IDE
- ~~[ ] include before/after visuals or gifs if this PR includes visual changes~~
- ~~[ ] write tests for all new functionality~~
- ~~[ ] document any changes to public APIs~~
- ~~[ ] post benchmark scores~~
- ~~[ ] manually test the debug page~~
- ~~[ ] add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`~~

Add IntelliJ file to gitignore

---

src/data/feature_index.ts
src/render/texture.ts
src/source/canvas_source.ts
src/source/raster_dem_tile_source.ts
src/source/raster_dem_tile_worker_source.ts
src/style-spec/migrate.ts
src/style/properties.ts
src/style/style_layer.ts
src/ui/handler/scroll_zoom.ts
src/ui/handler_manager.ts
src/ui/marker.ts
src/util/ajax.ts
src/util/browser.ts
src/util/browser/web_worker.ts
src/util/dom.ts
src/util/offscreen_canvas_supported.ts
src/util/performance.ts
src/util/tile_request_cache.ts
src/util/web_worker.ts
src/util/web_worker_transfer.ts

small changes from WIP branch extracted
268 -> 226

Typescript: a number of minor fixes from WIP branch

---

src/ui/map.ts

Fix typos in comments

---

src/util/dom.ts

This code was only for IE11 support, see https://caniuse.com/passive-event-listener

Remove feature detection for {passive: false} support

---

src/render/draw_debug.ts
src/render/painter.ts
src/render/program/circle_program.ts
src/render/program/line_program.ts
src/render/program/symbol_program.ts
src/source/geojson_source.ts
src/source/vector_tile_source.ts
src/style/load_sprite.ts
src/ui/map.ts
src/util/browser.ts
src/util/mapbox.ts
test/unit/util/browser.test.js

[Typescript] Remove the usage of devicePixelRatio as a getter from browser.ts

---

CHANGELOG.md
src/ui/map.ts
test/unit/ui/map.test.js

[feature] Add redraw function to map

---

.github/workflows/ci.yml

Closes https://github.com/maplibre/maplibre-gl-js/issues/256.

Allow latest geckodriver

---

CHANGELOG.md

changelog change:  do not use mapbox servers with this library.

Notice to not use Mapbox servers

---

src/ui/control/attribution_control.ts
src/ui/control/fullscreen_control.ts
src/ui/control/geolocate_control.ts
src/ui/control/logo_control.ts
src/ui/map.ts
src/ui/popup.ts
src/util/dom.ts

Resolves #263 - Improve DOM.ts helper.

Improve DOM.ts

---

bench/benchmarks_view.tsx
bench/lib/locations_with_tile_id.ts
bench/lib/statistics.ts
bench/rollup_config_benchmarks.js
bench/styles/benchmarks.ts
bench/versions/benchmarks.ts
tsconfig.json

Migrate react view to tsx

---

src/render/image_manager.ts

Please see https://github.com/maplibre/maplibre-gl-js/pull/603

Potpack change type

---

src/types/non-typed-modules.d.ts

See 
https://github.com/maplibre/maplibre-gl-js/pull/598#issuecomment-961692956
https://github.com/maplibre/maplibre-gl-js/issues/526
@mapbox/unitbezier
https://github.com/maplibre/maplibre-gl-js/pull/620
potpack
https://github.com/maplibre/maplibre-gl-js/pull/594

Remove the non-typed stuff

---

.github/workflows/fix-npm-tags.yml

Only add latest tag

---

src/ui/camera.test.ts

I think we do not need this `done`.

[Jest] Change `src/ui/camera.test.ts`  

---

src/render/glyph_manager.ts
src/symbol/collision_index.ts
src/symbol/grid_index.test.ts
src/symbol/grid_index.ts
src/symbol/placement.ts
src/symbol/symbol_layout.ts

Splitting out the type signature/code cleanup changes from #347 for ease of review.

Type signatures for grid_index, symbol_layout

---

CHANGELOG.md
src/source/geojson_source.ts
test/unit/source/geojson_source.test.js

<changelog>Fix GeoJSONSource#loaded sometimes returning true while there are still pending loads (#669)</changelog>

Fix GeoJSONSource#loaded sometimes returning true while there are still pending loads (#669)

---

CHANGELOG.md
src/source/geojson_source.ts
src/ui/events.ts
test/unit/source/geojson_source.test.js

<changelog>Fix MapDataEvent#isSourceLoaded being true in GeoJSONSource "dataloading" event handlers (#694)</changelog>

Fix MapDataEvent#isSourceLoaded being true in GeoJSONSource "dataloading" event handlers (#694)

---

codemods.js

See https://github.com/maplibre/maplibre-gl-js/pull/702#issuecomment-991775625

Expand Jest Codemods

---

src/source/vector_tile_source.test.ts
src/util/browser.test.ts

Fix Jest `done.fail()`

---

CHANGELOG.md
README.md
package.json

This pull request bumps MapLibre GL JS to v2.0.0.

Bump to v2.0.0

---

README.md

Reverts maplibre/maplibre-gl-js#648

Revert "Update Readme for version 2 - do it just before releasing it"

---

CHANGELOG.md
package.json
src/index.ts

Fix documentation of `addProtocol` and remove `version` docs

---

package.json

See title.
- [ x ] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!

Should we change the version number in `package.json` as well?

---

CHANGELOG.md
package-lock.json
package.json
src/source/geojson_source.test.ts
src/source/geojson_source.ts

Fixes supercluster max zoom

---

src/style-spec/migrate.test.ts

[Jest] Small improvment

---

src/ui/camera.ts
src/ui/map.ts

These are necessary docs updates after removal of `Point` and updates to `PointLike` in #800.

Fix docs for `Point` and `PointLike`

---

package-lock.json
package.json
src/data/program_configuration.ts
src/source/source_cache.test.ts
src/style/properties.ts
src/style/style_layer/custom_style_layer.ts
src/style/style_layer/fill_extrusion_style_layer.ts

Stricter linting. I bumped the package and, in contrast to the dependabot PR, ran `lint --fix` to resolve the newfound issues.

Bump eslint from 7.32.0 to 8.7.0

---

.stylelintrc
src/css/maplibre-gl.css

Following rule [color-function-notation](https://stylelint.io/user-guide/rules/list/color-function-notation/) would make me very happy because it makes it clear that the values have different meanings.

[Stylelint] color-function-notation

---

src/ui/handler/scroll_zoom.test.ts

I think a `done `is missing and added it.

[Jest] Missing done in `ui/handler/scroll_zoom.test.ts`

---

src/style/load_glyph_range.test.ts

We do not need to appease flow any more

---

bench/components/RegressionPlot.tsx
bench/components/StatisticsPlot.tsx

The react code is migrated from old class components to functional components with hooks. Easiest to review in split-view due to different levels of nesting.

Refactor benchmark plots to hooks api

---

CHANGELOG.md
src/render/glyph_manager.test.ts
src/render/glyph_manager.ts
src/util/image.ts

This is basically #775 with the existing tests without mocking tinySDF.

Removed mocking of tinySDF from tests and use the data from it

---

src/ui/events.ts

Fix `MapEvent` indentation

---

.eslintrc
src/geo/edge_insets.ts
src/geo/lng_lat_bounds.ts
src/index.ts
src/style/style.ts
src/style/style_image.ts
src/style/style_layer/custom_style_layer.ts
src/ui/camera.ts
src/ui/control/control.ts
src/ui/control/geolocate_control.ts
src/ui/events.ts
src/ui/handler/scroll_zoom.ts
src/ui/map.ts
src/ui/marker.ts

- Add jsdoc indenting and whitespace rules
- Run `npm run lint -- --fix`

Add lint JSDoc indenting and whitespaces rules

---

build/generate-query-test-fixtures.ts

Fix jsdoc warnings missing param description

---

bench/lib/tile_parser.ts

Fix benchmarks following the changes in PR #913.

Fix benchmarks following the changes in PR #913

---

CHANGELOG.md
package-lock.json
package.json

Bump version number and prepare changelog for next version.
After this is merged a new version will be released.

Release 2.1.2 Version

---

.github/workflows/release.yml

Fix release.yml due to bench folder move

---

CHANGELOG.md
package.json

Follow-up on #991. Fixes #990.

Bump to v2.1.4 Fix missing `postinstall.js` file in npm publish

---

.github/workflows/release.yml
CHANGELOG.md
package.json
postinstall.js

Fixes #990. Follow-up on #991, #992.

Bump to v2.1.5-pre.1 - Publish empty `postinstall.js` file

---

CHANGELOG.md
package-lock.json
package.json

Bump to v2.1.5

---

.github/workflows/release.yml
CHANGELOG.md
package-lock.json
package.json

Bump to v2.1.6-pre.1 - Fix `dist/package.json`

---

CHANGELOG.md
package-lock.json
package.json

Bump to v2.1.6

---

src/ui/control/logo_control.test.ts

Correct position of `done()` in the Test of the Logo Control

[JEST] Correct position of done

---

CHANGELOG.md
package-lock.json
package.json

Bump to v2.1.7

---

src/render/draw_symbol.test.ts
src/render/draw_symbol.ts
src/symbol/symbol_size.ts

Improve `draw_symbol.ts` code with better typings and unit test to cover it.

Improve `draw_symbol` code

---

test/README.md

Maybe you want to update more stuff on Sinon. Currently, `test-unit` npm script runs all unit tests `jest ./src`. So if I do `npm run test-unit -- unit-test-file-path` I will run all tests. This is not ideal I find but with `npx jest path-to-unit-file` I can run a single test.

Readme update after jest migration

---

CHANGELOG.md
package-lock.json
package.json

Bump to 2.1.8-pre.1

---

CHANGELOG.md
src/data/feature_index.ts
src/source/query_features.ts
src/style/style.ts
src/ui/map.ts
src/util/vectortile_to_geojson.ts

Resolves https://github.com/maplibre/maplibre-gl-js/issues/1103
This PR adds layer, source, sourceLayer, and state properties to GeoJSONFeature class definition.
I changed the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L1848) from the below to 
```
export type MapboxGeoJSONFeature = GeoJSON.Feature<GeoJSON.Geometry> & {
layer: Layer;
source: string;
sourceLayer: string;
state: { [key: string]: any };
};
```
to 
```
layer: LayerSpecification | undefined;
source: string | undefined;
sourceLayer: string | undefined;
state: { [key: string]: any } | undefined;
```
The reason for this change is that since layer, source, sourceLayer, and state are not set in the constructor, they are undefined for newly created instances.
Layer, …

add layer, source, sourceLayer, and state properties to GeoJSONFeature class definition

---

CHANGELOG.md
package-lock.json
package.json

Cut a new prerelease because of recent changes to the build pipeline.

Prerelease 2.1.8-pre.2

---

CHANGELOG.md
package-lock.json
package.json

Pre-release to check if #1096 is resolved now.

Bump to v2.1.8-pre.3

---

CHANGELOG.md
src/style/style_layer/custom_style_layer.ts

[DefinitelyTyped typed CustomLayerInterface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L2240) renderingMode, onRemove, onAdd, and prerender as optional. This PR updates maplibre typings to match DefinitelyTyped.

Type CustomLayerInterface renderingMode, onRemove, onAdd, and prerender optional

---

CHANGELOG.md
package-lock.json
package.json

Bump version to 2.1.8

---

.github/workflows/add-pr-demo.yml
.github/workflows/remove-pr-demo.yml

Addresses problem encountered in #1070 where a pull request from a branch in a different repo did not have enough permissions to create the demo.

Elevate demo permissions

---

.github/workflows/add-pr-demo.yml
.github/workflows/remove-pr-demo.yml

#1170 still fails. Maybe we need workflow-wide permissions.

Move permissions to full workflow file

---

src/source/canvas_source.test.ts

add missing mockImplementation to avoid error output

---

.gitignore
rollup.config.style-spec.ts
src/style-spec/CHANGELOG.md
src/style-spec/dist/package.json
src/style-spec/package.json
test/build/style-spec.test.ts

When trying to use https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec with Node 12(+), an error like the following is shown
```
require() of /app/node_modules/@maplibre/maplibre-gl-style-spec/dist/index.js from /app/src/serve_style.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/@maplibre/maplibre-gl-style-spec/package.json.
```
Talking to @HarelM on slack I had found out this error had also occurred in maplibre-gl-js and it was fixed by adding a package.json file with the line "{ type: "commonjs" }" to the dist folder where …

fix for "is an ES module file" in node 12+ when using style-spec npm package

---

CODE-OF-CONDUCT.md

Link to MapLibre's code of conduct

---

CHANGELOG.md
package-lock.json
package.json

I wanted to pre-release this due to the changes in geojson which are somewhat risky, just before publishing the terrain branch.
Nothing special here besides version and changelog changes.

Changes needed to release 2.2.0-pre.1

---

CHANGELOG.md
package-lock.json
package.json

Bump version to 2.2.0-pre.2 in order to release the terrain feature, yay!

Bump version to 2.2.0-pre.2

---

README.md

This pull request adds "MIERUNE Inc." to the list of sponsors in the README. Thanks for supporting MapLibre with USD 10'000 per year!
https://opencollective.com/maplibre
I added the company name and linked it to the company website. Did I spell it correctly @dayjournal?
Also linked the GitHub handles to their profile pages on GitHub.

Add sponsor MIERUNE Inc.

---

README.md

Change URLs which redirect to HTTPS to use HTTPS.
Skip changelog.
- ~~Add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`.~~

Change URL from HTTP to HTTPS

---

test/bench/lib/tile_parser.ts

Fix benchmark MapStub class

---

package.json
test/bench/benchmarks_view.tsx
test/bench/components/Axis.tsx
test/bench/components/BenchmarkRow.tsx
test/bench/components/BenchmarkStatistic.tsx
test/bench/components/BenchmarkTable.tsx
test/bench/components/RegressionPlot.tsx
test/bench/components/StatisticsPlot.tsx

Adds \`tsx\` files to the set of linted files. We have \`tsx\` files for example in the benchmark folder.

Lint `tsx` files

---

CHANGELOG.md
package-lock.json
package.json

@wipfli @birkskyum @xabbu42 @astridx please approve so I can publish a new version to npm
Thanks!

Bump version to 2.2.0-pre.3

---

src/style-spec/empty.test.ts
src/style-spec/empty.ts
src/ui/handler/drag_pan.test.ts
src/ui/map_events.test.ts

Removing some of the ts-nodecheck

Remove ts nocheck

---

CHANGELOG.md
package-lock.json
package.json

A lot of good work [has happened](https://github.com/maplibre/maplibre-gl-js/compare/8373c9d...88a3bc3) since last prerelease over a month ago, so let's cut a new one. 
@HarelM , @astridx , @wipfli

Release 2.2.0-pre.4

---

CHANGELOG.md
package-lock.json
package.json

Bump version to 2.2.1

---

build/generate-style-spec.ts
src/style-spec/feature_filter/feature_filter.test.ts

In continue to #1380, #1383 and #1390.
This is another fix for the typings.
@cns-solutions-admin feel free to review.

Fix interpolate typings definition

---

CHANGELOG.md
package-lock.json
package.json

Because of #1485 , we have to do a pre-release this time.

Release 2.3.1-pre.1

---

package.json

add a build-dist script that builds everything in dist.

---

src/style-spec/CHANGELOG.md

Minor "typo" change, just for consistency.

Changelog formatting: Add `#` before PR is

---

CHANGELOG.md
src/ui/map.test.ts
src/ui/map.ts

Create getter for the terrain elevation at the center of the map (camera target). Related to #1318

Add map.getCameraTargetElevation()

---

src/ui/map.ts

Improve docs for getCameraTargetElevation()

Add unit to getCameraTargetElevation

---

.github/workflows/test-unit.yml
package.json

This is a second attempt to add coverage after the coverage workflow was updated with relevant changes.
Let's see what we get now :-)

Add coverage only on PR's changed lines

---

test/debug-pages/terrain-hillshade.html
test/debug-pages/terrain-osm.html

Improve our terrain examples to debug hillshade (see  #1540 )
Add new terrain-hillshade example without extra texture on top
Add global terrain data to osm example

Improve terrain debug pages

---

test/bench/benchmarks/hillshade_load.ts
test/bench/run-benchmarks.ts
test/bench/versions/index.html

This are some unrelated small improvements in the benchmark code which do not need individual pull requests.

Small benchmark improvements

---

CHANGELOG.md

Changelog  - Remove elevation offset

---

src/source/query_features.test.ts
src/source/query_features.ts
src/source/tile.ts
src/style/style.ts
src/ui/map.ts

Fix parameter types of Map.querySourceFeatures

---

CHANGELOG.md
package-lock.json
package.json

A prerelease containing the last month's additions. The final v3.0.0 isn't quite ready yet, but with a prerelease, we can start testing the changes already (mainly terrain related).

Release 3.0.0-pre.0

---

CHANGELOG.md

- [maplibre/maplibre-gl-js](https://github.com/mapbox/mapbox-gl-js) issues and PRs
- [mapbox/mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) issues, PRs, and commits
- GitHub users
- skip changelog

Add links to CHANGELOG.md

---

CHANGELOG.md
package-lock.json
package.json

I've made a few small corrections to the changelog.

Release version 3.0.0-pre.1

---

.github/PULL_REQUEST_TEMPLATE.md

Clarifies hopefully a bit the changelog entry.

Update pull request guideline template

---

src/ui/control/attribution_control.ts

Update attribution control documentation to make it more clear, especially around responsive collapse behavior.

Update attribution control documentation

---

CHANGELOG.md

Adding changelog entry for #1808

---

test/integration/symbol-shaping/shaping.test.ts

Fixes lint warning at the bottom of the PRs.

Fix lint in PRs

---

CONTRIBUTING.md
README.md

Small improvements related to comment made in #1826

Improve readme and contributing

---

src/ui/control/navigation_control.test.ts
src/util/browser.ts

Adds tests for pressing / dragging the compass button in the NavigationControl. Part of the work on https://github.com/maplibre/maplibre-gl-js/pull/1852

Add compass button tests

---

test/integration/render/render.test.ts

Failed test messages are buried and hard to spot. Mark them red.

Mark failed render tests as red on console

---

README.md

Add advertisement for call for bounties

---

build/generate-debug-index-file.ts
test/bench/gl-stats.html
test/bench/styles/index.html
test/bench/versions/index.html
test/integration/browser/fixtures/land.html
test/integration/query/assets/loadMap.html

The 404 error in the console was annoying me.

suppress favicon on html pages

---

.github/workflows/release.yml

Upgrade deprecated GitHub Workflow Action plugins in release.yml

---

src/style-spec/feature_filter/feature_filter.test.ts

Add test for interpolating over zoom

---

CHANGELOG.md
package-lock.json
package.json

Bumping version to 3.0.0-pre.3 to allow testing new bug fixes and features.
cc: @wipfli, @birkskyum

Bump version to 3.0.0-pre.3

---

test/bench/README.md
test/bench/benchmarks/filter_evaluate.ts
test/bench/benchmarks/layers.ts
test/bench/benchmarks/paint_states.ts
test/bench/benchmarks/remove_paint_state.ts

fix paths broken by #2031

---

README.md

https://github.com/maplibre/maplibre.github.io/pull/113

Remove call for bounties

---

src/render/painter.ts

This pr introduces the refactoring of the duplicate loop in painter.

Refactoring painter duplicated for in sourceCaches

---

.eslintrc
build/generate-struct-arrays.ts
src/data/feature_index.ts
src/source/geojson_source.test.ts
src/style-spec/expression/types.ts
src/style/properties.ts
src/ui/camera.ts
src/util/ajax.ts
src/util/primitives.ts
src/util/tile_request_cache.ts
test/build/style-spec.test.ts
test/integration/assets/tiles/upgrade.js

Remove unused eslint-disable comments

Remove unused eslint-disable comments

---

CHANGELOG.md
package-lock.json
package.json

Also fixed some issues in the changelog...
@birkskyum @wipfli @rotu can you take a look?

Bump version to 3.0.0-pre.4

---

README.md

Adds a link to the bounties guide.

Add link to bounty step-by-step guide

---

README.md

Add komoot sponsor logo

---

CONTRIBUTING.md
test/README.md

Added some notes about things that are needed to make linux run.
Seems like Github's codespaces can do a decent job if configured correctly.

Improve readme for Linux

---

package-lock.json
package.json
src/css/maplibre-gl.css

Update stylelint to latest version and fix lint issues.

Fixes stylelint and updates to latest version

---

test/integration/render/result_item_template.html

A dumb mistake I did when refactoring this... Apparently I should've tested it better...

Fix render test report bug in click

---

package-lock.json
package.json

Remake of #2496 , due to lots of deps updates since.
Closes #2496

Add missing deps (remake)

---

CHANGELOG.md
package-lock.json
package.json

It seems like a good time for a pre-release, with quite a lot happening since pre.5.

Release 3.0.0-pre.6

---

src/style/style_layer/custom_style_layer.ts
src/util/webp_supported.ts

Update webgl types in custom style layer and webp test util

---

CHANGELOG.md

A PR link is missing for the transformCameraUpdate addition

Add link to latest changelog item

---

CHANGELOG.md
package-lock.json
package.json

Main addition:
**transformCameraUpdate()**
A pre-release makes it easier to test this feature in various apps / online snippet environments.

Release 3.0.0-pre.8

---

.github/workflows/test-all.yml

Let's see if removing this parameter fixes the CI...
Related to comments in here: #2545

Remove --report parameter

---

CHANGELOG.md
package-lock.json
package.json

Fix bug introduced in pre.5 with ResizeObserver

Release 3.0.0-pre.9

---

test/integration/README.md

Related to #2556
Also correct the location of supporting files in the `assets` subdirectory
- <s>Include before/after visuals or gifs if this PR includes visual changes.</s>
- <s>Write tests for all new functionality.</s>
- <s>Document any changes to public APIs.</s>
- <s>Post benchmark scores.</s>
- <s>Add an entry to `CHANGELOG.md` under the `## main` section.</s>

Document Running tests in GitHub

---

test/integration/render/run_render_tests.ts

Add a list of failing tests after their count.
Related to #2556
Before (taken from the issue):
After:
All tests test the new functionality
- <s> Document any changes to public APIs.</s>
- <s> Post benchmark scores.</s>
- <s> Add an entry to `CHANGELOG.md` under the `## main` section.</s>

Add a list of failing tests after their count

---

.gitignore
test/integration/render/run_render_tests.ts

Always include the actual rendering results in the artifact created for failing tests, including failures caused by a missing expected results or a mismatch in the size of the expected result.
Also, `.gitignore`: Add Vim `.*.swp` files
Resolves #2556
Missing expected image: 
Image size mismatch:
- <s>Write tests for all new functionality.</s>
- <s>Document any changes to public APIs.</s>
- <s>Post benchmark scores.</s>
- <s>Add an entry to `CHANGELOG.md` under the `## main` section.</s>

Improve test harness - actual rendering results

---

.github/workflows/release.yml

This check block the release pipeline.

Remove tag check temporarily

---

.github/workflows/release.yml

We can release, and add artifacts in a single step to simplify things.

Do release in one step

---

test/integration/render/run_render_tests.ts
test/integration/render/tests/debug/collision/style.json

I've seen that the retry doesn't really help, so I added some close and open a page.
For my environment locally it seems to solve one of the tests.
Let's monitor this and see if more improvements is needed there...

Try close and open the page when retrying.

---

test/integration/README.md

This script is removed in 50d5043

Remove description about script "watch-query"

---

.github/workflows/test-all.yml

This should allow uploading coverage report to codecov.

Upload coverage to codecov

---

src/ui/control/attribution_control.ts
src/ui/control/fullscreen_control.ts
src/ui/control/geolocate_control.ts
src/ui/control/navigation_control.ts
src/ui/control/scale_control.ts
src/ui/control/terrain_control.ts
src/ui/marker.ts
src/ui/popup.ts

I went over the page of the control in the docs as part of https://github.com/maplibre/maplibre-gl-js-docs/issues/468 and found all kind of issues.
This PR is aiming at fixing some of the stuff in that page.
It's specific to the control page in the docs.

Improve the docs related to the controls

---

src/render/texture.ts
src/source/raster_dem_tile_source.ts
src/source/vector_tile_worker_source.ts
src/util/browser.ts

Fixes stuff that got broken in typescript 5.1.3.
See #2680
https://github.com/microsoft/TypeScript/issues/54639
The original PR that failed was #2638

Improve typings for typescript 5.1.3

---

docs/plugins.md

Adds https://github.com/stadiamaps/maplibre-search-box to plugin list.

Update plugins.md with maplibre-search-box

---

.github/workflows/auto-merge-dependabot.yml

Remove patch restriction from dependabot

---

src/ui/handler/box_zoom.ts
src/ui/handler/click_zoom.ts
src/ui/handler/drag_handler.ts
src/ui/handler/keyboard.ts
src/ui/handler/scroll_zoom.ts
src/ui/handler/shim/dblclick_zoom.ts
src/ui/handler/shim/drag_pan.ts
src/ui/handler/shim/drag_rotate.ts
src/ui/handler/shim/two_fingers_touch.ts
src/ui/handler/two_fingers_touch.ts
src/ui/map.ts
typedoc.json

Added handlers section and converted all the jsdocs comments to TSdocs commetns.

Added handlers to the docs

---

CHANGELOG.md
documents_and_diagrams/README.md
src/render/painter.ts
src/render/render_to_texture.ts
src/ui/camera.ts
src/ui/control/navigation_control.ts
src/ui/hash.ts
src/ui/map.ts
src/ui/marker.test.ts
src/ui/marker.ts
src/ui/popup.ts
src/util/evented.ts
src/util/performance.ts
typedoc.json

Jsdocs tsdocs

---

src/source/canvas_source.ts
src/source/geojson_source.ts
src/source/geojson_worker_source.ts
src/source/image_source.ts
src/source/raster_dem_tile_source.ts
src/source/raster_tile_source.ts
src/source/source.ts
src/source/vector_tile_source.ts
src/source/video_source.ts
src/style/style_layer/custom_style_layer.ts
typedoc.json

Not sure what happened with the other branch...
git annoying stuff...
Created a new branch instead.
Added all the sources.

Fix sources

---

CHANGELOG.md
README.md
build/generate-docs.ts
docs/README.md
package-lock.json
package.json

Release a new version to see that the new links are working as expected.
If this will work as expected the old repo can be archived.

Bump version to 3.2.0-pre.2

---

CHANGELOG.md
mkdocs.yml
package-lock.json
package.json

Also removed some depths of TOC.
Once released I think we can release an official version.

Bump version to 3.2.0-pre.3

---

docs/plugins.md

Link to a maplibre plugin, and to @dimfeld's Svelte library

Link to route-snapper and svelte-maplibre plugins

---

package-lock.json
package.json

Bump @maplibre/maplibre-gl-style-spec from 19.2.1 to 19.2.2

---

src/ui/map.ts

Fix broken links in the documentation.

fix broken links

---

CHANGELOG.md
package-lock.json
package.json

Bump version to 3.2.1

---

CHANGELOG.md
src/util/image_request.ts

Properly check `ImageBitmap`.
Fixes #2940.
Not sure there's much to add here besides the above...

Properly check `ImageBitmap`

---

CHANGELOG.md
package-lock.json
package.json

The following PRs should be merged before releasing this version:
#2942 and #2945

Bump version to 3.2.2

---

README.md

Add Radar logo

---

CHANGELOG.md
src/style/style.ts
src/ui/map.ts

fixes https://github.com/maplibre/maplibre-gl-js/issues/2992

Map set terrain ts fix

---

src/style/style_layer/variable_text_anchor.ts
src/ui/marker.ts
src/ui/popup.ts

This is the same as #2730.
The person who opened the PR didn't answer my code review fixes.

Remove some SQRT calls

---

src/source/vector_tile_source.ts
src/ui/control/navigation_control.ts
test/examples/live-geojson.html

Fixes #3019.
Fixes #2833.
Removed broken links, improve the example of live reload, although the response is no longer geojson, the example is better I think, or at least not broken...

Fix docs links and live reload

---

CHANGELOG.md
package-lock.json
package.json

Release to fix a few typing issues

Bump version to 3.3.1

---

CHANGELOG.md
package-lock.json
package.json

This also updates the changelog to add info about the custom raster-dem encodings

Bumps version to 3.4

---

CHANGELOG.md
package-lock.json
package.json

Bump version to 3.4.1

---

CHANGELOG.md
package-lock.json
package.json

Bump version to 3.5.0.
cc @HarelM

Bump version to 3.5.0

---

docs/plugins.md

Adding vue-maplibre-gl which provides Vue integration for maplibre-gl

Update plugins.md to include Vue Integration

---

src/util/actor.ts
src/util/dispatcher.test.ts
src/util/dispatcher.ts

This doesn't change any code, just adds more types and improve refactoring capabilities, also uses more capabilities of Jest in tests.

Improve dispatcher typings

---

src/data/dem_data.ts
src/source/raster_dem_tile_source.ts
src/source/raster_dem_tile_worker_source.ts
src/source/worker.ts
src/source/worker_source.ts
src/util/actor_messages.ts

A couple of tweaks to illustrate the comments I made in #3233

A couple of tweaks to async-actor

---

src/source/vector_tile_worker_source.ts
src/util/actor.test.ts

Code review changes from https://github.com/maplibre/maplibre-gl-js/pull/3273

Code review changes

---

README.md

Meta is now a gold sponsor, reflect this in the readme.

Meta Gold sponsorship

---

test/bench/benchmarks/worker_transfer.ts
test/bench/benchmarks_view.tsx
test/bench/components/BenchmarkRow.tsx
test/bench/components/BenchmarkTable.tsx
test/bench/components/util.ts
test/bench/lib/benchmark.ts
test/bench/run-benchmarks.ts
test/bench/versions/index.html

Added better titles to versions,
Show graphs only when all benchmarks are completed to avoid performance degradation.
Improve code readability a bit.
This is still a hot mess of code which I hope is the last time I'm touching... it's just horrible...
Before the fix:
After the fix:

Benchmark improvements

---

.github/workflows/release.yml

The reason for the number before the email is from this thread:
https://github.com/orgs/community/discussions/26560#discussioncomment-3531273

Fix missing git config to enable easier release

---

.github/workflows/release.yml

This uses the commit and push action instead of writing my own code...

Use commit and push GitHub action

---

docs/plugins.md

docs(plugins.md): update to add mapbox-gl-ogc-feature-collection

---

CHANGELOG.md
test/examples/mapbox-gl-draw.html

Fixes the example as per the discussion in #2601

Fix the example as per the discussion in #2601 issue

---

.github/workflows/release.yml

This was ignoring pre-release.
Now it takes the last version simply...

Fix release issue with pre-release

---

src/source/load_tilejson.ts
src/types/tilejson.ts
test/integration/render/run_render_tests.ts

This improves the loadTileJson method types according to what's really is returned.

Improve `loadTileJson` types

---

CHANGELOG.md

fixed `addSrouceType` -> `addSourceType`

Update typo in CHANGELOG.md

---

src/util/config.ts

Fixed typo and rephrased comment about Abort Controller.

---

src/source/query_features.ts

Minor update to fix typo in the docstring for `QuerySourceFeatureOptions`. Thank you!

Update docstring for QuerySourceFeatureOptions

---

.github/workflows/test-all.yml
test/integration/render/tests/text-variable-anchor-offset/pitched/style.json

Improves the ci build by removing unneeded complexity in strategy and OS matric, and fix the upload artifact behavior change in version 4.

Fix upload action breaking changes

---

src/ui/handler/two_fingers_touch.ts

I intended to only add some type declarations, but then there were some logical consequences that required some behavioral changes. I believe these strictly make things more robust in the "should never happen" case of state being undefined. I'll call them out below with inline comments momentarily.
As mentioned in https://github.com/maplibre/maplibre-gl-js/issues/3504#issuecomment-1875927741, I wanted to start adding more thorough and correct type information. It's my first commit to the project, so please let me know if something seems off.
- [n/a?] Add an entry to `CHANGELOG.md` under the `## main` section.

strict lints for two_fingers_touch.ts

---

.github/workflows/test-all.yml
package-lock.json
package.json
test/integration/render/run_render_tests.ts

This is an initial attempt to add coverage to the render tests, I don't know if this will work, but it's worth a shot.

Add coverage to render tests

---

.github/workflows/test-all.yml

Changed the code without changing the CI...
My mistake...

Fix CI typo

---

docs/index.md

Add missing "from" to the sentence.

add missing 'from' to sentence

---

.github/workflows/release.yml
.github/workflows/upload-benchmarks.yml
package.json

I accidentally broke the benchmark and release pipelines.
This will fix them and make them more robust as there was a possible race condition issue with the previous build-dist command.

Fix release and benchmark pipelines

---

docs/style-spec.md

fix defiNItion typo

---

CHANGELOG.md
src/ui/handler/scroll_zoom.test.ts
src/ui/handler/scroll_zoom.ts

Use center for zoom when mouse above horizon (#3398).

---

src/ui/camera.ts

Trivial change improving documentation for `queryTerrainElevation`.

Improve docstring for queryTerrainElevation

---

build/rollup/bundle_prelude.js
build/rollup/maplibregl.js
rollup.config.ts

Related to https://github.com/timocov/dts-bundle-generator/discussions/291
cc @HarelM 
There are 2 commits and it works on both of them. Feel free to drop the last one if you don't feel comfortable with the changes in it (it is a tiny refactoring).

Fixing initializing with esm exports

---

COMMUNITY.md
README.md

- Remove COMMUNITY.md file
- Fix sponsorship tier
Closes #3342

Remove COMMUNITY.md file, fix sponsorship tier

---

CHANGELOG.md

add pr link in changelog

---

src/ui/control/geolocate_control.ts

Update geolocate_control.ts to format code keywords consistently

---

CHANGELOG.md
src/util/actor.test.ts
src/util/actor.ts

Fixes https://github.com/maplibre/maplibre-gl-js/issues/3680

Fix vector tiles not loading when html is opened via file://

---

CHANGELOG.md
src/style/style.test.ts
src/style/style.ts

Adds a test for 
- #3709 
Fixes #3709

Fix Style.setState ignoring validate flag #3709

---

README.md

Merge after https://github.com/maplibre/maplibre.github.io/pull/303

Add MSFT logo

---

src/geo/transform.ts
src/ui/camera.ts
test/examples/add-3d-model-with-terrain.html

Fixes (temporarily) https://github.com/maplibre/maplibre-gl-js/issues/3736.

Fix comment on queryTerrainElevation

---

test/examples/add-3d-model-babylon.html

Adding optional code for interactivity and occlusion.

Update add-3d-model-babylon.html with comments on occlusion and interactivity

---

test/examples/check-for-support.html

Fix misleading wording (see #3857).

Fix title and description of check-for-support example.

---

src/ui/popup.ts

Comments to show docs for Popup Constructor and PopupOptions, fix #4017

---

src/ui/map.ts
test/examples/custom-marker-icons.html

placekitten.com since month, so substitute by picsum.photos
Fixes #4034

sustitute placekitten.com by picsum.photos, fix #4034

---

.github/ISSUE_TEMPLATE/Feature_request.md

I believe that having two "sentence" words is a typo?

Fix a typo in the Feature_request.md (an issue template)

---

docs/plugins.md

* Demo:  https://maps-withastro.roblabs.com
---
- [N/A] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
- [N/A] Briefly describe the changes in this PR.
- [N/A] Link to related issues.
- [N/A] Include before/after visuals or gifs if this PR includes visual changes.
- [N/A] Write tests for all new functionality.
- [N/A] Document any changes to public APIs.
- [N/A] Post benchmark scores.
- [N/A] Add an entry to `CHANGELOG.md` under the `## main` section.

Bring Leaflet & MapLibre maps directly into Astro.

---

src/ui/control/attribution_control.test.ts
src/ui/control/attribution_control.ts
src/ui/map.ts

defaultAtributionControlOptions -> defaultAttributionControlOptions
- [n/a ] Link to related issues.
- [ n/a] Include before/after visuals or gifs if this PR includes visual changes.
- [n/a] Document any changes to public APIs.
- [n/a] Post benchmark scores.
- [n/a] Add an entry to `CHANGELOG.md` under the `## main` section.

Fix a typo in "Attribution"

---

CHANGELOG.md
CONTRIBUTING.md
build/readme.md
developer-guides/life-of-a-tile.md
docs/README.md
docs/guides/mapbox-migration-guide.md
docs/plugins.md
docs/style-spec.md
test/README.md
test/integration/README.md

Various typo fixes to docs.
I haven't added this to the `CHANGELOG.md` but let me know if its worth me doing that and I'll add a commit to this PR.
FYI, I use and recommend this: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
(Also available as a GitHub Action).

Typo Fixes

---

src/ui/control/fullscreen_control.ts
src/ui/control/geolocate_control.ts
src/ui/control/logo_control.ts
src/ui/control/scale_control.ts
src/ui/control/terrain_control.ts

The documentation is lacking some constructor options, which make it difficult to find what the controls accepts.

Add constructor comments on the controls to fix doc generation

---

CONTRIBUTING.md

- correct capitalization of GitHub
- Change OSX to macOS (it's been that for a long time already)
- Set Apple silicon to be a sub-header. (good practice for markdown files)

Minor fixes for CONTRIBUTING.md

---

mkdocs.yml

Fixes missing description. Improves SEO  (see: https://www.opengraph.xyz/url/https%3A%2F%2Fmaplibre.org%2Fmaplibre-gl-js%2Fdocs%2F )
I haven't tested this locally (don't have Docker setup) but assume it should be fine.
Usage is similar to mkdocs-material docs site: (https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml#L25)

Add site description

---

test/examples/camera-animation.html
test/examples/change-case-of-labels.html
test/examples/color-switcher.html
test/examples/filter-within-layer.html
test/examples/interactive-false.html
test/examples/map-tiles.html
test/integration/render/report_template.html

- Some labels were not linked to their inputs
- HTTPS a few relevant links (faster and faster)

Fix a few accessibility issues on tests

---

CHANGELOG.md
CONTRIBUTING.md
docs/plugins.md
test/README.md
test/examples/popup-on-click.html
test/examples/scroll-fly-to.html
test/examples/timeline-animation.html

HTTPS relevant links

---

src/source/geojson_source.ts

There is a small typo in the source code. It seems to be not exposed to the outside, so it's not a breaking change.

Fix a typo in the type

---

ARCHITECTURE.md
CHANGELOG.md
docs/README.md
src/source/tile_cache.ts
src/ui/handler/scroll_zoom.ts
src/util/actor.ts
src/util/ajax.test.ts
src/util/find_pole_of_inaccessibility.ts
src/util/geolocation_support.ts
src/util/intersection_tests.ts
src/util/is_char_in_unicode_block.ts
src/util/script_detection.ts
src/util/util.ts
test/README.md

Few a few URLs and typos

---

.editorconfig
.vscode/extensions.json

Add an .editorconfig config

---

docs/index.md

Closes https://github.com/maplibre/maplibre-gl-js/issues/4305#issuecomment-2182243048

Fix link MapLibre Native

---

docs/guides/large-data.md
src/source/geojson_source.ts
src/ui/handler/cooperative_gestures.ts

Used htmlproofer to find some more dead links.

Fix dead links

---

README.md

Merge only after the maplibre.github.io pr has been merged.

Add mapme logo

---

src/shaders/shaders.ts

Fixes failing render tests in globe branch.

Terrain fix

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docs/README.md
docs/plugins.md
src/util/web_worker.ts

+ minor markdown formatting fixes

Fix various typos

---

test/integration/README.md

Remove dangling link to missing browser test readme

---

test/integration/README.md

Fix typo in integration test readme

---

CONTRIBUTING.md

Fix two broken readme links

---

test/integration/README.md

Use npx instead of global install for vt2geojson.

---

docs/index.md

small adjustment to make the map a bit taller
before
after

docs: adjust map height

---

CHANGELOG.md
src/style/style.ts

- N/A: ~~Write tests for all new functionality.~~
Making this API doc more readable: https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/TransformStyleFunction/
Not sure if there is a good way, to make an actual list aka `<ul>`.
Before:
After:

docs: TransformStyleFunction improvements

---

docs/guides/index.md

Fix docs typo

---

CHANGELOG.md

fix broken link in changelog

---

CHANGELOG.md
package-lock.json
package.json
rollup.config.ts
test/bench/rollup_config_benchmarks.ts

Replace rollup-plugin-sourcemaps with rollup-plugin-sourcemaps2

---

src/ui/camera.test.ts

Small cleanup after the globe merge.
Close #4793

use platform instead of jest.done

---

src/source/geojson_source.test.ts
src/ui/camera.test.ts

This clears the unwanted logs when running unit tests...

Clean up console log in unit tests

---

test/examples/pmtiles.html

This just updates the example library version and fixes the link to osm.org/copyright.

pmtiles example: bump library version, fix link to OpenStreetMap.

---

.github/workflows/create-bumb-version-pr.yml
.github/workflows/release.yml
CHANGELOG.md

This simplifies release flow and also adds prerelease release notes which I though didn't work well.
I've also fixed some issues I saw in the changelog.
The following is what caused me to look at it:

Remove deprecated actions, simplify release flow

---

CHANGELOG.md

Add migration note for `["geometry-type"]`

---

CHANGELOG.md

As discussed in the discussion just now, I think a bit of a longer wording for this might be more clear in how it breaks.
Currently this point is somewhat simple to gloss over if reading quickly ^^
To be clear:
Would be fine with closing this PR if you think the docs are currently sufficient.
We are on the same team ^^
PS: Could we also change the [release notes here](https://github.com/maplibre/maplibre-gl-js/releases/tag/v5.0.0)?

made the v5 geometry type change more explicitely documented.

---

docs/README.md

I only fixed a small typo error

docs: fixed small error

---

package-lock.json
package.json
src/style/style_layer.ts
src/util/web_worker_transfer.ts
test/build/min.test.ts

Alternative to #5892 that builds and passes tests.

Bump @maplibre/maplibre-gl-style-spec from 23.2.2 to 23.2.3

---

README.md

This should fix the logo showing twice on npm: https://www.npmjs.com/package/maplibre-gl

Make sure logo does not show up twice on npm

---

src/source/geojson_source.ts

docs: Fix a few Example URLs

---

CHANGELOG.md
src/ui/control/navigation_control.ts

Fix _rotatePitchHandler typo

---

README.md

PR to move sponsor logo in between tiers

Sponsor tier update

---

src/source/vector_tile_source.ts

https://maplibre.org/maplibre-gl-js/docs/examples/vector-source/ is 404'ing - I think this is probably the example it intends to point to

Update link to vector tile example in docstring

---

.github/dependabot.yml

Fixes https://github.com/maplibre/maplibre-gl-js/network/updates

chore(deps): fix dependabot complaining about semver configuration for github actions

---

src/source/source_cache.ts
src/symbol/placement.test.ts

Flatten, add comments, and move data handler...

Refactor source data handler
