maplibre/maplibre-gl-js

package.json
Main thing is updating package.json name to maplibre-gl, and changing our version back to an `-rc.1` patch release until we feel confident to (irrevocably) release v1.13.0.
=> Conservative update of package.json for maplibre

CODE-OF-CONDUCT.md, docs/making-a-release.md
As we start as a project, it can be debilitating in early days to live inside a previous project's docs, but of course many of them are extremely valuable and will be re-used. This PR adds a `docs/` subdir where we can start documenting our own less formally refined notes.... better rough docs that are accurate than polished docs that are wrong!
- Replace the /very/ Mapbox-legal specific CODEOFCONDUCT.md with a placeholder, indicating basic decency and that we will probably select a formal code of conduct shortly
- Document the actual series of steps Seth has been using to build+publish maps-gl releases to npm
=> Document MapLibre specific items

build/banner.js
This text is included in some files in the `dist` directory:
https://unpkg.com/browse/maplibre-gl@1.13.0-rc.3/dist/mapbox-gl.js
=> Change project name in the banner

test/unit/changelog.js
The changelog unit test currently verifies that the version in package.json exists in the changelog, unless the version contains the `-dev` string. We have been using `-rc` string in the version which will now also be ignored.
This is required before enabling CI testing
=> fix changelog unit tests

.gitattributes, .github/workflows/node.js.yml
Fixes #4 by following instructions no the "gl" package to get it working on headless linux. I made progress on the windows build, but couldn't quite get it happy invoking bash script files from npm run scripts.
=> Got github actions working

.github/workflows/analyze.yml, .github/workflows/build.yml, build/check-bundle-size.js
It looks like the `workflow_run` job can't tell what the pull request number or base sha are. Follow examples from https://github.com/search?l=&q=%22workflow_run%22+%22marocchino%2Fsticky-pull-request-comment%22&type=code which store an artifact from `pull_request` job containing those variables and then use them in the downstream `workflow_run` job.
Also add `haya14busa/action-workflow_run-status@v1` which reports status of the workflow run job back to the original pull request.
=> upload artifact with build info

src/util/ajax.js
Copied verbatim from https://github.com/mapbox/mapbox-gl-js/pull/10394/commits/0f5780720a0a04fe45e3c6959daad7bd10959d13.
Original patch authored by https://github.com/mourner.
=> fix ImageSource not working in FF/Safari

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Question.md, .github/PULL_REQUEST_TEMPLATE.md
Just text editing, did not touch .workflow to avoid breaking things too soon.
=> Remove mapbox specifics and branding from .github

build/.eslintrc, package.json
Document the eslint overrides used by the build scripts.
Most of them should be removed during the future cleanup.
=> add build scripts to eslinting

CHANGELOG.md, src/data/bucket/circle_bucket.js, src/data/bucket/fill_bucket.js, src/data/bucket/line_bucket.js, src/data/bucket/symbol_bucket.js, src/render/draw_circle.js, src/render/draw_symbol.js, src/style/pauseable_placement.js
This addresses 2 related bugs:
1. An unevaluated mapbox expression-object was used in a condition (`if (expression)`) to decide if sorting was necessary, the assumption was probably that the default constant value of `undefined` would skip sorting. However, the unevaluated mapbox expression is not the value `undefined`, but an expression-object describing the value and its type. So, even if the mapbox expression was a constant `undefined`, the check would never be true. This leads to a lot of unnecessary sorting.
This was already correct for the drawing sort in circles and symbols, and this is where the `sortFeaturesByKey` variable name originates.
2. Even where the check was correct, it would explicitly check if the sort-key was a constant with value `undefined` to skip sorting. However, …
=> Avoid sorting of features if the sort-key is constant

LICENSE.txt
After consulting with laywer: "MapLibre" is not a legal entity, so it should be changed to "MapLibre contributors". Please wait for discussion in steering committe before merging.
=> Change MapLibre to MapLibre contributors

CHANGELOG.md, src/geo/lng_lat.js, src/geo/mercator_coordinate.js, src/index.js, src/source/geojson_source.js, src/source/image_source.js, src/source/vector_tile_source.js, src/source/video_source.js, src/style/style_image.js, src/ui/camera.js, src/ui/control/fullscreen_control.js, src/ui/control/geolocate_control.js, src/ui/control/navigation_control.js, src/ui/events.js, src/ui/map.js, src/ui/marker.js, src/ui/popup.js
This pull requests updates the links to examples in JSDoc comments from Mapbox to MapLibre. The links are defined in the ```@see``` tags and they show up in the [documentation website](https://maplibre.org/maplibre-gl-js-docs/api/).
I did not migrate all existing examples to the new documentation website because some of them were incompatible with ```maplibregl``` or they required a mapbox access token, see https://github.com/maplibre/maplibre-gl-js-docs/pull/36. Links to examples that were not migrated are removed.
- 🔲 include before/after visuals or gifs if this PR includes visual changes 
- 🔲 write tests for all new functionality
- 🔲 …
=> Update example links

CHANGELOG.md, package.json, src/index.d.ts
Resolves #24 - copied the typescript definition file and added reference to package.json file.
The only problem I see is that I can't test it well without a build to see that the file is present in the npm package and that I can use it in a demo example.
Please let me know if there's a way to merge this and create a release candidate so I can test it.
=> Bring in typescript definition file

CHANGELOG.md, src/geo/lng_lat.js, src/geo/lng_lat_bounds.js, src/geo/mercator_coordinate.js, src/index.js, src/ui/camera.js, src/ui/control/attribution_control.js, src/ui/control/fullscreen_control.js, src/ui/control/geolocate_control.js, src/ui/control/navigation_control.js, src/ui/control/scale_control.js, src/ui/events.js, src/ui/map.js, src/ui/marker.js, src/ui/popup.js
This pull request replaces ```mapboxgl``` with ```maplibregl``` in the inline examples in the comments of the public API.
- ✅ add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog>Replace mapboxgl with maplibregl in JSDocs inline examples</changelog>`
=> Replace mapboxgl with maplibregl in JSDocs inline examples

README.md
This pull requests adds a note to the README to replace ```mapboxgl``` with ```maplibregl``` when migrating. This was not needed in maplibre-gl-js ```1.13.0``` but with ```1.14.0``` it is.
I also added in a link to the documentation website at https://maplibre.org/maplibre-gl-js-docs/api/.
- ✅ apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog' 
- please skip changelog
=> Update readme migration instructions

RELEASE-PROCESS.md
This pull requests adds a reminder to ```RELEASE-PROCESS.md``` to check that the version in ```package.json``` matches the version of the git tag.
- ✅ apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog' -> please skip changelog
=> Add version reminder when publishing a release

.github/workflows/ci.yml
This pull requests adds ```sudo apt update``` and ```sudo apt upgrade google-chrome-stable -y``` to the GitHub actions file ```ci.yml``` in order to get the latest version of google chrome. 
Right now we run into problems where ```/usr/bin/google-chrome``` has version 89 while ```chromedriver``` is at version 90.
See https://github.com/maplibre/maplibre-gl-js/issues/132#issuecomment-821325227 and https://github.com/maplibre/maplibre-gl-js/pull/119
- ✅  confirm your changes do not include backports from Mapbox projects (unless with compliant license)
- ✅  briefly describe the changes in this PR
- ✅ apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog' -> no change log
=> Update google-chrome with apt in ci before browser-test

README.md
This pull request updates the readme to better explain how to migrate from `v1.13.0` mapbox to `v1.14.0` maplibre.
- ✅  confirm your changes do not include backports from Mapbox projects (unless with compliant license)
- 😄 briefly describe the changes in this PR
- 👍  apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog' `skip`
- add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`
=> Add migration diff for javascript code block

CHANGELOG.md, src/ui/control/logo_control.js
As discussed in https://github.com/maplibre/maplibre-gl-js/issues/121#issuecomment-831017594 and brought up in https://github.com/EqualStreetNames/equalstreetnames/issues/191
I found out that the link in the bottom left (from the MapLibre logo) goes to Mapbox.com, but probably should not.
This PR aims to correct that, and also changes the help text of the function a bit.
=> Update link from logo from Mapbox to MapLibre

.github/workflows/publish-style-spec.yml, CHANGELOG.md, src/style-spec/CHANGELOG.md, src/style-spec/package.json
This pull request removes the `--dry-run` flag from the [`publish-style-spec.yml`](https://github.com/maplibre/maplibre-gl-js/actions/workflows/publish-style-spec.yml) action.
You find the output of the last dry run here: https://github.com/maplibre/maplibre-gl-js/pull/147#issuecomment-830681902
If merged, we will be able to publish `v13.17.0` of the style spec to NPM at `@maplibre/maplibre-gl-style-spec`.
- ✅  confirm your changes do not include backports from Mapbox projects (unless with compliant license)
- ✅  briefly describe the changes in this PR
- 👍  apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
- 👍 add an entry inside this element for inclusion in the `maplibre-gl-js` changelog: `<changelog></changelog>`
=> Publish style spec v14.0.0 to NPM

.github/workflows/publish-style-spec.yml
This pull requests adds the [`--access=public`](https://docs.npmjs.com/cli/v7/using-npm/config#access) flag to `npm publish` for the style spec, to avoid this error:
```
npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@maplibre%2fmaplibre-gl-style-spec - You must sign up for private packages
```
See https://github.com/maplibre/maplibre-gl-js/runs/2503036374 for the failing publishing run without this flag.
- ✅  briefly describe the changes in this PR
- ✅  apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog' `skip`
=> Add --access=public to style spec npm publish command

src/style-spec/README.md, src/style-spec/package.json
This pull request adds `-dev` to the style spec version in `src/style-spec/package.json`. This prevents accidental workflow runs of `publish-style-spec.yml`. The pull request also removes a note about `--mapbox-api-supported` in the readme of the style spec.
- 🐳  confirm your changes do not include backports from Mapbox projects (unless with compliant license)
- 👍 apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog' -> `no changelog please`
=> Add dev to style spec version

.github/workflows/ci.yml
The workflow `ci.yml` is failing because we use node `v10` and we run in the action `yarn global add geckodriver`, i.e. we always use the latest version of the geckodriver. Now `v2.0.0` of geckodriver came out and it requires at least  node `v12`. 
To fix this test I suggest in this pull request to restrict the geckodriver version range to `v1`.
Another approach would be to use geckodriver `v2.0.0` and move on to node `v12`, which is something we might want to do anyway sometime in the future.
- 🐋  briefly describe the changes in this PR
- 👍 apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog' -> please skip
=> Restrict geckodriver to version 1

README.md
Fixed a code snippet for migrating from mapboxgl, which was advising to change it to maplibre instead of maplibregl.
=> [Docs] Fixed code snippet typo in README

docs/README-unpkg.md
* This PR adds *notes on unpkg; tailored for MapLibre GL JS.*  
* This is useful for developers that want to fetch via unpkg a specific version (give me `1.14.0`), or at least versions (give me at least `1.14.x`), or `latest`.
* Developers can also fetch *release date*, `size` and `CHANGELOG` for any version using these notes on unpkg.
* Tested unpkg links in the readme including semver, `meta`
N/A:
=> Readme on unpkg; tailored for MapLibre GL JS

src/index.d.ts, src/ui/map.js, src/util/mapbox.js, test/unit/ui/map.test.js
- Added api for setting a transformRequest instead of only being set in the constructor
- This allows the map object to be created (without setting style so no rendering) and for the transformRequest to be dynamically set after the map object's instantiation
- EX: 
```
var map = new Map({
container: "map",
center: [-123.1187, 49.2819],
zoom: 10,
});
map.setTransformRequest((url: string, resourceType: string) => {});
map.setStyle(style);
```
=> added setTransformRequest to map to allow dynamically setting the transformRequestFn

src/index.d.ts
This PR is to update the typings definition to reflect the changes in the maplibre rename of mapbox elements. See #27
=> Rename mapbox to maplibre in typings file

CHANGELOG.md, src/ui/control/attribution_control.js
Prevents form from submitting when clicked
=> Add type='button' to attrib button

src/index.d.ts
The GeoJsonSource constructor is declared as private and should not be directly instantiated from outside, because to every GeoJSONSource also a corresponding SourceCache instance has to be created. 
https://github.com/maplibre/maplibre-gl-js/blob/0c6ead362589465ffa14a8feb99b689640c698d3/src/source/geojson_source.js#L89
Instantiating the GeoJSONSource from outside also leads to error messages when used with a bundler like webpack see https://github.com/mapbox/mapbox-gl-js/issues/3050   
Exporting the constructor in the typing files is missleading and error prone. This PR replaces the GeoJSONSource class declaration with an interface to get rid of the exported constructor.   
The GeoJsonSource class should only be consumed via Map#getSource and Layer#source. For adding GeoJSON features to …
=> Refactor the GeoJSONSource typings from class to interface to hide the private constructor

package.json, yarn.lock
This PR adds the GeoJSON declaration file as a dev dependency to the project.
There is now no need anymore to install the GeoJSON typings in separate step when working with GeoJSON sources in a Typescript project.
closes #180
=> Add GeoJSON declaration file as dev dependency

src/index.d.ts
- https://github.com/maplibre/maplibre-gl-js/issues/186
- Added a typescript type fix for `setTransfomrRequest`, it was errantly using an undefined type `RequestTransformFunction`. Switched it to `TransformRequestFunction`
- Tried to test this by yarn linking `maplibre-gl` to a package using typescript and running build/tsc. Didn't see errors before or after making this change so not 100% sure how to confirm this change
=> fix: update setTransformRequest to use TransformRequestFunction type

bench/gl-stats.html, src/css/maplibre-gl.css, src/ui/map.js, test/unit/ui/handler/box_zoom.test.js, test/unit/ui/handler/dblclick_zoom.test.js, test/unit/ui/handler/drag_pan.test.js, test/unit/ui/handler/drag_rotate.test.js, test/unit/ui/handler/keyboard.test.js, test/unit/ui/handler/map_event.test.js, test/unit/ui/handler/mouse_rotate.test.js, test/unit/ui/handler/scroll_zoom.test.js, test/unit/ui/handler/touch_zoom_rotate.test.js, test/unit/ui/map.test.js, test/unit/ui/map/isMoving.test.js, test/unit/ui/map/isRotating.test.js, test/unit/ui/map/isZooming.test.js, test/util/index.js
Remove missingcss method and mapboxgl-canary dom element. The only purpose is checking whether the css is added and warn if not. This is unnecessary bloat.
#74 (comment)
=> remove detectmissingcss method

CHANGELOG.md, src/index.d.ts
Since the release of the new version 1.15.0, I have an error in the declaration of 2 methods with the strict mode of Typescript. The strict mode of TS implies to fill the type of returns.
=> Fix compile time issue with typescript strict mode

CHANGELOG.md, package.json, src/ui/map.js
Fix bad css merge, update changelog, prepare to release 1.15.1
=> Fix bad merge, bump version to 1.15.1

src/index.d.ts
No code changes, just some type tweaks so that TS actually allows, what is already valid usage. Namely the use of padding in the easeTo method (even used in an example - https://maplibre.org/maplibre-gl-js-docs/example/offset-vanishing-point-with-padding/). Also allowing to include just some but at least one property in the padding definition (again, even th documentation allows omitting some - https://maplibre.org/maplibre-gl-js-docs/api/map/#map#setpadding).
=> Better typing of PaddingOptions and EaseToOptions

.stylelintrc, CHANGELOG.md, README.md, package.json, src/css/maplibre-gl.css, src/ui/anchor.js, src/ui/control/attribution_control.js, src/ui/control/fullscreen_control.js, src/ui/control/geolocate_control.js, src/ui/control/logo_control.js, src/ui/control/navigation_control.js, src/ui/control/scale_control.js, src/ui/handler/box_zoom.js, src/ui/handler/shim/drag_pan.js, src/ui/handler/shim/touch_zoom_rotate.js, src/ui/map.js, src/ui/marker.js, src/ui/popup.js, test/browser/util/browser.js, yarn.lock
**TL;DR:**
This PR reverts the breaking change introduced in v15.1.0 by adopting a dual naming scheme for the CSS Classe name throughout the project.
Addresses concerns voiced in https://github.com/maplibre/maplibre-gl-js/issues/83 & https://github.com/maplibre/maplibre-gl-js/pull/185 
Closes https://github.com/maplibre/maplibre-gl-js/issues/199
Resolves https://github.com/visgl/react-map-gl/issues/1513
This PR is aimed at making maplibre 1.* more backward compatible and making sure that developers working with it and other mapbox/maplibre related tools are not depending on other packages adopting the new naming scheme right now.
=> fix breaking changes to css classnames

src/style-spec/expression/definitions/assertion.ts, src/style-spec/expression/definitions/at.ts, src/style-spec/expression/definitions/case.ts, src/style-spec/expression/definitions/coalesce.ts, src/style-spec/expression/definitions/coercion.ts, src/style-spec/expression/definitions/collator.ts, src/style-spec/expression/definitions/comparison.ts, src/style-spec/expression/definitions/format.ts, src/style-spec/expression/definitions/image.ts, src/style-spec/expression/definitions/in.ts, src/style-spec/expression/definitions/index.ts, src/style-spec/expression/definitions/index_of.ts, src/style-spec/expression/definitions/interpolate.ts, src/style-spec/expression/definitions/length.ts, src/style-spec/expression/definitions/match.ts, src/style-spec/expression/definitions/number_format.ts, src/style-spec/expression/definitions/slice.ts, src/style-spec/expression/definitions/step.ts, src/style-spec/expression/definitions/within.ts, src/style-spec/expression/types.ts, src/style-spec/expression/values.ts
As @HarelM pointed out to me, instead of casting the style spec types each time we use them we can also give them the correct types in the place where they are defined first. 
- [❤️  ] confirm your changes do not include backports from Mapbox projects (unless with compliant license)
=> Fix style spec casts

flow-typed/vector-tile.js, package-lock.json, package.json, src/source/geojson_source.ts, src/source/geojson_worker_source.ts, src/style-spec/expression/definitions/within.ts, src/style/style.ts, src/types/non-typed-modules.d.ts, src/util/vectortile_to_geojson.ts
- Remove imports of @mapbox/geojson-types
- Update GeoJSON types (untested build as TS WIP, but reduces tsc errors)
- Errors from 615 -> 609
- Marked as draft because currently difficult to test. I will try to improve the PR when I can get things building and more stable
=> Typescript: Remove @mapbox/geojson-types and replace with @types/GeoJSON'

src/types/glsl.d.ts
Adding d.ts file so Typescript knows what to do importing .glsl files
https://stackoverflow.com/questions/48741570/how-can-i-import-glsl-as-string-in-typescript
Reduces 629 -> 575 (54 errors removed)
=> Typescript: add glsl.d.ts to allow import of .glsl files

.eslintrc, src/geo/transform.ts, src/ui/control/fullscreen_control.ts
JavaScript behaves slightly differently with overriding class members. In JS they are just overridden completely, in TS they are overridden in type, so it is fine to have multiple similarly named members. This change to .eslintrc switches off the JS rule and adds the relevant TS rule to allow correct behavior.
=> Typescript: fix lint and update .eslintrc with alternate TS rule

src/data/bucket/symbol_bucket.ts, src/data/feature_index.ts, src/geo/transform.ts, src/render/draw_symbol.ts, src/render/painter.ts, src/render/program/background_program.ts, src/render/program/clipping_mask_program.ts, src/render/program/collision_program.ts, src/render/program/debug_program.ts, src/render/program/fill_extrusion_program.ts, src/render/program/fill_program.ts, src/render/program/heatmap_program.ts, src/render/program/raster_program.ts, src/render/program/symbol_program.ts, src/render/uniform_binding.ts, src/source/query_features.ts, src/source/tile.ts, src/source/tile_id.ts, src/style/style_layer.ts, src/style/style_layer/circle_style_layer.ts, src/style/style_layer/custom_style_layer.ts, src/style/style_layer/fill_extrusion_style_layer.ts, src/symbol/collision_index.ts, src/symbol/placement.ts, src/symbol/projection.ts, src/util/primitives.ts, src/util/window.ts
Some types seem to be Float32Array when it seems they should often be gl-matrix types and constructors.
Because we are in the middle of porting to Typescript it is hard to confirm that this doesn't break more than it fixes, however for my fork at the time of the MR the errors in tsx went from `615` down to `593`.
UPDATE: latest `226` -> `202` // this is a moving target, latest is about 20 errors fixed by this branch (I assume 4 got merged in as unrelated issues)
UPDATE: last check I see 39 errors left after the changes in this branch
The PR is WIP, please comment and I'll do my best to fix.
=> Typescript: updates to gl-matrix (Draft - hard to test as tsc failing)

.github/workflows/publish-style-spec.yml, .github/workflows/release.yml, RELEASE-PROCESS.md
In the past we have used personal NPM access tokens to publish this library. With the number of packages growing (`maplibre-gl-style-spec`, `maplibre-gl-leaflet`, `maplibre-gl-geocoder`) @nyurik created now an npm organization access token for `@maplibre` which is stored in the organization secrets of the GitHub `maplibre` org. The name of the secret is `NPM_ORG_TOKEN`. This token is shared with selected projects in the GitHub `maplibre` org (`maplibre-gl-js` and `maplibre-gl-geocoder`). If additional projects need access to this token, please contact @nyurik on slack.
- [✅  ] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
- [🐋  ] apply changelog label ('bug', 'feature', 'docs', etc) or …
=> Use organization secret NPM_ORG_TOKEN

package.json, test/expression.test.js
very minor changes to get `npm run test-expression` working
- point file imports to built js files in rollup/build/tsc (requires build before running tests), not original paths which were renamed to .ts 
- call node directly rather than using run-node with it's flow removal script and `esm`
- add node flags as mentioned by @HarelM (only `--experimental-specifier-resolution=node` appears necessary, tests still run and pass without `--experimental-json-modules`)
- update `__filename` which is no longer available in node 14 to `fileURLToPath` from `url` library
=> Typescript: fix running of test-expression

package.json, test/query.test.js
- couple of minor changes same as previous **test-expression** that get the tests running (but failing)
=> Typescript: get "npm run test-query-node" running

test/unit/style/load_glyph_range.test.js, test/unit/style/style.test.js
completely Harel's fix! .. I was struggling for quite a while then we did a call with screenshare and fixed straight away..
=> Typescript: unit tests remove window from window.XHRHttpRequest

CONTRIBUTING.md, README.md
This pull request fixes a broken link to https://github.com/maplibre/maplibre-gl-js/discussions in README and CONTRIBUTING as well as a typo in README.
=> Fix typo and broken link in readme and contributing

src/util/primitives.ts, test/stub_loader.js, test/unit/util/primitives.test.js
Fix to frustum tests (only addresses tests run with `npm run test-unit-file test/unit/util/primitives.test.js`)
- I'm not 100% convinced these tests are representative
- Failing was due to rounding and saving back into typed array, however WHY was it being rounded? Well so that the tests could compare with less precision.. however real world usage this is not an issue.
- Test projection and inverseProjection matrix are different Array types to actual class.. to get the tests to pass it needs to be either Float64Array or [] (JS native Array), using either Float32Array or mat4 (using Float32Array internally) is off by a very small amount so tests with hard coded expected values fail. Again what is the real world affect of this is not clear.. would be good to verify this outside of tests or …
=> Typescript: unit tests Frustum issues

package.json
We changed `yarn `to `npm `in  https://github.com/maplibre/maplibre-gl-js/pull/213
So we should change the script `prepare-publish` too
=> One forgotten yarn install?

docs/life-of-a-tile.md
See https://github.com/maplibre/maplibre-gl-js/pull/245
=> Life of a tile

.github/workflows/build.yml, .github/workflows/ci.yml
So far we were running CI only against pull requests that want to be merged to the `main` branch. This is inconvenient for development on the `typescript` branch. 
With this change here, CI will run on all pull requests, independent of the target branch.
=> Run CI on all pull requests

src/style/style_layer/custom_style_layer.ts
remove comment and change comment in jsdoc (?) definition
=> Remove custom layer comment and update type in jsdoc

bench/benchmarks/worker_transfer.js, src/data/feature_position_map.ts, src/render/painter.ts, src/source/source_cache.ts, src/source/worker_tile.ts, src/style/light.ts, src/style/style_layer.ts, src/style/style_layer/line_style_layer.ts, src/style/style_layer_index.ts, src/util/util.ts, test/unit/util/util.test.js
This pull request removes polyfill functions used for IE11 support.
And 368d3800665866bbbe957d1c7e4d514eb377913e removes two unused functions from `src/util.ts` (alreads present in `src/util/mapbox.ts`): they are not used in the code and are not(?) part of the api.
=> Remove support of IE11

src/data/bucket/line_bucket.ts, src/render/texture.ts, src/source/source_cache.ts, src/style-spec/expression/compound_expression.ts, src/style-spec/expression/definitions/coalesce.ts, src/style-spec/expression/definitions/interpolate.ts, src/style-spec/expression/definitions/step.ts, src/style-spec/expression/evaluation_context.ts, src/style-spec/visit.ts, src/style/properties.ts, src/symbol/mergelines.ts, src/ui/control/fullscreen_control.ts, src/ui/handler/box_zoom.ts, src/util/worker_pool.ts
Unnecessary casts for 'undefined' or 'null' as 'any'. Searched for `undefined as any` and `null as any` across the source. All of the results could be trivially removed.
Fixes #281
=> Remove undefined as any casts

CHANGELOG.md, src/symbol/symbol_layout.ts, test/unit/data/symbol_bucket.test.js, test/util/create_symbol_layer.js
Treats null/undefined the same as false for the image sdf property, eliminating a console warning in the process.
Fixes #303
=> Default handling for image.sdf

package-lock.json, package.json, src/util/offscreen_canvas_supported.ts
Fixes #305
This is probably due to when this supported method is called.
It used to be using the `window.` in the past which was removed.
This causes this kind of code to fail when using inside workers.
I hope this is the last place...
=> Offscreencanvas error fix

src/style-spec/CHANGELOG.md, src/style-spec/package.json
This pull request checks if we can still publish `@maplibre/maplibre-gl-style-spec` on NPM after the typescript migration. Closes https://github.com/maplibre/maplibre-gl-js/issues/275.
=> Bump style spec to v14.0.1-rc.1

.github/workflows/release.yml
We have published MapLibre GL JS version `2.0.0-pre.1` on NPM with the intention that this would be a pre-release which is unstable. However, currently `npm install maplibre-gl --save` will indeed get the unstable pre-release instead of the latest stable release. This is not what we want but we are also not the first ones to fall into this trap, see https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420.
This pull requests add a `--tag next` to `npm publish` if it is a pre-release. Like this the version will not be tagged as `latest` (which is the default).
=> Publish pre-releases on npm with `next` tag

package.json
I hope this fixes the release workflow error
```
Error: No files matching the pattern "'src/css/maplibre-gl.css'" were found.
at D:\a\maplibre-gl-js\maplibre-gl-js\node_modules\stylelint\lib\standalone.js:212:12
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
(https://github.com/maplibre/maplibre-gl-js/runs/3517866490?check_suite_focus=true)
=> Escape quotes around stylelint file argument

src/style-spec/package.json
Follow-up on https://github.com/maplibre/maplibre-gl-js/pull/310 to publish the actual new version of the style spec.
=> Bump style spec to v14.0.1

src/render/uniform_binding.ts, test/unit/render/uniform_binding.test.js
UniformMatrix4f expects to be initialized with an all-zeros array, while mat4.create() creates an identity matrix. Subsequent calls to UniformMatrix4f.set with an identity matrix will become no-op as gl.uniformMatrix4fv won't be called.
Fixes #341
=> Fix for uninitialized UniformMatrix4f

.github/workflows/ci-test-render.yml
This pull request adds a new workflow file which contains the `build_lint_test` job from the release workflow. This runs in particular the `test-render` script which seems to be failing at the moment. Note that `build_lint_test` in the release workflow actually does not build the library, which is strange.
=> Copy-paste `test-render` from release workflow

test/suite_implementation.js
Fix some broken implementation in suite_implementation due to the removal of `window` and the migration to `global`.
This allows the `test-render` to run to completion without throwing exceptions.
Having said that, `test-render` doesn't seem to fully pass and I get an out of memory when I run it locally, I don't know how this will behave in the CI though.
I think it might be worth looking into the failing tests as they seem to point on issues that might be real, but might existed before typescript migration. I don't know, I'll open a different issue about it...
=> Fix issues in suite implementation for test-render to run

.github/workflows/ci-test-render.yml
Reduces steps in `ci-test-render.yml` which saves time and console output.
=> Run only `build-dev` and `test-render`

CHANGELOG.md, src/source/tile_id.ts, test/unit/source/tile_id.test.js
Currently tile URL placeholders are replaced only once in a URL. If the placeholder appears more than once, it additional placeholder doesn't get replaced. This is due to the replace function only replacing the first instance of a string. The simple solution is to us a global regex with the replace function. Performance wise there is little difference (regex is actually a tad bit faster in nearly all browsers).
I came across this issue on a project a couple years ago, but thought it was an edge case and workaround it with a transform request, but just saw this issue:  https://github.com/maplibre/maplibre-gl-js/issues/346 and see I'm not the only one who ran into this. This fix works for both raster and vector tile URLs.
- [ N/A ] include before/after visuals or gifs if this PR includes …
=> Improve tile URL placeholder support

.eslintrc, src/style/style_layer.ts, src/style/style_layer/circle_style_layer.ts, src/style/style_layer/fill_extrusion_style_layer.ts, src/style/style_layer/fill_style_layer.ts, src/style/style_layer/heatmap_style_layer.ts, src/style/style_layer/line_style_layer.ts, src/style/style_layer/symbol_style_layer.ts
Factors out improvements to the style layer inheritance from the `test-render-revert` branch, https://github.com/maplibre/maplibre-gl-js/pull/367.
@HarelM can you comment on the motivation for this?
=> Improve style layer inheritance

bench/rollup_config_benchmarks.js, bench/versions/benchmarks.js
first part pointing benchmark config to worker.js output from worker.ts in rollup/build/tsc folder
NOTE:
This is just to try and address the immediate problem and share how to move forward so we can work on fixing other bits.
I think the better solution might be to set the benchmarks up to accept Typescript files directly (using node-ts or whatever) so we don't have to compile every time or risk running against old files etc. Makes debugging a bit easier too with a single source of truth
=> updating config wip

bench/benchmarks/expressions.ts, bench/benchmarks/filter_create.ts, bench/benchmarks/hillshade_load.ts, bench/benchmarks/layout.ts, bench/benchmarks/layout_dds.ts, bench/benchmarks/paint.ts, bench/benchmarks/placement.ts, bench/benchmarks/query_box.ts, bench/benchmarks/query_point.ts, bench/benchmarks/style_layer_create.ts, bench/benchmarks/style_validate.ts, bench/benchmarks/symbol_layout.ts, bench/benchmarks/worker_transfer.ts, bench/lib/benchmark.ts, bench/lib/create_map.ts, bench/lib/fetch_style.ts, bench/lib/tile_parser.ts
For consistency with the typescript migration I propose to migrate the benchmarks with `flowts`, as @HarelM suggested.
=> Run `flowts --no-prettier` on `lib` and `benchmarks`

bench/benchmarks/expressions.ts, bench/benchmarks/hillshade_load.ts, bench/benchmarks/layers.js, bench/benchmarks/layout.ts, bench/benchmarks/layout_dds.ts, bench/benchmarks/paint_states.js, bench/benchmarks/remove_paint_state.js, bench/benchmarks/style_layer_create.ts, bench/benchmarks/style_validate.ts, bench/benchmarks/worker_transfer.ts, bench/lib/benchmark.ts, bench/lib/fetch_style.ts, bench/lib/tile_parser.ts
- minor cleanup:
- whitespace around braces in imports
- switch quotes to single quotes
- remove quotes for object keys with no hyphens
- semicolons instead of commas in type definitions
=> [benchmarks] Minor cleanup of ts file formatting

package-lock.json, package.json, src/index.ts, src/types/non-typed-modules.d.ts, src/ui/map.ts
The problem with the failing render tests is that mapbox-gl-supported 2.0 introduced breaking changes (with the right semver).
Since they don't have type definitions, definitions were added to this project "by hand",
This caused the breaking changes to be ignored when updating the package which causes the tests to fail.
This is basically a "by the book" update of this library.
=> Upgrade mapbox-gl-supported library

.github/workflows/publish-style-spec.yml, src/style-spec/CHANGELOG.md, src/style-spec/package.json
As reported in https://github.com/maplibre/maplibre-gl-js/issues/400, currently our style spec CLI scripts are broken. I think this is related to rollup and typescript putting files not in `dist`, but rather `dist/style-spec`.
- [🐳  ] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
- [ 🍏 ] briefly describe the changes in this PR
=> Fix entry point paths

CONTRIBUTING.md
Updates node and npm versions in the contributing guidelines.
- [🐳  ] confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
- [ 📗 ] briefly describe the changes in this PR
=> Recommend `node 14` and `npm 7`

src/render/glyph_manager.ts
=> Fix tinySdf upgrade and cleaned up a bit.

bench/benchmarks/style_layer_create.ts, bench/lib/fetch_style.ts
tiny fix that breaks a lot of tests.. after this they all run for me
=> [Benchmarks] add then() back to fetch(url) in fetch_style (fixing benchmarks)

.eslintrc, src/geo/lng_lat_bounds.test.ts, src/geo/transform.test.ts, src/gl/vertex_buffer.test.ts, src/render/glyph_manager.test.ts, src/source/tile_cache.test.ts, src/source/tile_id.test.ts, src/source/vector_tile_source.test.ts, src/source/worker.test.ts, src/style-spec/function/index.test.ts, src/style-spec/util/color.test.ts, src/style/light.test.ts, src/style/style_layer.test.ts, src/util/evented.test.ts
Do we like to use the rule https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-to-be.md ?
I have added it here and checked the tests via` npm run lint -- --fix`.
=> [Jest Lint] Add rule prefer-to-be 

.eslintrc
Do we like to use the rule https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-to-contain.md ?
I have added it here and checked the tests via` npm run lint -- --fix`. All test files are fine currently. But I think it good to get a message, in future.
=> [Jest Lint] Add rule `prefer-to-contain`

.eslintrc
Do we like to use the rule https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-commented-out-tests.md ?
I have added it here and checked the tests via` npm run lint -- --fix`. There is no commented out test currently. But I would like it to get a message in case.
=> [Jest Lint] Add rule `no-commented-out-tests`

.eslintrc, src/style-spec/composite.test.ts, src/style-spec/function/index.test.ts
Do we like to use the rule https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-alias-methods.md ?
I have added it here and checked the tests via` npm run lint -- --fix`.
=> [Jest Lint] Add rule `no-alias-methods`

.eslintrc
I think this rule is fine too:
https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-deprecated-functions.md
What do you mean
=> [Jest-Lint] Add rule `no-deprecated-functions`

src/source/tile_id.test.ts, src/source/tile_id.ts
Replace {r} in tile urls with @2x for devices with a pixelratio > 1.
This feature is compatible with leafletjs and useful to fetch hidpi tiles for
layers that support it.
=> handle {r} in tile urls for hidpi raster tiles (fix #141)

package.json, src/data/bucket.ts, src/data/bucket/circle_bucket.ts, src/data/bucket/fill_bucket.ts, src/data/bucket/fill_extrusion_bucket.ts, src/data/bucket/line_bucket.ts, src/data/bucket/symbol_bucket.ts, src/data/evaluation_feature.ts, src/data/feature_index.ts, src/data/load_geometry.ts, src/data/program_configuration.ts, src/source/geojson_wrapper.ts, src/source/tile.ts, src/source/vector_tile_worker_source.ts, src/source/worker_tile.ts, src/style/style_layer.ts, src/style/style_layer/circle_style_layer.ts, src/style/style_layer/fill_extrusion_style_layer.ts, src/style/style_layer/fill_style_layer.ts, src/style/style_layer/line_style_layer.ts, src/types/non-typed-modules.d.ts, src/util/vectortile_to_geojson.ts
I wanted to iron out all the non-typed modules and leave it so that the only change needed is to update the package once the vector-tile typings get merged.
Currently this is not the case as the vector tile types are defined globally, which I don't see a good reason to keep.
This PR irons things out.
Relevant PR in vector-tile-js repo is the following for future reference:
https://github.com/mapbox/vector-tile-js/pull/78
=> Remove global typings

src/source/tile_id.test.ts, src/source/tile_id.ts
Follow up to #637 as I did not know about the equivalent feature in mapbox-gl-native at the time.
I'm not sure what to do exactly about the changelog entry as we of course don't want 2 entries for this.
=> use {ratio} instead of {r} to be compatible with maplibre-gl-native

src/ui/control/attribution_control.ts
In https://github.com/maplibre/maplibre-gl-js/pull/557 I forgot to set the `open `attribute in the `details `element when details is not displayed as **compact** but as open by default. This is automatically set with the **compact** option when the `summary `element is clicked (https://www.w3.org/TR/2011/WD-html5-author-20110809/the-details-element.html).
This error was reported in the issue https://github.com/maplibre/maplibre-gl-js/issues/640.
=> add attribut open to html details element, if no compact is used

CHANGELOG.md, src/css/maplibre-gl.css
Close #338
When I set a popup on a marker and click on it, the focus is on the close button (x) and part of the text in the popup is hidden. This happens only when you click on the marker for the first time.
So, I changed the padding-top of the popup from 10px to 15px.
`<changelog>Fix padding-top of the popup to improve readability of popup text (#354).</changelog>`
=> Set padding-top: 15px for popup card.

CHANGELOG.md, src/util/ajax.ts, test/unit/util/ajax.test.js
When converting a byte buffer to a [CanvasImageSource](https://developer.mozilla.org/en-US/docs/Web/API/CanvasImageSource), maplibre uses either an [ImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap) if supported or an [HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) as fallback.
HTMLImageElement has many flaws, such as [the transparent pixel hack to avoid memory leaks](https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/ajax.ts#L304-L308). Therefore the ImageBitmap seems more reliable and is the preferred image source.
In order to load the byte buffer to an ImageBitmap the library checks if the feature is available on the browser. Currently the function checks if the function createImageBitmap is defined **and** if …
=> Use createImageBitmap when supported

src/ui/camera.test.ts
`camera.test.ts` has a test which fails sometimes since we migrated it from tap to jest. The original code of this test looked like this:
https://github.com/maplibre/maplibre-gl-js/blob/cb3a4200bfbc113969e9dcbedae2aa7655f9aa98/test/unit/ui/camera.test.js#L1624-L1627
which looks like a strange use of comparing a limited number of digits. Basically this means if `abs(timeDiff) < 10`, the test passes. If we divide `timeDiff` by 100 and check to to first digit after the decimal point, we should get the same result.
=> Fix timediff test

src/ui/events.ts
Adds type for `styleimagemissing` event.
=> Add type for styleimagemissing event

src/style/style.ts, src/ui/map.ts
Defines the return type of `getSource` as possibly `undefined` as described in JSDoc.
=> Define return type of getSource as possibly undefined

CHANGELOG.md, src/ui/map.ts, test/unit/ui/map.test.js
<changelog>Fix events being fired after Map#remove has been called when the WebGL context is lost and restored (#726)</changelog>
=> Fix events being fired after Map#remove has been called when the WebGL context is lost and restored (#726)

CHANGELOG.md, build/generate-style-spec.ts, src/style-spec/feature_filter/convert.ts, src/style-spec/feature_filter/feature_filter.test.ts, src/style-spec/types.ts
=> support nested filter specification types

src/geo/lng_lat.ts, src/index.ts, src/source/geojson_source.ts, src/source/image_source.ts, src/source/source.ts, src/source/vector_tile_source.ts, src/source/video_source.ts, src/style-spec/CHANGELOG.md, src/style-spec/format.ts, src/style-spec/package.json, src/style-spec/reference/v8.json, src/style-spec/validate_style.min.ts, src/symbol/shaping.test.ts, src/ui/camera.ts, src/ui/control/attribution_control.ts, src/ui/control/control.ts, src/ui/events.ts, src/ui/map.test.ts, src/ui/map.ts, src/ui/marker.ts, src/ui/popup.ts
This pull request updates jsdocs comments on the removal of the `mapbox://` protocol, which happened in the TypeScript migration [#209](https://github.com/maplibre/maplibre-gl-js/pull/209).
The style specification is updated too, to reflect the removal of `mapbox://` and its major version is bumped from 14 to 15.
Since I was cleaning up the docs, I also replaced `Mapbox` with `MapLibre` and removed links to mapbox.com.
=> Update docs on removal of `mapbox://` protocol

build/release-notes.js
Fixes the release-notes script.
=> Fix release notes script to be in es6 import format

CHANGELOG.md
Related to #783.
- v1.15.2 works with Chrome 49+.
- v2.0.0 require Chrome 66+.
It is breaking change for some cases when Chrome 49-65 support needed.
So, it may be useful to specify that Chrome 66+ is required for v2 in the Release notes.
=> Add Chrome 66+ notice to v2 breaking changes

package-lock.json, package.json
<changelog>Update TypeScript to 4.5.4</changelog>
I can see the currently used ts version was release in late August. How come dependabot doesn't update this automatically in the monthly check?
=> chore: update typescript to 4.5.4

bench/README.md, bench/gl-stats.html, bench/gl-stats.js, package.json
This fixes and refactors bench/gl-stats.js, a script to run a short zoom animation and gather some gl statistics.
I also added some minimal documentation so people can find it and know how to run it.
=> Resurrect gl-stats.js

build/release-notes.js
Simplfies release notes generation. Release notes are only built from the changelog and git tags are not taken into account anymore. Makes testing `build/release-notes.js` easier and the script more predictable. Fixes #780.
=> Build release notes from changelog only

CHANGELOG.md, package-lock.json, package.json
Fixes #811 by making sure everything in the dist folder is packed by npm.
This probably worked in npm 6 but was a bug that was fixed in later version if I need to guess...
=> Update files in package.json, bump to version 2.0.4

package.json
Our CI/CD currently test Node 16, but maplibre can run on many more versions. Having node >=16 (#797) in package.json break all these build systems, but adding i.e. node 14 put us in the position of claiming node 14 support without testing it.
I therefore suggest we simply removed the engines list, to let any build system install and try to run the maplibre code.
=> Disable strict list of supported node versions package.json

bench/README.md, bench/run-benchmarks.js
run-bechmarks.js now handles different --compare parameters and also passes them on as url parameters. That way the script default output more closely follows the default output in the browser and supports the same parameters.
This also fixes an error when executing run-benchmarks.js on a clean checkout of main as the old script always expected two versions to benchmark but only got one in that case.
=> run-benchmarks.js: handle --compare parameters

.stylelintrc, src/css/maplibre-gl.css
I think we should use the standard rule string-quotes from [stylelint](https://stylelint.io/user-guide/rules/list/string-quotes/).
Even though both quotes are valid. I think it is better to follow the common style guides. For example, [Google's style guide] (https://google.github.io/styleguide/) recommends using double quotes for HTML and single quotes for CSS.: https://google.github.io/styleguide/htmlcssguide.html#CSS_Quotation_Marks
=> [Stylelint] string-quotes

bench/rollup_config_benchmarks.js, package-lock.json, package.json, tsconfig.json
Buble was made for a different day and age.
We only use it for benchmarks, but setting "jsx": "react" in tsconfig.json makes it redundant.
=> Remove obsolete buble compiler

bench/rollup_config_benchmarks.js
bench/benchmarks_view.tsx transpiles to .js and not .jsx. 
This PR fixes the broken path in benchmark rollup config.
=> Fix broken path in benchmark build

.stylelintrc, src/css/maplibre-gl.css
Another stylelint rule [ alpha-value-notation](https://stylelint.io/user-guide/rules/list/alpha-value-notation/). 
I'm not fully convinced about this one, because not even [w3c](https://drafts.csswg.org/css-color-3/#alphavalue-def) uses it on their website. But since it is a standard rule in stylelint and I think it is good to handle everything consistently, I suggest using it anyway.
=> [Stylelint] alpha-value-notation

src/ui/map.ts
JSDocs wants type followed by variable name in function argument documentation.
=> Fix `setPixelRatio` jsdocs

bench/rollup_config_benchmarks.js, build/rollup_plugins.js, rollup.config.style-spec.js
We have a lot of warnings from rollup, because the next version of rollup-plugin-replace will have the setting         preventAssignment: true - and they recommend we opt-in now.
=> rollup plugin-replace:  enable preventAssignment

.github/dependabot.yml, package-lock.json, package.json
This updates a few packages not covered by dependabot to their latest versions.
I noticed our devDeps for right-to-left text `@mapbox/mapbox-gl-rtl-text` adds a mapbox-gl peer dependency  v0.2.2 - back in 2019 when the library last wass updated
```
"peerDependencies": {
"mapbox-gl": ">=0.32.1 <2.0.0"
}
```
https://github.com/mapbox/mapbox-gl-rtl-text/commit/046c611e38efb7a1335d7126662a6803c564f3f1
Any opinions on that? It's the BSD version, but we also have the option to make a fork and cut it out.
=> Update mapbox dependencies

package-lock.json, package.json
We can get to v13 with this PR, which is what our documentation repository use - but we can't update to the latest version (13.2.5), because of this: https://github.com/documentationjs/documentation/issues/1471
=> Bump documentation to 13.0.2

src/ui/camera.test.ts
fix #908 . Change timeDiff from being <10 sec to <20, so slower runners can pass test.
=> Fix camera tests on mac runners

.github/workflows/release.yml, .github/workflows/upload-benchmarks.yml
This hopefully fixes #861.
I'm not sure how to test workflows locally so this is as yet untested.
=> upload benchmarks_generated.js for releases as part of the release workflow

src/ui/camera.test.ts
The can apparently takes longer than the limit set in #910, so this raises the limit a bit further from 20 to 30, so the even the mac runner, which has a timeDiff of 22 sometimes, can pass every time.
=> Raise limit for camera test further

CHANGELOG.md, src/source/vector_tile_source.test.ts, src/source/vector_tile_source.ts, src/style/style.test.ts, src/ui/control/logo_control.test.ts
<changelog>Fix stale tiles being shown when calling VectorTileSource#setTiles while the map is moving</changelog>
Before this PR, when calling `VectorTileSource#setTiles`, the source cache was cleared before the TileJSON was reloaded asynchronously. If the map was moving while `VectorTileSource#setTiles` was called, it was possible for the cache to be repopulated with the old tiles if `VectorTileSource#loadTile` happened to be called before the TileJSON had been reloaded. This was due to the `VectorTileSource#tiles` property, which is used by `VectorTileSource#loadTile`, only being updated asynchronously after the TileJSON had reloaded.
=> Fix stale tiles being shown when calling VectorTileSource#setTiles while the map is moving

CHANGELOG.md, src/source/source_cache.test.ts, src/source/source_cache.ts, src/ui/events.ts, src/ui/map.test.ts, src/ui/map.ts
<changelog>Fire dataabort event when a tile request is aborted (#794)</changelog>
=> Fire dataabort event when a tile request is aborted (#794)

postcss.config.cjs
The old svgo options are no longer supported and we effectively disabled svgo usage with an error message.
This pull request fixes the options to the original intend. This does change the generated css though as svgo is used again.
I only checked the icons on http://localhost:9966/debug/debug.html in Safari so far and they look the same in main and this branch.
Alternatively we can generate the exact same css but without any error messages by just explicitly disabling svgo with `svgo: false`.
What should we do?
=> fix svgo options

jest.config.cjs, package-lock.json, package.json
Unused dependency, because glsl are converted to ts files before jest run.
=> Remove jest raw loader

.husky/pre-commit, package-lock.json, package.json
Sometimes CI fails because contributors forget to check for linting errors before pushing. 
This pull requests enables a pre-commit hook which runs `npm run lint` on every commit.
It uses husky https://github.com/typicode/husky which we have in the docs repo, too. I like it.
=> Use husky to lint on precommit

.stylelintrc
Stylelint makes 1000 warnings because it is linting our minified output in the dist folder. This pr exludes that folder.
=> Stylelint - Ignore dist folder

bench/gl-stats.html, bench/gl-stats.ts, bench/run-benchmarks.ts, package.json
bench/gl-stats.js > .ts
bench/run-benchmarks.js > .ts
Currently there is an issue in gl-stats where it doesn't load maplibre properly, and it's more clear when disabling headless mode for puppeteer. I have verified that the behavior is the same with js and ts, so it must have been introduced earlier.
=> Move gl-stats and run-benchmarks to ts

bench/rollup_config_benchmarks.ts, bench/styles/index.html, bench/versions/index.html
Slowly adapting for the new standard, I have moved benchmarks to use ES module format rather than UMD and AMD
=> Move bench to ES modules

bench/rollup_config_benchmarks.ts, bench/styles/index.html, bench/versions/index.html
Reverts maplibre/maplibre-gl-js#964
Benchmarks has troubling me most of the day, and it turns out this might be the root cause. I suggest we revert it for now to get things stabilized
=> Revert "Move bench to ES modules"

bench/rollup_config_benchmarks.ts, build/rollup_plugins.ts, build/web_worker_replacement.ts, package.json, rollup.config.style-spec.ts
Currently, the web worker is only enabled if watch mode is off, because the rollup node-resolve plugin doesn't look at typescript files by default, and it was configured to the wrong path. This pr fixes that, and it can hopefully unblock #961 
To test this PR, first go to the main branch and:
1. Delete the rollup/build/tsc/src folder
2. Run `npm run start-debug`
3. Open chrome dev console, and go to "sources" tap - there will be just "top -> localhost -> local files" in the left pane, which indicates that the web worker ain't running.
Now checkout this pr, and do the same.
The sources tap should now have "top" and some web workers, like in the image
=> Fix web worker in watch mode

package-lock.json, package.json, tsconfig.json
ts-node 10.5 moves the swc compiler support from experimental to stable [(release notes)](https://github.com/TypeStrong/ts-node/releases/tag/v10.5.0).
Whenever we run a ts file with the JIT compiler which we do a lot in postinstall, like shown below, we can now configure the  `--loader ts-node/esm` to use swc for near instant compilation.
```
node --loader ts-node/esm --experimental-specifier-resolution=node build/generate-shaders.ts
```
On my machine "postinstall" goes from 14 to 4 sec
=> Bump ts-node for 3x faster postinstall with swc

CHANGELOG.md, src/util/browser.ts
Same as #791 - Fixes NextJs bug, I hope - #768
=> Add typeof guard to performance variable

.stylelintrc, src/css/maplibre-gl.css
I think we should use the rule https://stylelint.io/user-guide/rules/list/function-url-quotes/
Quotes are optional but standard. But: Some special characters must be escaped. With the rule we avoid running into problems with this in future.
=> [Stylelint]  function-url-quotes/

CHANGELOG.md, src/render/uniform_binding.ts, src/ui/map.ts
Improve typings.
See linked issues in the changelog.
Fixes #790
=> Fixes #790 - improve typings for angular strict mode

CHANGELOG.md, src/source/source_cache.test.ts, src/source/source_cache.ts
<changelog>Fix SourceCache.loaded() always returning true following a load error (#1025)</changelog>
=> Fix SourceCache.loaded() always returning true following a load error (#1025)

.github/workflows/release.yml, CHANGELOG.md
Fixes #1042 - Adds dev, csp and prod to release pipeline in order for it to be in the npm package
=> Add missing builds to release pipeline

CONTRIBUTING.md
On new macOS installation, 'npm install' results in errors with the node_canvas module. Update CONTRIBUTING.md with missing setup step.
=> Instructions for missing node_canvas dependencies

.github/dependabot.yml
Bit anying that dependabot pull requests come in one after the other because we have a limit of 5 open pull requests. This changes the limit to 20.
=> Increase dependabot open pull request limit from 5 to 20

src/source/source_cache.test.ts, src/source/source_cache.ts
<changelog>Fix SourceCache.loaded() returning true when a source load error occurs while the source still has pending loads</changelog>
This PR fixes an issue related to #1025. When calling `GeoJSONSource.setData()` with an argument that can be successfully loaded right after a call to the same method with an argument that causes a load error (e.g. a URL pointing to a nonexistent resource), `Map.isStyleLoaded()` would return `true` after the `error` event had fired even though the `GeoJSONSource` still had a pending load. Here is an example: https://jsbin.com/hedesi/3/edit?html,console,output.
=> Fix SourceCache.loaded() returning true when a source load error occurs while the source still has pending loads

CONTRIBUTING.md
I added apple silicon guidelines for rebuilding a few node modules.
The render tests fail for node 16.14, so I updated the version to 16.13.
=> Update contribution guidelines for arm64 machines

CHANGELOG.md, src/style/style.ts, src/ui/map.ts
This PR adds FeatureIdentifier interface. This interface existed in [mapbox DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L940)
The interface changes `id: string | number` to `id?: string | number | undefined;`. Adding type support for undefined in the interface is supported because Style.setFeatureState, Style.removeFeatureState, and Style.getFeatureState implementations have logic to ensure target.id === undefined is safely handled.
=> FeatureIdentifier interface

CHANGELOG.md, src/ui/map.ts
Libraries like [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw) can extend Map with new events, for example, [draw.create](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md#events). Maplibre map.on, map.off, and map.once type parameter needs to support `string` to support these libraries and avoid type failures like 
"No overload matches this call.
Overload 1 of 3, '(type: keyof MapEventType, listener: (ev: (MapMouseEvent | MapLibreEvent<MouseEvent | TouchEvent | WheelEvent | undefined> | ... 10 more ... | MapWheelEvent) & Object) => void): Map', gave the following error.
Argument of type '"draw.create"' is not assignable to parameter of type 'keyof MapEventType'.
Overload 2 of 3, '(type: MapEvent, listener: Listener): Map', gave the following error.
Argument of …
=> Change type of map.on, map.off, and map.once parameter from "type:  MapEvent" to "type: MapEvent | string"

src/source/source_cache.test.ts, src/source/source_cache.ts
<changelog>Do not fire the data event for aborted tiles</changelog>
=> Do not fire the data event for aborted tiles

CHANGELOG.md, src/source/source_cache.test.ts, src/source/source_cache.ts, src/style/style.test.ts, src/style/style.ts
After Style instance removal all initialized sources and their resources (like HTTP requests) stay to live, that produce race conditions – like map style access after receiving of GeoJSON source response.
One of known issues is `cannot read properties of undefined (reading 'sourceCaches')` when you destroy the map instance during tiles load request.
=> fix: dispose SourceCache resources on Style remove

CHANGELOG.md, src/source/raster_tile_source.ts, src/source/tile.ts, src/source/vector_tile_worker_source.ts, src/ui/map.ts, src/util/ajax.test.ts, src/util/ajax.ts
Fixes expiry data on raster tiles fetched by browsers supporting offscreen canvas not getting automatically refreshed by mapbox.
=> Fix raster source refreshing (#700)

.github/workflows/build.yml, .github/workflows/publish-style-spec.yml, .github/workflows/release.yml, CONTRIBUTING.md, build/readme.md, build/rollup_plugins.ts, package.json, rollup.config.csp.ts, rollup.config.ts, test/bench/README.md, test/bench/rollup_config_benchmarks.ts
The unminified production target isn't tested, and seems somewhat useless, so I suggest we tidy up the build pipeline by removing it.
This way `npm run build-prod` can also be assigned to make the actual production build, which seems more intuitive.
=> Remove unminified production build

CHANGELOG.md, src/style/query_utils.test.ts, src/style/query_utils.ts, src/style/style_layer/line_style_layer.ts
bug
<changelog>Use correct location for mouse events of line layer with line-offset (#1108)</changelog>.
The `offsetLine` function uses a `ring` array that contains instances of the class `Point` from `@mapbox/point-geometry`. Methods of the `Point` class that are prefixed with `_` adjust the instance of the `Point` class in place, i.e. no new instance is created and the current instance is mutated as a side effect and returned. This goes wrong when the `zero` variable is reused.
In the solution of this pull request the `zero` variable is removed and new instances of the `Point` class are created when needed.
This fixes #1108 using a similar solution as in https://github.com/jack9ye/mapbox-gl-js/commit/ad2df2df734d26c85b9daa81c76eca9dc4f4508d, which is referred to in …
=> Fix: use correct location for mouse events of line layer with line-offset (#1108)

CHANGELOG.md, src/ui/events.ts
Accessing `MapTouchEvent`'s `type` property and comparing it to `"mousemove"` throws a TypeScript error. This PR fixes it.
Example:
```typescript
if (e.type === "touchmove") e.originalEvent.preventDefault();
```
The code above results in
```
This condition will always return 'false' since the types '"mousedown" | "mouseup" | "click" | "dblclick" | "mousemove" | "mouseover" | "mouseenter" | "mouseleave" | "mouseout" | "contextmenu" | "touchstart" | "touchend" | "touchcancel"' and '"touchmove"' have no overlap.
```
The event is already properly documented, nothing to do on that account.
=> [TypeScript] fix: missing `touchmove` in MapTouchEvent["type"]

build/generate-style-spec.ts, debug/terrain.html, src/render/terrain.ts, src/style-spec/error/validation_error.ts, src/style-spec/reference/v8.json, src/style-spec/validate/validate.ts, src/style-spec/validate/validate_terrain.test.ts, src/style-spec/validate/validate_terrain.ts, src/style-spec/validate_style.min.ts, src/style-spec/validate_style.ts, src/style/style.test.ts, src/style/style.ts, src/style/validate_style.ts, src/ui/control/terrain_control.ts, src/ui/map.ts
Add terrain to style spec and apply it when setting a style.
@prozessor13 @wipfli @birkskyum please review and let me know if I missed something.
I've used the debug page to make sure it works, nothing extra.
=> Add terrain to style spec

src/style-spec/reference/v8.json
https://github.com/mapbox/mapbox-gl-js/pull/8987 added `source.promoteId` that promoted a feature property to be used as the join key for feature-state, thus allowing feature-state ids to match on string values. The docs where never updated. This PR updates v8 specification feature-state docs to provide details on how promoteId can be used to match feature-state with features on string fields.
=> update v8 specification feature-state docs

CHANGELOG.md, package.json, yarn.lock
This PR should fix the security issue of the minimist dependency by bumping the version to 1.2.6.
Relates to #1129
=> Bump minimist from 1.2.5 to 1.2.6 for version 1.15.x

.github/workflows/add-pr-demo.yml, .github/workflows/remove-pr-demo.yml, test/integration/pr-demo/index.html
This is a revival of #328 which builds the library automatically and deploys the build output file from the `dist/` folder to the gh-pages branch on pull request.
This is useful for stackblitz and jsbins where one can make an examples with the code from a pull request.
Build output will be available at https://maplibre.org/maplibre-gl-js/pulls/<pr-number>
=> Create pull request demo on GitHub Pages

test/README.md, test/integration/README.md
fixes some broken/wrong links and removes a no longer working command from test documentation.
=> some small documentation fixes

test/integration/render/render.test.ts
Bugfix for render test results page. Some of the test paths have '#' chars, which need to be encoded for the expected/actual/diff images to show.
=> Encode hash char in render result path

debug/terrain.html, src/geo/transform.test.ts, src/geo/transform.ts, src/render/draw_terrain.ts, src/render/terrain.test.ts, src/render/terrain.ts, src/source/source_cache.ts, src/ui/marker.test.ts, src/ui/marker.ts
Fixes #1180 and #1181.
@wipfli @prozessor13 Feel free to review.
=> Fixes related to console errors and some typings improvement in terrain branch

debug/terrain.html
=> Use demotiles.maplibre.org

CHANGELOG.md, src/source/geojson_source.test.ts, src/source/geojson_source.ts, src/source/geojson_worker_source.test.ts, src/source/geojson_worker_source.ts, src/ui/events.ts
<changelog>Cancel pending GeoJSON requests when GeoJSONSource.setData() is called</changelog>
Currently, when `GeoJSONSource.setData()` is called with a new URL, the source waits for the previous URL to finish loading before issuing the request for the new URL. This PR proposes a solution where instead of waiting for the pending request to complete before issuing the new one, the pending request is canceled. The goal of this PR is to improve latency and avoid downloading unnecessary data.
=> Cancel pending GeoJSON requests when GeoJSONSource.setData() is called

README.md
As discussed in the governing board and announced on open collective, we would like to mention all sponsors who support us with recurring donations in the README. We can put the name, github handle, and if desired a company name.
@nyurik do you think the wording makes sense? 
Suggestions welcome on formulating this better. The point is just to say thanks to people and orgs who support us...
=> Add sponsors with recurring donations to the README

CHANGELOG.md, src/css/maplibre-gl.css
Overrides the default styles for `summary` elements on the attribution control. This is currently showing on iOS Safari, but overriding the styles hides it. It looks like this popped up as a result of changing the elements in #557.
Let me know if I can make any changes to this, thanks!
Before:
After:
=> reset attrib summary element styles

CHANGELOG.md, src/geo/transform.test.ts, src/geo/transform.ts, src/ui/map.test.ts
_constrain uses 'wrap()' to adjust minX, maxX and point.x to the same range
so that valid 'east of' and 'west of' comparisons can be made
Fixes bug in issue #1298 
- [x ] Manually test the debug page.
=> Transform._constrain handles bounds that cross the anti-meridian

src/geo/transform.test.ts, src/geo/transform.ts, src/render/terrain.test.ts, src/render/terrain.ts
This is a pull request on top of PR #1300. It adds a unit test for that PR's bug fix to [`Transform.coveringTiles()`](https://github.com/maplibre/maplibre-gl-js/blob/577f200072b9a55ce9b841bc04a21cde7603e01c/src/geo/transform.ts#L334). The affected code has been pulled out into a separate method, `Transform.getTileMinMaxElevation()`, so that it can be tested in isolation. (That method should probably be on [`DEMData`](https://github.com/maplibre/maplibre-gl-js/blob/main/src/data/dem_data.ts), but time has run away from me.)
This test fails on `main` but passes on the `covering_tiles_3d` branch.
=> Add unit test for calculating min/max elevation

.github/workflows/dependabot-auto-merge.yml
This pull request add a workflow to merge dependabot pull requests automatically if only the patch version changes.
https://github.com/dependabot/fetch-metadata is where this action was taken from.
My approach for handling dependabot pull requests is anyway to merge without looking at the changelog, if it is only a patch version bump.
I think this workflow would require auto-merge to be enabled on this repository. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request
I don't know if we want auto-merge in general. The concept is that a pull request gets merged as soon as there is one approval and CI is green...
=> Add dependabot auto-merge workflow

debug/chinese.html, debug/events.html
Fix a bug in debug/events.html. The unchecked events that uncheck after checking still will be listened because 'map.off' should have 2nd param([listener](https://maplibre.org/maplibre-gl-js-docs/api/map/#map#off ))
=> fix: unchecked event still will be listened in debug/events.html

build/generate-debug-index-file.ts
At the moment, going to http://localhost:9966/test/debug-pages without the trailing slash makes the links to the debug pages broken.
For example, one gets directed to http://localhost:9966/test/shield-rotation.html instead of http://localhost:9966/test/debug-pages/shield-rotation.html.
This pull request introduces absolute paths for the debug pages.
=> Use absolute paths in debug pages index file

src/css/maplibre-gl.css
Remove css duplications.
As mentioned in issue: https://github.com/maplibre/maplibre-gl-js/issues/1378, there are some duplications of keyframes in css when we clean out the prefix.
=> Remove duplicate keyframes in css file

build/generate-style-spec.ts, src/style-spec/feature_filter/convert.ts, src/style-spec/feature_filter/feature_filter.test.ts, src/style-spec/feature_filter/index.ts
See #1380.
Add typing for expressions and fix filter expressions.
improve filter conversion by adding typing and helping typescript to guess types.
add tests for filters mentioned in issue #1380.
no backports.
=> Fix filter typing and add expression type.

src/ui/map.ts
Fixes #1381.
The layer parameter is a LayerSpecification, but may also contain a full SourceSpecification instead of a string (reference).
=> Fix the layer parameter of Map.addLayer

.github/dependabot.yml
Now that jest is up to date, dependabot can manage it again.
=> Remove jest from dependabot

CHANGELOG.md
Apologies, this is a tiny PR to fix language in the CHANGELOG. I called the option `collaborativeGestures` when it's actually `cooperativeGestures` throughout the app.
=> Fixing mistake in name of cooperativeGestures option in the CHANGELOG

build/rollup_plugins.ts, package-lock.json, package.json, rollup.config.style-spec.ts
Replace the rollup plugin for unassert with an improved version that compared to the old one:
* is written in typescript
* has node 18 compatibility
* is 20 times faster due to unassert 2.0.0 rather than 1.6.0
* has updated dependencies
=> Use new unassert plugin

.github/dependabot.yml
To avoid the monthly crunch and be more evergreen, run the dependabot weekly. It's not daily like proposed in #933 , but with more hands coming to the project, much less dependencies than half a year ago and fast ci/cd build checks, I think we can handle this.
=> Dependabot will update packages and github actions weekly

CHANGELOG.md, build/generate-typings.ts, src/source/worker.ts, src/style-spec/reference/latest.ts, src/style-spec/style-spec.ts, src/util/util.ts, tsconfig.json
Fixes #1462 
This PR is to make sure that the type generation fails with this new build configuration.
This should not be merged as is, but rather use this branch to fix the typings.
The problem is that there are two `ExpressionSpecification` defined in the code now, and the type generation fails.
In the past I ignored the problem that it was exposing due to conflict between DOM and WebWroker.
I have now fixed the issues using `@ts-ignore` in the places where web worker types are used.
If you have a better idea how to fix/improve this let me know.
cc: @birkskyum @wipfli
=> Add type check to typescript definition generation

build/generate-typings.ts, src/style-spec/CHANGELOG.md, src/style-spec/expression/index.ts, src/style-spec/expression/parsing_context.ts, src/style-spec/expression/parsing_error.ts, src/style-spec/package.json
See discussion here: #1116
This fixes #1107
Basically this adds typings to the style-spec pacakge.
I don't use it so this need better testing, but I think it's better than nothing...
@achou11 feel free to review this and see if it works as expected.
=> Added typings for style-spec package

test/integration/render/render.test.ts
I was unable to run the render tests on a Windows machine because none of the expected PNG files were being found. It turned out to be due to the backslashes in the path being created to find the PNG files. The backslashes mess up the glob pattern. This change applies the suggested fix by the fast-glob library, to replace '\\' with '/' on Windows.
=> Fix glob path so render tests can run on Windows

.github/workflows/publish-style-spec.yml, src/style-spec/CHANGELOG.md, src/style-spec/package.json
Related to #1107 #1116 #1468
This basically adds the missing step in the publish CI script which I assumed happens automatically but apparently it was a wrong assumption as the only thing that runs in the post install is the code generation that is needed in order to build the package but the type generation is not part of it.
My bad :-(
=> Added missing style-spec typings to publish

CHANGELOG.md, build/rollup_plugins.ts, package.json, src/index.test.ts, src/index.ts, src/ui/map.test.ts, src/ui/map.ts
Extension of #1459  towards resolving issues like this ( #1426)
Provides a way to get the package version, and add unit tests to make sure it's proper semver.
Because of compiler issues at the time this functionality was removed when we moved to typescript in [this PR](https://github.com/maplibre/maplibre-gl-js/pull/209), specifically in [this commit](https://github.com/maplibre/maplibre-gl-js/pull/209/commits/056a39635e8931388873008c23f7536d7ca670ce).
=> Version with test

CHANGELOG.md, package-lock.json, package.json
Adds a getter method to retrieve the package version. We lost this ability in the migration to typescript.
=> Release-2.3.0

.github/workflows/dependabot-auto-merge.yml
Enables automatic approval and merging of pull requests from dependabot if they bump the minor or patch version of a package. Pull requests are only merged after a successful CI run.
=> Automatically merge dependabot semver patch and minor pull requests

.github/dependabot.yml
Every once in a while when the lockfile is way ahead of package.json, we manually go in and update the package.json.
Dependabot can actually update the package.json too so they don't get out of sync, simply by setting the `versioning-strategy: increase`
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> Automatically keep package.json and lock-file in sync

CHANGELOG.md, tsconfig.json
Modern browsers have come a long way, and so have our codebase, and we might as well start leveraging that. [ES2019 is well supported]( https://caniuse.com/sr_es10), and [your browser](https://www.whatismybrowser.com/detect/ecma-script-version) is probably ahead of that, and we were previously blocked from moving towards it because of lacking support by the SWC / Jest setup we had for unit-test.
=> Update target to es2019

build/generate-query-test-fixtures.ts
I found another case where glob.sync was failing, leading to the query tests not working on Windows.
=> In query tests, fixing up the glob sync path so it works on Windows

src/render/program.ts
I'm looking at ways to speedup shader compilation (unrelated to this change) and found this snippet of code in the `draw` function which seemed inefficient.
Some benchmarking showed that the previous primitive size selection (which uses an object, etc.) is about 3x slower in Chromium browsers than a switch statement. It also is apparently a lot slower in Firefox, but I don't know how much credence to give the results I got on Firefox.
It's probably in micro-optimization territory either way, but it's a simple change.
https://www.measurethat.net/Benchmarks/Show/20441/0/if-else-vs-switch-vs-object-2
=> Minor optimization for primitive size selection

CHANGELOG.md, package-lock.json, package.json
Changelog since 2.3.1-pre.1
- Improve expression types ([#1510](https://github.com/maplibre/maplibre-gl-js/pull/1510))
- Improve performance for primitive size selection ([#1508](https://github.com/maplibre/maplibre-gl-js/pull/1508))
- Fix query tests on windows ([#1506](https://github.com/maplibre/maplibre-gl-js/pull/1506))
- Upgrade target from ES2017 to ES2019 ([#1499](https://github.com/maplibre/maplibre-gl-js/pull/1499))
=> Release 2.3.1-pre.2

CHANGELOG.md, src/style/style_layer/symbol_style_layer.ts
Fixes #264 - removes `_interpolationType` which is not used and no set anywhere as far as I can understand...
=> Removes `_interpolationType`

CHANGELOG.md, src/ui/handler/map_event.test.ts, src/ui/handler/map_event.ts, test/unit/lib/simulate_interaction.ts
If something (e.g. rotate or pitch) resets the context menu handler, this is now also taken into account on Windows, where the browser contextmenu event is triggered after mouseup (and not after mousedown).
Fixes #1511.
=> Fix contextmenu on windows: do not trigger after rotate or pitch.

.stylelintrc, CHANGELOG.md, README.md, src/css/maplibre-gl.css, src/ui/anchor.ts, src/ui/control/attribution_control.ts, src/ui/control/fullscreen_control.ts, src/ui/control/geolocate_control.ts, src/ui/control/logo_control.ts, src/ui/control/navigation_control.ts, src/ui/control/scale_control.ts, src/ui/control/terrain_control.ts, src/ui/handler/box_zoom.ts, src/ui/handler/shim/drag_pan.ts, src/ui/handler/shim/touch_zoom_rotate.ts, src/ui/map.ts, src/ui/marker.ts, src/ui/popup.ts
These duplicate classes were introduced to bring improved backward compatibility to the 1.x release. This cleanup reverts that, which was intended to happen with the v2 release where we would start looking forward. See #203, #83
=> Remove duplicate mapboxgl-css classes

.github/workflows/test-unit.yml, package.json
Fixes #1581 - Removes the github action to add coverage and add the coverage report to the console log of the CI machine.
It's far from ideal but at least can be used to some extent...
=> Remove coverage action

package-lock.json, package.json
We don't use the 'request' library anymore, so this removes it. We use fetch instead.
fixes #1584
=> Remove deprecated unused request library

test/build/style-spec.test.ts
Very simple fix.
Currently "test-build" does not pass on windows because regex tests fail for full path string starting with "c:\".
=> Add regex for Windows full path so test-build can pass

.github/workflows/test-unit.yml
Hopefully this should remove annotations from fork PRs so that test-unit will pass.
This is not ideal, but at least it should report some relevant coverage in the PR comment, I hope.
Worst case, we can always remove it :-)
=> Fix Fork PR annotations error

build/generate-query-test-fixtures.ts, package-lock.json, package.json, test/integration/assets/styles/basic-v9.json, test/integration/assets/styles/bright-v9.json, test/integration/lib/localize-urls.ts, test/integration/render/render.test.ts, test/integration/render/tests/basic-v9/z0-narrow-y/style.json, test/integration/render/tests/basic-v9/z0-wide-x/style.json, test/integration/render/tests/basic-v9/z0/style.json, test/integration/render/tests/bright-v9/z0/style.json, test/integration/render/tests/satellite-v9/z0/style.json
- Bump mapbox-gl-styles from 2.0.2 to 2.1.1
Mostly a success, but 5 / 1212 render tests fail. Needs investigation.
=> Remove mapbox-gl-styles dependency

test/bench/gl-stats.html, test/bench/gl-stats.ts
Necessary fixes for opening http://localhost:9966/test/bench/gl-stats.html in the browser or running `npm run gl-stats` to work (its still necessary to edit gl-stats.html and provide your own maptiler api key).
=> Fix gl-stats

CHANGELOG.md, src/style/style.test.ts, src/style/style.ts, src/ui/map.test.ts, src/ui/map.ts, test/debug-pages/transform-style.html
Adds support to generic `transformStyle` convenience style transformer function that allows to modify a style after it is fetched but before it is committed to the map state. 
This allows to support a range of functionalities when incoming style requires modification based on external state or when previous style carries certain 'state' that needs to be carried over to a new style gracefully (without causing unnecessary visual transitions if changes are applied after a style change).
Impact to existing behaviour: **None**
This is a simple alternative to https://github.com/maplibre/maplibre-gl-js/pull/1238.
Map's `setStyle()` and Style's `loadURL()` and `loadJSON()` options now may take an additional transformStyle function, which is exposed with a following signature:
```ts …
```
=> map.setStyle's transformStyle option

src/ui/map.ts
Tiny #1632 follow-up docstring fix for map.setStyle's transformStyle
=> fix transformStyle docstring in map.setStyle

test/bench/benchmarks/expressions.ts, test/bench/benchmarks/filter_evaluate.ts, test/bench/benchmarks/hillshade_load.ts, test/bench/benchmarks/layers.ts, test/bench/benchmarks/layout.ts, test/bench/benchmarks/map_idle.ts, test/bench/benchmarks/map_load.ts, test/bench/benchmarks/paint.ts, test/bench/benchmarks/paint_states.ts, test/bench/benchmarks/placement.ts, test/bench/benchmarks/query_box.ts, test/bench/benchmarks/query_point.ts, test/bench/benchmarks/remove_paint_state.ts, test/bench/benchmarks/style_layer_create.ts, test/bench/benchmarks/style_validate.ts, test/bench/benchmarks/symbol_layout.ts, test/bench/benchmarks/worker_transfer.ts
I refactored most benchmarks to use async await as I consider that style more readable. I can change the remaining benchmarks too for consistency but there the difference is very minor. I'm assuming browser compatibility is less of an issue with the benchmark code.
=> Use async/await for more readable code.

src/geo/transform.test.ts, src/geo/transform.ts, src/render/program/terrain_program.ts, src/render/terrain.test.ts, src/render/terrain.ts, src/shaders/_prelude.vertex.glsl, src/style-spec/reference/v8.json, src/style-spec/validate/validate_terrain.test.ts, src/ui/control/terrain_control.ts, src/ui/map.ts, test/debug-pages/terrain-satellite.html, test/integration/render/tests/terrain/default/style.json, test/integration/style-spec/tests/terrain.input.json, test/integration/style-spec/tests/terrain.output.json
The first two commits just remove the elevation offset.
We have a ~450 elevation offset to move lakes below sea level to places above sea level. It's a workaroud, and it should be removed.
=> Remove elevationOffset and fix below sea-level clipping

README.md
This pull request adds logos and links to the participants of the MapLibre Sponsorship Program, https://maplibre.org/sponsors
Related to https://github.com/maplibre/maplibre/issues/110
=> Add AWS, Meta, MIERUNE to README

README.md
Removes manual links to backers and supporters from README and instead shows automatic avatars of backers and supporters from opencollective.
=> Automatically show opencollective backers and supporters in README

CHANGELOG.md, src/source/geojson_source.test.ts, src/source/source_cache.test.ts, src/source/vector_tile_source.test.ts, src/style/style.test.ts, src/ui/control/geolocate_control.test.ts, src/ui/map.test.ts, src/ui/map.ts, src/ui/map/requestRenderFrame.test.ts, src/util/evented.test.ts, src/util/evented.ts
I've added the ability to get a promise from the `once` method when not sending a listener.
This doesn't break the API but extends it.
I've changed some tests to show the that it is more readable (for me at least).
=> Return a promise from once in case a listener is not provided

test/bench/lib/tile_parser.ts
Fixes #1709 - benchmarks are broken.
I hope as this needs to be merged to main and then see that it creates the relevant file...
=> Fixes missing setTerrain method for benchmarks

CHANGELOG.md, test/bench/run-benchmarks.ts
When working on VM (or various weak hardware), certain headless benchmark tests may fail to execute. Currently the execution just throws null exception and stops the rest. This fix ignores the failed ones and continue.
Cosmetic: one-line lambda and nested tertiary are difficult to set breakpoint and debug, so they are changed to if statements.
=> Fix headless benchmark execution especially on VM

CHANGELOG.md, src/css/maplibre-gl.css
Add a high z-index to the `cooperativeGesture` overlay. 
This make sure that, e.g, popups in a map, always is below the overlay.
CooperativeGestures introduced in #1234
=> Make sure coop-gesture overlay always on top

test/integration/render/custom_layer_implementations.ts
<changelog>
The following 2 tests fail on Windows platform but pass on Linux.
1. test-render custom-layer-js/depth
2. test-render custom-layer-js/null-island
Possibly resulted by a bug/optimization results to WebGL Shaders from headless-gl/Chrome Angle(WebGL simulator for Node.js).
We found a same purpose fix in test-render custom-layer-js/tent-3d, and ported from there.
Have verified that the 2 tests can pass both on Windows 11 and WSL.
</changelog>
=> Fix test fails on Windows 11 platform: "test-render custom-layer-js/depth" and "test-render custom-layer-js/null-island"

CHANGELOG.md, src/ui/control/navigation_control.test.ts, src/ui/control/navigation_control.ts
This fix the #1754. The `NavigationControl` constructor should receive options as optional, this avoid to instantiate the class passing an empty object.
=> Set navigationOptions as optional in NavigationControl

src/source/raster_dem_tile_worker_source.ts, src/util/browser.ts
When setting willReadFrequently to true, it is a hint to the browser that it can decelerate the canvas. This can be beneficial to perf if the canvas is only used for decoding and getting image data in raw pixels. If the canvas was accelerated (i.e. hosting data on the GPU) there could be a lot of latency to get the image data back to the main thread. 
Perf-wise, I was able to isolate this function into a benchmark to show the improvement:
From chromium on a relatively fast machine (~8ms vs ~2ms):
In practice, I'm seeing this improvement is better for slower machines and less noticeable on faster machines.
On Firefox I saw no difference.
Using the hint also removes the source of a warning when using hillshade layer:
=> Use willReadFrequently optimization hint on 2D canvases.

CHANGELOG.md, package-lock.json, package.json
This PR just bumps `rollup-plugin-import-assert` to fix the sourcemaps. Fix was in this PR: https://github.com/calebdwilliams/rollup-plugin-import-assert/pull/8
Fixes #1582
Note: the release that includes the change doesn't include in the built distribution, so keeping it in draft until that's fixed. Context here: https://github.com/calebdwilliams/rollup-plugin-import-assert/pull/8#issuecomment-1292847070
=> bump rollup-plugin-import-assert to fix sourcemaps

src/ui/handler/mouse.ts
Rename buttonStillPressed in the mouse handling module to buttonNoLongerPressed as this is what it is checking. This function is only used in this context and should have no impact beyond code legibility.
Split from https://github.com/maplibre/maplibre-gl-js/pull/1852 based on instructions by @HarelM.
=> Rename buttonStillPressed to better reflect what it does

package.json, test/README.md
While I was refactoring some code I was looking for a script to watch specific subfolders while developing to make the test runs fast enough to aid in test driven development. Since I could not find an implemented script - I added one myself, and thought others may find this useful too.
=> Add a script to watch run tests in watch mode for a specific folder

src/util/web_worker_transfer.ts
The following typescript error is no longer reported when running `npm
run typecheck`
src/util/web_worker_transfer.ts:114:9 - error TS2322: Type 'unknown' is
not assignable to type 'Serialized'.
114         return input;
=> Resolve typescript error

.github/workflows/analyze.yml, .github/workflows/release.yml
Resolves [some workflow warnings](https://github.com/maplibre/maplibre-gl-js/actions/runs/3638991800)
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> use new Github Action output hook

CHANGELOG.md, package-lock.json, package.json, test/bench/data/style-benchmark-locations.json, test/bench/styles/benchmarks.ts, test/bench/versions/benchmarks.ts
Removes dependency on gazetteer, which was only being used for a single GeoJSON file for benchmarks but pulled in a number of deprecated packages.
Fix #1897
=> Remove dependency on gazetteer

.eslintrc, .vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md
Add project-specific VSCode settings to use correct formatting standards.
=> Default VSCode to use current code formatters

CHANGELOG.md, src/ui/map.ts
Following [quertRenderedFeatures is not typed well #1900](https://github.com/maplibre/maplibre-gl-js/issues/1900), a type definition added to the options param.
To be consist with the type way the param is typed in `queryRenderedFeatures` function in `query_features.ts` I added an inline definition instead of creating a typescript type.
=> better type for the options param in quertRenderedFeatures

CONTRIBUTING.md, docs/RELEASE-PROCESS.md
1. Redirect semver help to npm's page, not yarn's.
2. Link to changelog guidelines
3. Add recommendation to use the new `npm version`, which also updates the lockfile.
https://github.com/maplibre/maplibre-gl-js/pull/1916#issuecomment-1348503903
=> Update Changelog and Release processes

jest.config.builds.ts, jest.config.e2e.ts, jest.config.ts
Fix complaint from jest due to the way ts-jnode interacts with jest ts runner.
see https://github.com/maplibre/maplibre-gl-js/pull/1966#issuecomment-1362079702
=> fix warning for running jest tests

package-lock.json, package.json
Fix upstream build issue so now things install cleanly on Mac + Node 19
=> Bump gl package

test/bench/versions/index.html
The benchmarks use url-search-params via unpkg to parse arguments. This is unnecessary, since the URL API natively supports this.
=> replace url-search-params with URL

CHANGELOG.md, src/source/geojson_source.test.ts, src/source/geojson_source.ts
- I Confirm that **my changes do not include backports from Mapbox projects** (unless with compliant license) 
- fix issue #1384 and #429 
-  enable users to change cluster properties on the source by adding setClusterOptions in [src/source/geojson-source.ts](https://github.com/maplibre/maplibre-gl-js/blob/v2.4.0/src/source/geojson_source.ts#L68-L346)
- `setClusterOptions(cluster: boolean, clusterRadius?: number; clusterMaxZoom?: number})`  The value of the clusters properties.
Exemple:
```js
map.addSource('earthquakes', {
type: 'geojson',
data:
'https://maplibre.org/maplibre-gl-js-docs/assets/earthquakes.geojson',
cluster: true,
});
///////////////
map.getSource('earthquakes').setClusterOptions(cluster:false);
map.getSource('earthquakes').setClusterOptions(clust: true, clusterRadius: 80, …
```
=> change the cluster properties on the sources option

CHANGELOG.md, test/integration/expression/expression.test.ts
While testing another PR, I was struggling to figure out why my test case was failing. This PR adds additional logging of test case failures, in order that the author of a failing test can see what's wrong. The extra logging occurs only in the event of a test failure.
=> Add logging for test case failures

test/build/min.test.ts
Previous check was +-5% of 750KB, this means each PR was allowed to change size up to 37KB minified!!!
Based on our data of millions of users, 1k size increasement usually means +1ms of load time, and each change needs to be justified.
Should not use percentage because the net byte change will get bigger and bigger.
Changes:
- Allow up to 1K increasement per PR. Or it needs manual attention. Practically, 1K minified usually means ~4k of debug scripts, and that is already a lot of code for one PR.
- Allow up to 4K reduction. This is just to catch bugs that may have dropped things unintentionally.
=> Adjust build min test to be more frugal

CHANGELOG.md, src/source/terrain_source_cache.test.ts, src/style/style.test.ts, src/style/style.ts, src/ui/map.test.ts, src/ui/map.ts, src/util/dispatcher.test.ts, src/util/dispatcher.ts
- On style change (map.setStyle), currently the existing style object is removed and recreated. When style object is removed ( style._remove(), worker is also getting terminated (unless there are other multiple map instances)  and a new worker is created each time which is a very expensive operation.
- Code flow: map.setStyle(<new Style>)--> map._updateStyle(...) --> map.style._remove() --> map.style.dispatcher.remove() --> map.style.dispatcher.workerPool.release() causing the worker to be terminated, if there is no other active map.
Fix is simply to not terminate the worker till map is been removed. When map is removed, then map.setStyle(null) is called. When this happen's we pass the intend and terminate the worker.
=> Fix: worker been terminated on setting new style

CHANGELOG.md, src/style-spec/diff.test.ts, src/style/style.ts
The recent addition of setSprite is great! However, I noticed this small issue when using `map.setStyle(..., {diff:true})` / `map.style.setState()` to unload sprites. `style._loadSprite()` properly checks if `completion` exists, but `style.setSprite()` invokes it blindly. This PR checks that `completion` exists / is not undefined before calling it.
Not sure if this needs to be mentioned in the changelog.
=> Fix invocation of callback in map.style.setSprite() that may be undefined

src/index.ts, src/util/config.ts, src/util/web_worker.ts
Long circular depedency:
<code>src/index.ts -> src/ui/map.ts -> src/style/style.ts -> src/util/global_worker_pool.ts -> src/util/worker_pool.ts -> src/util/web_worker.ts -> src/index.ts</code>
It looks very reasonable to move workerURL to config object instead of piggyback on main maplibre.
=> Break circular dep: index.ts ... web_worker.ts -> src/index.ts

src/geo/transform.test.ts, src/geo/transform.ts
wrap `lnglat` point so `fitBounds` across anti-meridian no longer throws error
=> fix fitBounds crossing AM with 3d - add wrap for lng in transform getElevation 

.github/ISSUE_TEMPLATE/Feature_request.md
As a **developer** I want to **provide useful information to the maintainer team** in order that I **clearly describe the reason for desired code changes**.
In https://github.com/maplibre/maplibre-gl-js/issues/2162#issuecomment-1426745555, it was described that there's an undocumented expectation for issue authors to provide a [user story](https://en.wikipedia.org/wiki/User_story) which succinctly describes the purpose of the requested change. This PR formally adds that expectation explicitly in the issue template.  This will assist authors of new feature tickets in better communicating what they are trying to accomplish.
Sorry for going straight to PR but I felt this was a simple enough change.
=> Update new feature template to add user story requirement

CHANGELOG.md, src/ui/map.test.ts, src/ui/map.ts
Fixes #2162 
This PR adds `Map.getImage()`, which completes the CRUD methods for image access, along with `Map.addImage()`, `Map.updateImage()`, and `Map.removeImage()`.
=> Add Map.getImage()

CHANGELOG.md, package-lock.json, package.json, src/geo/lng_lat.test.ts, src/geo/lng_lat.ts, src/geo/lng_lat_bounds.test.ts, src/geo/lng_lat_bounds.ts, src/ui/control/geolocate_control.test.ts, src/ui/control/geolocate_control.ts
- Add types to LngLatBounds constructor.
- remove toBounds
- Create a static method called fromLngLat(lnglat, radius).
- Fail build on all warnings to stop all future circular dependency problems
=> Migrate toBounds method to be a static fromLngLat method in LngLatBounds

CHANGELOG.md
Doc change: add more information about the resizing API change. Original PR was pretty big and not easy to dig up the details.
=> Doc: add more details about resize API change

src/style-spec/CHANGELOG.md
When https://github.com/maplibre/maplibre-gl-js/pull/1805 was merged, the version in style-spec package.json was bumped from 17.0.2 to 17.1.0, but the changelog was never updated, and the 17.1.0 version was never released.
=> Update changelog for style-spec

CONTRIBUTING.md
This PR updates the contributor's guide with recommendations interacting with the team, based on [Slack discussions](https://osmus.slack.com/archives/C01G3D28DAB/p1676846211248879).
=> Add helpful guideline for contributors

CHANGELOG.md, src/ui/events.ts
Currently, `MapLayerMouseEvent` and `MapLayerTouchEvent` are typed with their `features` property as `GeoJSON.Feature[]`. However, the features returned on either of these events are `MapGeoJSONFeature`s; they contain the additional properties of that interface (e.g., `layer`, `source`, `sourceLayer`, and `state`). In addition, it appears the unit tests already cast features returned on `MapLayerMouseEvent`s to `MapGeoJSONFeature[]`; see [here](https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/map_events.test.ts#L117-L118) for an example. This PR just corrects the types!
Looking through the CHANGELOG, it appears `MapGeoJSONFeature` is a fairly new addition (2.1.8-pre.2), so I think this may just be on spot where the types got missed!
- While these types are part of the …
=> Ensure features property is typed as MapGeoJSONFeature[] on MapLayerMouseEvent and MapLayerTouchEvent.

CHANGELOG.md, src/ui/events.ts, src/ui/map_events.test.ts
Currently, the default type for originalEvent on a MapLibreEvent is "undefined." This can lead to type errors when handling some events unless the type for originalEvent is specified on the handler, even when we may not care about the type of orginalEvent at all. For example, let's say I want to handle a zoom event. If I define an event handler like this:
onZoom(event: MapLibreEvent) {}
I will get a type error if I try to subscribe to a zoom event using that callback, because that event is typed as `MapLibreEvent<MouseEvent | TouchEvent | WheelEvent | undefined>`. The TypeScript compiler complains about the three non-undefined event types being unassignable to undefined.
Moreover, the type "unknown" is more correct here anyway, as the base case is not knowing what the type is. In the case …
=> Change default original event type from undefined to unknown

.github/workflows/test-all.yml
PR #2044 removed the unit test coverage reports. This PR reinstates them and uploads the coverage reports as build artifacts.
Per https://github.com/maplibre/maplibre-gl-js/pull/2044#issuecomment-1468107043
=> Reinstate CI unit test coverage

CHANGELOG.md, src/ui/camera.test.ts, src/ui/camera.ts
=> Add queryTerrainElevation

src/ui/map.test.ts, src/ui/map.ts
Fix ~50ms regression introduced by PR #2097 
- When previous set of requests are sent and not finished, image queue appears dirty so _render kicks of another frame and archives nothing. In fact, _imageQueueDirty flag is not needed because when images are received, other code (usually raster tile) will trigger rendering.
- When not throttled, calling processQueue does nothing but wasting time
Therefore, remove this._imageQueueDirty field and only call process queue when throttled (which means moving)
=> Fix perf regression introduced by PR 2097

CHANGELOG.md, src/render/draw_debug.ts, src/render/painter.ts
This removes **one** of the deprecation warnings from https://github.com/maplibre/maplibre-gl-js/issues/2030, by getting rid of the painter's `emptyTexture`.
`emptyTexture` is used literally nowhere else than on `render_debug`, and the debug tiles draw just fine without it.
=> Remove emptyTexture from painter

src/style/style.test.ts
Upgraded to nodejs 19 and all style tests failed.
Somehow node 19 does not allow to modify "global.self", although I cannot find any release notes about it.
Nevertheless, looks like Style.ts has also evolved and all UTs are passing without this mock anyway
=> fix style test UT on nodejs 19

src/symbol/placement.ts
placeSymbol is a very hot code path if not the hottest. For most screen sizes, this function is called 1000 to 2000 times. 
When terrain does not exist, it is still doing a loop on 4-element array ['textBox', 'verticalTextBox', 'iconBox', 'verticalIconBox'] which means 4000 to 8000 extra loops.
Please review --- before my change, textBox had elevation of 0, and now it would be undefined. 
However, I cannot find anywhere the elevation of textBox is used for placement or collision. The previous code was added in #1022, @HarelM  @prozessor13, can you share more insights regarding where and how it is used?
There is no UT coverage either.
=> avoid extra loops when terrain does not exist

.github/workflows/dependabot-auto-merge.yml
Enable auto merge to dependent bot if CI passes.
Heavily relies on https://rednafi.github.io/reflections/automerge-dependabot-prs-on-github.html
I've been spending a lot of time simply clicking approve on dependant bot PRs.
I hope this will reduce the time I need to spend on this.
@birkskyum @zhangyiatmicrosoft
=> Allow auto merge to Dependabot PR if they pass CI

.eslintrc
Enforces separation of maplibre and style spec by preventing cross-package imports.
No longer as much of an issue since #2198 migrated the style spec to a different repo.
fixes https://github.com/maplibre/maplibre-gl-js/issues/2054
=> Prevent cross-package imports

CHANGELOG.md, src/ui/control/geolocate_control.test.ts, src/ui/control/geolocate_control.ts
Closes #2387
- Add a unit test for the bug
- Check if control is still mounted before setting up UI
=> (fix) GeolocateControl error if removed quickly

CHANGELOG.md, src/source/rtl_text_plugin.ts, src/style/style.test.ts, src/style/style.ts
Fixes #2380
When a deferred load of the RTL text plugin completes, there's logic that causes the source caches to reload:
https://github.com/maplibre/maplibre-gl-js/blob/9f713cd2299a567e4f2a8000d984cd3f4ca14a19/src/style/style.ts#L226-L238
The purpose of this logic is to cause them to regenerate their symbol buckets with the new RTL shaping applied. If the plugin loads before the initial tile load, this will be a no-op, but if some tiles have already loaded it will reparse them. This is some extra work and the tile cache is cleared out, but the old tiles can still display until the new tiles are ready.
This logic is unnecessary for raster sources, since they don't have any symbols to regenerate. Also, raster tiles tend to load faster (because no parsing/bucket-generation is necessary), …
=> Don't reload raster sources when RTL text plugin loads to avoid flicker.

test/bench/README.md, test/bench/run-benchmarks.ts
This changes are necessary as index.html is no longer used for directories.
=> adapt links to a7e74509b1116207020626bf9942eac2563a7548

test/bench/README.md, test/bench/lib/tile_parser.ts, test/bench/versions/index.html
I forgot to add the link changes of the first commit to #2412. Sorry about the confusion.
The second commit brings back the possibility to run the benchmarks without comparing to any releases. As the feature was somewhat obscure but useful especially to develop on the benchmarks itself, I added a short documentation to the README.
=> Small benchmark fixes

CHANGELOG.md, src/geo/lng_lat_bounds.test.ts, src/geo/lng_lat_bounds.ts
This PR fixes `LngLatBounds.extend()` to handle `{ lng: number, lat: number }` and `{ lon: number, lat: number }` coordinates.
Fixes #2424.
=> Fix `LngLatBounds.extend()` to Handle Object Coordinates

src/index.ts
This is related to the change in #2198.
See my comments here:
https://github.com/maplibre/maplibre-gl-js/pull/2198#issuecomment-1516670246
It basically re-exports all the typescript typings of the style-spec package so that there won't be a need to reference the style-spec package when importing its types.
cc: @birkskyum
=> Export style-spec typings

CHANGELOG.md, package-lock.json, src/ui/control/geolocate_control.test.ts, src/ui/control/geolocate_control.ts
Fixes #2449 
Accuracy-circle was going places, chaning size randomly, seams to be fixed with this.
Replace _updateCircleRadius in geolocate_control.ts because the calculation was wrong. Code fix heavily inspired from stackoverflow. 
The old "circleDiameter" calculations
=> Accuracy-circle in geolocate fix

CHANGELOG.md, src/util/image_request.ts
fetchPriority is experimental property supported on Chromium browsers from Version 102. By default images are downloaded with priority low, whereas fetch request downloads with priority high. 
Documentation:  https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchPriority
Browser usage: https://caniuse.com/?search=fetchpriority
Our internal A/B testing shows slight (0.5%) page load time improvement in raster tiles heavy scenarios when used with refreshExpiredTiles=false which triggers use of HtmlImageElement instead of fetch to download raster images.
=> Set fetchPriority for HTMLImageElement to help improve raster heavy scenarios

CHANGELOG.md, src/ui/map.test.ts, src/ui/map.ts, src/ui/map/requestRenderFrame.test.ts
There is no reason to fire a render before map style is loaded. This change reduces number of render event fired on initial load.
Loading a Maptiler style invokes render 7 times, 1 before the style loaded and 6 after style loaded. After this change it saves the first render pass which is not required as there is nothing to render.
=> Reduce rendering calls on initial load

.github/workflows/test-all.yml
Close #2482, #2411
This splits up integration, unit, render and build tests. 
In this PR all these tests completed in 7m 57s, which is significantly shorter than a typical ~16 min run.
If i.e. a render test breaks, it only has the potential to cancel the other render test, but not the integration/unit/build tests which will keep running.
=> Parallelize test workflow (splitting up jobs)

README.md
Link in the README was still pointing to docs/ making it a broken link after  #2353
=> Fix broken docs link in README

test/integration/query/query.test.ts, test/integration/render/tests/zoomed-raster/underzoom/style.json
This fixes the CI tests in the main branch.
**Query test:**
On windows, the query test server / browser start isn't able to complete within the 5s timeout. This PR increases it to 30 sec to make sure the tests will run.
Example here: https://github.com/maplibre/maplibre-gl-js/actions/runs/4925448119/jobs/8820183726
**Render test:**
Also, extends the zoomed-raster\underzoom render test timeout, because it's flaky on the slower windows runners.
=> Increase test timeouts, to accommodate for windows runners 

src/gl/context.ts, src/gl/webgl2.ts, src/render/painter.ts, src/ui/map.ts, test/integration/query/query.test.ts
Continuation of #1891 
Adding more typings for WebGL2RenderingContext.
Also, unused field variable on Painter `emptyTexture: Texture;` is removed.
=> Cleanup WebGL2 typings

CHANGELOG.md, src/ui/map.ts, src/util/test/util.ts
This PR removes webgl1 from the distributions, but allow our coverage/unit tests to continue using a nodejs webgl1 mock for now.
=> Sunset webgl1

src/gl/types.ts, src/render/program.ts, src/render/texture.ts
part of #2515 
instead of
```ts
WebGLRenderingContext['LINES']
```
use 
```ts
typeof WebGL2RenderingContext.LINES
```
this is non-breaking, as the values come from the shared interface of  WebGLRenderingContext and WebGL2RenderingContext, known as WebGLRenderingContextBase.
=> Use WebGL2 constants in a typesafe way

test/bench/benchmarks/customlayer.ts, test/integration/render/run_render_tests.ts
Part of #2515 
This updates types in the render test code / benchmark.
=> Update webgl typing in render test / benchmark

src/gl/context.ts
Part of #2515 
This removes loading of some webgl1 extensions, as they are bundled with webgl2.
=> Remove webgl1-only extensions

src/gl/vertex_buffer.ts, src/render/uniform_binding.ts
Part of #2515 
Updates:
- uniform_binding
- vertex_buffer
=> Update WebGL types in vertex buffer and uniform binding

CHANGELOG.md
I think it makes sense to separate DX improvements from the features/improvements section, because it's not so relevant if you're a consumer of this library, whereas it can be quite informative for contributors to know if there has been changes to the stack / reorganizations / refactors / benchmarks / other changes to tests.
=> Remove DX items from changelog

test/integration/README.md, test/integration/render/run_render_tests.ts
- Render tests are generating a lot of messages and when running >1200 of them together it is difficult to find the failed ones, so hide them by default add a <code>--debug</code> switch to turn on as needed.
- Puppeteer tests takes ~10 min to run them all, so generate reports by default for easy troubleshooting. This can be skipped by <code>--skip-report</code>
- Clean up and cosmetic changes: make a main "executeRenderTests" function as entry point to improve readability.
- Update readme.md with instructions
=> Generate report by default and hide debug messages in render tests.

CHANGELOG.md, src/ui/map.test.ts, src/ui/map.ts, test/integration/browser/browser.test.ts
Closes #2551 
Captures the initial resize event from the resize observer, so it's more similar to the previous implementation that didn't fire on setup.
Adds the browser test that checks that the 'load' event comes before 'resize' and 'moveend'
=> Capture initial resize event

package.json
Parallelize the codegen task, to save time for all CI's
In windows, the npm ci sometimes takes > 3 min, where it's almost always <1 min. on ubuntu.
=> Parallelize code generation and run it before builds

package-lock.json, package.json
This is to include the CSS4 color parser, and allow decimal numbers in rgb() etc.. See https://github.com/maplibre/maplibre-style-spec/pull/175
=> Bump style spec from 19.1.0 to 19.2.0

.github/workflows/release.yml
If release exist, skip. 
Also closes #2582 
For reference, there is also another flag called [allowUpdates ](https://github.com/ncipollo/release-action) that would have allowed the CI to continue
=> Skip release if exist

CHANGELOG.md, src/util/request_manager.ts
RequestTransformFunction is typed incorrectly. RequestTransformFunction can return RequestParameters or undefined. Documentation even provides an example where RequestTransformFunction returns RequestParameters or undefined.
=> fix RequestTransformFunction type

test/integration/render/run_render_tests.ts
I've generalized the split code and added a retry for failing tests.
Let's hope this will improve the situation for the render tests...
=> Add retry to render tests

src/index.ts
Since supported was still in the index.ts docs, the Maplibre 3.0 [documentation](https://maplibre.org/maplibre-gl-js-docs/api/properties/#supported) still includes it although it's not exported anymore. 
This PR removes that doc comment. We'll need to regenerate the docs when this is merged in.
Also, not sure if this needs a changelog entry?
=> Remove `supported` from index.ts

CHANGELOG.md, src/gl/context.ts
Fixes https://github.com/maplibre/maplibre-gl-js/issues/2590 
Adds the `gl.getExtension('EXT_color_buffer_float');` to support [all these types](https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float).
=> Load float webgl2 extension to support i.e. RGBA16F

src/render/program.ts, src/shaders/background_pattern.fragment.glsl, src/shaders/background_pattern.vertex.glsl, src/shaders/shaders.ts
This code contains the port of 1 shader pair, the **background-pattern** to GLSL 3.0, to prove the feasibility of a migration. When going through the rest of the shaders, there will likely surface more adjustments.
Closes #2576
=> migrate background-pattern to glsl 3

package-lock.json, package.json
Bring in latest changes from [maplibre-style-spec](https://github.com/maplibre/maplibre-style-spec) repo.  
Specifically: Skip running color match regex for hex color or rgb, if not required https://github.com/maplibre/maplibre-style-spec/pull/186
=> Bump Style-spec from 19.2.0 to 19.2.1

src/ui/events.ts
I spent at least a few minutes puzzling through the fact that `dblclick` handlers don't magically suppress `click` events. It makes sense in hindsight, but I want to try and save the next person a little bit of time. See https://osmus.slack.com/archives/C01G3D28DAB/p1685016451984109 for some discussion.
=> Document that dblclick is preceded by click events

.github/workflows/test-all.yml, build/readme.md, package.json, src/gl/value.ts, tsconfig.dist.json
Fixes #2588.
This adds a tsconfig file that is specific to the `d.ts` file in the dist folder in order to make sure that the generated file is following the strict mode.
=> Add strict typecheck to generated d.ts file

package-lock.json, package.json
Typescript package scripts should no longer crash with an error on Node 20.
Node 20 changed how loaders work which broke `ts-node`.
https://github.com/TypeStrong/ts-node/issues/1997
e.g. running `npm run generate-shaders` would fail with an error like below:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ...\maplibre-gl-js\build\generate-shaders.ts
at new NodeError (node:internal/errors:399:5)
at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
at defaultGetFormat (node:internal/modules/esm/get_format:139:38)
at defaultLoad (node:internal/modules/esm/load:83:20)
at nextLoad (node:internal/modules/esm/hooks:735:28)
at load (C:\Users\dan\Source\maplibre-gl-js\node_modules\ts-node\dist\child\child-loader.js:19:122)
at …
```
=> fix package scripts on node v20

CHANGELOG.md, README.md, src/source/vector_tile_source.test.ts, test/integration/browser/README.md, test/unit/assets/source.json, test/unit/lib/web_worker_mock.ts
There were a few minor instances of MapLibre spelled as Maplibre.
=> Fix MapLibre name convention outliers

src/gl/context.ts
Remove this webgl extension which was added as a part of #2656 .
It didn't exist before WebGL2 was introduced (https://github.com/maplibre/maplibre-gl-js/pull/1891/files), and it still isn't needed.
Fixes #2678
=> remove EXT_sRGB

src/source/canvas_source.ts, src/source/geojson_source.ts, src/source/image_source.test.ts, src/source/image_source.ts, src/source/source.ts, src/source/vector_tile_source.ts, src/source/video_source.ts, src/style/style.test.ts, src/style/style.ts, src/ui/camera.ts, src/ui/control/attribution_control.ts, src/ui/control/geolocate_control.ts, src/ui/control/logo_control.ts, src/ui/control/navigation_control.ts, src/ui/control/scale_control.ts, src/ui/control/terrain_control.ts, src/ui/handler/scroll_zoom.ts, src/ui/handler_manager.ts, src/ui/hash.ts, src/ui/map.ts, src/ui/marker.ts, src/ui/popup.ts, src/util/actor.test.ts, src/util/actor.ts, src/util/util.test.ts, src/util/util.ts
Superficial refactoring to remove bindall and introduce the typescript `() =>` way of doing things in modern code.
=> Removed `bindall`, added some types, changed source.ts factory

CHANGELOG.md, src/style/style.test.ts, src/style/style.ts, src/ui/map.test.ts
This PR fixes issue #2692.
One of the things that I think is a bit tricky about MapLibre is knowing how to interact with it when it's in an intermediate/loading state (thus the standard pattern in examples where your logic all lives in a `map.on('load', ...` block). I don't really have a clear idea of how to improve that situation, although I have the vague impression that moving to a promise-based interface could be helpful.
Given the current setup though, there's basically two types of things that are supposed to happen when you call a method that depends on something that still needs to be loaded:
- You get a specific "not loaded yet" error, e.g. `throw new Error('Style is not done loading.');`, or
- You get some version of an "empty" result
I don't know a hard/fast rule for how to …
=> Make Style.serialize() return undefined instead of throwing if style hasn't loaded yet.

CHANGELOG.md, src/symbol/check_max_angle.test.ts, src/symbol/check_max_angle.ts
This fixes issue #2654. As documented in the issue, a zero-length label would _almost_ always return true in the check max angle check (and of course it should, since it's impossible for there to be a bend), but would throw an exception if the anchor happened to be on the last segment of the line. The unit test introduced with this PR would fail on the exception without the matching code change. The impact of throwing the exception is to entirely prevent tiles from loading.
cc @ibesora
=> Make checkMaxAngle return "true" for empty labels, to avoid potentially indexing off end of line

CHANGELOG.md, src/ui/map.test.ts, src/ui/map.ts
Since typescript migration (#294) the pixel ratio is fixed, but this isn't desirable. The device pixel ratio may change after map load, for example when zooming in or out the viewport
=> Make pixel ratio dynamic again

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts, src/ui/popup.ts
Add `className` option to Marker,  also add `addClassName`, `removeClassName` and `toggleClassName` methods to be more consistent with the Popup.
Made similar PR to `mapbox-gl-js` https://github.com/mapbox/mapbox-gl-js/pull/12770 and `react-map-gl` https://github.com/visgl/react-map-gl/pull/2213 to keep the same APIs between libraries.
=> Add className option to Marker

.github/workflows/auto-merge-dependapot.yml
This is in continue to #2345.
cc @stepankuzmin, @IvanSanchez @wipfli @zhangyiatmicrosoft @birkskyum 
I've also configured the branch protection in the setting of this repo so that all the CI are now required, I hope this is what caused the issue in the original PR.
If this won't work I'll change to use renovate, these PR merges are taking a lot of time...
The following is the configuration on main's branch protection:
=> Automerge dependabot

docs/plugins.md
This is a documentation change. It adds [terra-draw](https;//www.github.com/JamesLMilner), a library for drawing with MapLibre GL JS to the list of available plugins.
=> Add Terra Draw as available plugin

CHANGELOG.md, src/render/painter.ts, src/render/render_to_texture.ts, src/ui/camera.ts, src/ui/control/navigation_control.ts, src/ui/hash.ts, src/ui/map.ts, src/ui/marker.test.ts, src/ui/marker.ts, src/ui/popup.ts, src/util/evented.ts, src/util/performance.ts, typedoc.json
Migrated Popup and Marker and changed the Map group to "Main":
It seems that setting the `## Events` section below the examples helps with the grouping for some reason...
=> Migrated popup and marker

.github/workflows/release.yml, .github/workflows/test-all.yml, docs/README.md, mkdocs.yml, src/index.ts, src/source/rtl_text_plugin.ts, src/ui/control/attribution_control.ts, src/ui/control/fullscreen_control.ts, src/ui/control/geolocate_control.ts, src/ui/control/logo_control.ts, src/ui/control/navigation_control.ts, src/ui/control/scale_control.ts, src/ui/control/terrain_control.ts, src/ui/events.ts, src/ui/hash.ts, src/ui/map.ts, src/ui/marker.ts, src/ui/popup.ts, src/util/ajax.ts, src/util/config.ts, test/examples/add-image-animated.html, test/examples/custom-style-layer.html, typedoc.json
I've aligned the group to the original doc's structure and fixed the linked in the main readme.
I also changed the main exported const to be a static class - this is mainly so it would show up in the docs with all the relevant information - I'm not super excited about this change so I'll need a second opinion here.
Added also the build to the CI, although I'm not sure what it actually checks...
=> Main docs readme links fixes

CHANGELOG.md, package-lock.json, package.json
This is a pre-release since I would also like to see how the changes that were introduced to the main maplibre object affect libraries that use this lib.
And I also want to see that the docs publication works as expected.
=> Bump version to 3.2.0-pre.1

.gitignore, build/generate-docs.ts
It seems quite straightforward in cloudflare to forwarding all existing examples to the new route.
https://maplibre.org/maplibre-gl-js-docs/example/ -> https://maplibre.org/maplibre-gl-js/docs/examples/
Alternatively, if a direct forward of everything from old to new docs page is setup, this could also be fixed with a redirect:
https://maplibre.org/maplibre-gl-js/docs/example/ -> https://maplibre.org/maplibre-gl-js/docs/examples/
=> Move docs examples to examples folder

README.md, build/generate-docs.ts, docs/README.md
move links to assets to `/docs/assets/`
=> Fix docs links to examples folder

README.md, docs/README.md
Images in readme now point to where they are in the new docs site.
=> Fix image links in readme

.github/workflows/release.yml, CHANGELOG.md, package-lock.json, package.json
Release version 3.2.
I believe I fixes most of the docs issues.
I'm fairly pleased with it.
I've added a condition to the release.yml to avoid publishing the docs when publishing a pre-release.
=> Bump version to 3.2.0

CHANGELOG.md, test/examples/check-for-support.html
Closes #2822 
As `supported` was removed, I checked browser support by creating a canvas with webgl and weggl2. If there are some errors, then the browser does not support webgl
#2822 
<changelog>Updated `check-for-support` example ([#2859](https://github.com/maplibre/maplibre-gl-js/pull/2859))</changelog>.
=> feat: update supported example

CHANGELOG.md, test/examples/cooperated-gestures.html
Closes #2819 
Added `cooperated gestures` example
#2819
=> feat: add cooperated gestures example

CHANGELOG.md, src/ui/map.test.ts, src/ui/map.ts
At the moment the cooperative gesture screen text is read my screenreaders such as VoiceOver on iOS. But screenreader users are not able to use the gestures (Using two fingers or Ctrl + scroll ect.) to interact with the map. Therefore this text doesn't make sense for them.
This element should be hidden from the accessibility tree using `aria-hidden="true"` which results in screenreaders not reading the text to the user.
=> Remove cooperative gesture screen from accessibility tree

src/ui/camera.ts, src/ui/map.ts
This improves the Map/Camera class documentation in the following ways:
- Private functions and properties are suppressed from the output
- Event annotations are constrained only to event listeners, and lists of events are added to each method that fires events.
- Some events were added to the Camera class where they seemed to be missing/wrong/copy-paste-errored, for example, adding pitch and rotate to functions that pitch and rotate the map.
If the table takes up too much white space to list the Camera class events, it can be changed to a simple, more compact list.
Related to #2861, however, this changes documentation only and does not fire warnings.
=> Improve documentation on Map and Camera classes

src/render/draw_fill.test.ts, src/render/draw_symbol.test.ts, src/render/painter.ts, src/render/program.ts
The 'name' parameter in the `Program` class is unused. This PR removes this parameter from the constructor and from all invocations.
=> Remove unused 'name' parameter from class Program

CHANGELOG.md, src/source/vector_tile_worker_source.test.ts, src/source/vector_tile_worker_source.ts, src/source/worker_tile.test.ts, src/source/worker_tile.ts
As pointed out in https://github.com/maplibre/maplibre-gl-js/pull/1805#issuecomment-1315978349, the issue occurred where after adding a geojson source, a bunch of symbol layers and new spritesheets in a `load` callback, the sprites would be not shown for geojson's source tiles already loaded (which are loaded before the sprites are loaded), as a result of tiles not being reparsed:
https://github.com/maplibre/maplibre-gl-js/blob/870c2a38550a363ca62833a2f401f599d2720f97/src/source/worker_tile.ts#L64
not getting called inside the web-worker and so the https://github.com/maplibre/maplibre-gl-js/blob/870c2a38550a363ca62833a2f401f599d2720f97/src/source/worker_tile.ts#L169 would not fire to grab the new loaded image assets. 
This issue would not happen if browser have cached sprite assets, …
=> VectorTileWorkerSource: change reloadTile behavior to reload right away instead of waiting for previous parse to complete

CHANGELOG.md, src/source/raster_dem_tile_source.test.ts, src/source/raster_dem_tile_source.ts, src/source/raster_tile_source.test.ts
Closes https://github.com/maplibre/maplibre-gl-js/issues/2889.
While investigating the issue, I determined that not only are undefined properties included when serializing, but not all relevant properties are included either (e.g. minzoom and maxzoom). However, I can see no reason to not just use the base class [RasterTileSource's serialize() function](https://github.com/maplibre/maplibre-gl-js/blob/8c351c401b72e69bb3d5156a6101d281d18f44cb/src/source/raster_tile_source.ts#L127) directly. So, I've removed the function from RasterDEMTileSource, and added a test for both RasterTileSource and RasterDEMTileSource.
=> Fix Raster DEM source serialization

CHANGELOG.md, src/source/vector_tile_worker_source.test.ts, src/source/vector_tile_worker_source.ts
Fixes #2923.
An unfortunate regression has been introduced in #1874, where when `reloadTile`  would get called before the original load completes, the `rawTileData` won't get passed to the main thread, leading to #2923. The base `loadTile` will extend the parse result with previously fetched data at https://github.com/maplibre/maplibre-gl-js/blob/01e5f51cf15421cb40ad0ff4798f8f536f816a0c/src/source/vector_tile_worker_source.ts#L130
This PR will keep the original fetching state until the first parse completes and will pass it along as expected.
=> VectorTileWorkerSource: fix reload for original's load parse would not pass the rawTileData and meta

test/examples/check-for-support.html
Closes [#2912](https://github.com/maplibre/maplibre-gl-js/issues/2912).
Update existing check-for-support example with comment about failIfMajorPerformanceCaveat.
=> Update check-for-support example to document failIfMajorPerformanceCaveat

CHANGELOG.md, package-lock.json, package.json
Version bump to release text-variable-anchor-offset changes (#2914). Implementation of new style property is significant enough for a bump to 3.3.0 instead of 3.2.3?
=> Version bump to 3.3.0: text-variable-anchor-offset

CHANGELOG.md, src/style/style.ts, src/ui/map.ts
Fixes #2968
This PR changes the return types of:
* `Map.getLayer()` from returning `StyleLayer` to `StyleLayer | undefined`
* `Style.getLayer()` from returning `StyleLayer` to `StyleLayer | undefined`
Those _declared_ return types are changing to match the existing _documented_ behaviour, and brings them in line with the existing similar `Map.getSource()` and `Style.getSource()` methods.
* Does this constitute a (breaking) public API change?
Yes and no. It's making the TypeScript-advertised type match the already-documented and implemented behaviour. It is possible that this could cause existing code to fail to compile if it's calling `getLayer()` and is compiled with a strict type-checking mode that will flag up that the return type is not being checked for `undefined`.
See PR #724 for …
=> Fix typing of Map.getLayer() and Style.getLayer()

src/source/video_source.ts
Along with https://github.com/maplibre/maplibre-style-spec/pull/297, closes the documentation request in https://github.com/maplibre/maplibre-gl-js/issues/2922.
=> Update docs to describe raster-fade-duration's effect on rendering videos

docs/plugins.md
Added the following two GitHub repository to develop maplibre application in svelte/sveltekit into the documentation.
- [sveltekit-maplibre-boilerplate](https://github.com/watergis/sveltekit-maplibre-boilerplate)
- [svelte-maplibre-components](https://github.com/watergis/svelte-maplibre-components)
=> doc: added svelte-maplibre-components and sveltekit-maplibre-boilerplate on the plugins page

CHANGELOG.md, src/ui/map.test.ts, src/ui/map.ts, src/util/throttle.ts
- Closes https://github.com/maplibre/maplibre-gl-js/issues/2971
- Replaces https://github.com/maplibre/maplibre-gl-js/pull/2973 - I think throttle probably turned out better anyway!
- Throttles the map's ResizeObserver's call to map.resize(), to 50 milliseconds
- Adds argument support to existing throttle() utility
- Still ignores ResizeObserver's initial call, with subsequent calls throttled
- Resizing in Chrome and Firefox behaves considerably better, with much less flicker
=> Throttle ResizeObserver's call to map.resize()

test/examples/cooperated-gestures.html
This is to show how cooperative gestures behave on fullscreen mode.
Related to #2152 and #1488.
=> Improve cooperative gesture example

test/examples/local-ideographs.html
The docs https://maplibre.org/maplibre-gl-js/docs/examples/local-ideographs/ state the opposite of what this setting actually does. Sped-up map load times with local ideographs is the default, and no setting is necessary, but setting it to `false` will disable local ideographs. Finally, setting the value only specifies device font fallbacks that override the style. 
Related to #2990
=> Revise description of localIdeographFontFamily example

CHANGELOG.md, src/ui/map.test.ts, src/ui/map.ts
Related to https://github.com/maplibre/maplibre-gl-js/pull/2993. Updates map.getTerrain() typing for consistency with map.setTerrain(), specifying that it may return null (i.e. if terrain is not set).
=> Update typing of getTerrain to be consistent with setTerrain

CHANGELOG.md, LICENSE.txt, build/generate-dist-package.js
Fixes #2865 
This PR consists of three changes:
- [when creating dist/package.json, also copy LICENSE.txt from repo root](https://github.com/maplibre/maplibre-gl-js/commit/6b827479cad87a87cd04d6212fcfdd2a58c402c0)
- This is achieved by modifying `generate-dist-package.js`. I assume this file must be run during build, but couldn't see where in the GitHub actions. This seemed like the best place without adding a rollup plugin or relying on an OS specific command.
- I tested with local npm installation and upon `ng build` the license was included in 3rdpartylicenses.txt.
- [set name in dist/package.json to maplibre-gl](https://github.com/maplibre/maplibre-gl-js/commit/9213b1f0678f1d26d4e4409484640e515496b6ec)
- This will ensure that the package name as listed in 3rdpartylicenses.txt is …
=> Copy LICENSE.txt to dist folder so it's included in 3rdpartylicenses by webpack

CHANGELOG.md, jest.config.ts
This PR is to resolve a test warning introduced with https://github.com/maplibre/maplibre-gl-js/pull/3021.
To resolve this, the dist folder is added to jest config `modulePathIgnorePatterns` so that it's not visible to jest, preventing the duplicate module warning.
=> jest ignore dist folder

CHANGELOG.md, src/ui/handler/scroll_zoom.ts, test/integration/browser/browser.test.ts
Fixes #2709
This basically resets the scroll handler state better which solves the above bug.
I couldn't find a way to test this using the existing unit test, as they are more of integration tests.
The browser test was a last resort, but it reproduces the bug perfectly.
=> Reset scroll handler state properly

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts, test/build/min.test.ts, test/integration/browser/browser.test.ts
Fixes #2868.
We need to update the marker position after the terrain is loaded; when the map is fully loaded an _idle event_ is fired.
So the approach was that after the _terrain event_ is detected by the marker wait till an idle event is reached.
https://github.com/maplibre/maplibre-gl-js/assets/10349981/5d2b7ec7-f179-4379-9e2f-88c46f33f0f6
=> fix: [issue-2868] after enabling terrain, the _update marker method was not called

.npmrc
maplibre-gj-js uses lock file version 3 (https://github.com/maplibre/maplibre-gl-js/blob/main/package-lock.json) so we should specify here in the `.npmrc` to help prevent changes. I added spaces between the = to make it easier to read.
Info: https://docs.npmjs.com/cli/v10/using-npm/config#lockfile-version 
As this is so minor, I haven't changed the CHANGELOG.md.
=> Add lock file version to `.npmrc`

CHANGELOG.md, package-lock.json, package.json, src/style/style_layer.test.ts, src/style/style_layer/line_style_layer.test.ts, src/style/style_layer/line_style_layer.ts, src/ui/map.ts
This PR fixes #2683
A `StyleLayer` is added to a map by calling [`map.addLayer`](https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.Map/#addlayer). In particular, we can add a `LineStyleLayer` that adds a color gradient (`line-gradient`) as follows:
```
map.addLayer({
type: 'line',
source: 'line',
id: 'line',
paint: {
'line-color': 'red',
'line-width': 14,
'line-gradient': [
'interpolate',
['linear'],
['line-progress'],
0,
'blue',
1,
'red'
]
}
});
```
Our problem comes when we try to unset the `line-gradient` using [`Map.setPaintProperty`](https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.Map/#setpaintproperty):
```
map.setPaintProperty('line', 'line-gradient', null)
```
Note the third argument, `null`, which is meant to unset the property. (Note that `null` and …
=> Fix setting line-gradient to null/undefined

CHANGELOG.md, src/ui/handler_manager.ts, test/integration/browser/browser.test.ts
To fix issue #2238, this PR modifies the camera animation behavior on Mac when the 'reduced motion' setting is on.
The **camera.easeTo** method is called after the map movement happens, in order to add if needed a kind of "inertia movement". The *easeTo* method is called with the **around** property option with the position that should be the end of the camera ease movement.
Currently, when the 'reduced motion' setting is on, the duration is changed by 0. This does not avoid the final result, it only avoids the animation, because the final result will be at the **around** position, so it looks like an unexpected jump.
Example of the current behaviour, another example can be found here #2238
https://github.com/maplibre/maplibre-gl-js/assets/10349981/df381d05-a92b-4561-a677-9cde719a1549
- …
=> fix: [issue-2238] stop camera animation on mac when reduced motion is on

CHANGELOG.md, src/source/raster_tile_source.ts, test/examples/map-tiles.html
Stamen is discontinuing our current method of serving our flagship map styles (read more about that [here](https://stamen.com/here-comes-the-future-of-stamen-maps/)) and the current link will be broken in a month.  This PR updates the any references to the old Watercolor map tile end point with a new link to the tiles hosted by the [Cooper Hewitt Design Museum](https://watercolormaps.collection.cooperhewitt.org/#12/40.7847/-73.9574).
running locally, the change works!
the new `tiles` url in the locally running web page
=> update stamen tile endpoints

test/examples/map-tiles.html
Building on #3105, this adds a comment about how to authenticate to the Stadia Maps tile servers.
It also updates the license information for the Watercolor tiles. TL;DR, adds attribution for Stadia hosting the tiles, standardizes the OSM attribution to match modern convention, and removes the CC BY 3.0 reference as it is confusing what it applies to (that's clarified below), and Stamen also bumped it to 4.0 to allow for easier use in academic contexts (IIRC; @RossThorn or @almccon can confirm details if desired).
The _tiles_ served by Stadia Maps are subject to our standard ToS, which prohibits things like mass downloads / caching forever. This is clarified on https://stadiamaps.com/attribution/, but is way too long to fit the distinction between design, code, and tile access in an …
=> Add auth information + update license for Stamen Watercolor

docs/plugins.md
Remove unsupported "mapbox-gl-style-switcher" plugin from docs
=> Remove unsupported "mapbox-gl-style-switcher" plugin from docs

test/examples/contour-lines.html
Bump maplibre-contour plugin in demo to version 0.0.4 to pull in https://github.com/onthegomap/maplibre-contour/pull/85 so that the demo works properly on iOS 17 private browsing mode.
=> Bump maplibre-contour plugin in demo to fix safari DEM issue

CHANGELOG.md, src/source/raster_tile_source.test.ts, src/source/raster_tile_source.ts
Resolves #3207. Adds a `setTiles` method to `RasterTileSource`. Changes made:
- Add `setTiles` to `RasterTileSource`
- Add unit test to confirm tiles update
- Changelog entry
[Screencast from 2023-10-11 13-43-31.webm](https://github.com/maplibre/maplibre-gl-js/assets/133472204/9ee52951-5289-4710-a77a-2418da89039a)
=> Add RasterTileSource setTiles method

jest.config.ts, tsconfig.jest.json, tsconfig.json
Async/await causes trouble in the bundle, so this PR compiles it down to es2016 promises.
Related to
- https://github.com/maplibre/maplibre-gl-js/discussions/3210#discussioncomment-7304396
- #3209
=> Remove async/await from bundle

CHANGELOG.md, package-lock.json, package.json
- Fix regression introduced in 3.5.0, related to async/await ([#3228](https://github.com/maplibre/maplibre-gl-js/pull/3228))
=> Release 3.5.1

src/source/worker.test.ts, src/source/worker.ts, src/util/actor.test.ts, src/util/actor.ts, src/util/dispatcher.ts, src/util/web_worker.ts, src/util/web_worker_transfer.ts, src/util/worker_pool.ts, test/unit/lib/web_worker_mock.ts
This mainly type changes (a few minor code changes).
I needed a break from the angular/webpack/babel stuff.
@msbarry can you take a look and suggest what can be done better?
Going forward I would like every message type to have a data type associated with it so that when you send a message you know what data you send with it, but that can be done as a later step.
=> Improve `Actor` typings

CHANGELOG.md, test/examples/variable-offset-label-placement.html
The title of the example is duplicated and caused a search confusion.
I forgot to add a change in the behavior in previous PR.
Both fixed in this small PR.
=> Small correction to change log and an example's duplicate title

CHANGELOG.md, src/style/style.test.ts, src/style/style.ts
Fix issue https://github.com/maplibre/maplibre-gl-js/issues/3214, add `terrain` property to map `style` object.
**Before**
**After**
---
-----
closes #3214
=> Add terrain property to map style object

CHANGELOG.md, src/gl/webgl2.ts
`gl.getParameter(gl.VERSION)` returns null on some browsers, so `gl.getParameter(gl.VERSION).startsWith(...)` throws an exception. This change makes it so that `isWebGL2` returns false on browsers where `gl.getParameter(gl.VERSION)` returns null.
=> Fix exception thrown from `isWebGL2` check

CHANGELOG.md, build/rollup_plugins.ts, rollup.config.ts, tsconfig.json
When running in watch mode (`npm start`) I noticed that the dev js build wasn't getting rebuilt when files changed, just the staging chunks. It turns out that the first stage of the rollup build is aware of which input files get combined into which output files, but the second stage that merges the staging chunks into a dev.js build is not. I found [this stackoverflow post](https://stackoverflow.com/a/63548394) that explains how to resolve this issue by telling rollup explicitly to watch a set of file.  `npm start` rebuilds the dev.js file on each change now.
=> Fix rollup watch mode

CHANGELOG.md, package-lock.json, package.json
- Convert plantuml diagrams to mermaid ([#3217](https://github.com/maplibre/maplibre-gl-js/pull/3217))
- Improve buffer transfer in Safari after Safari fixed a memory leak bug ([#3225](https://github.com/maplibre/maplibre-gl-js/pull/3225))
- Minify internal exports to reduce bundle size ([#3216](https://github.com/maplibre/maplibre-gl-js/pull/3216))
- Add terrain property to map style object ([#3234](https://github.com/maplibre/maplibre-gl-js/pull/3234))
- Fix exception thrown from `isWebGL2` check ([#3238](https://github.com/maplibre/maplibre-gl-js/pull/3238))
- Fix rollup watch mode ([#3270](https://github.com/maplibre/maplibre-gl-js/pull/3270))
=> Release 3.5.2

src/render/glyph_atlas.ts, src/render/glyph_manager.test.ts, src/render/glyph_manager.ts, src/render/image_atlas.ts, src/render/image_manager.ts, src/source/geojson_worker_source.test.ts, src/source/vector_tile_source.ts, src/source/vector_tile_worker_source.test.ts, src/source/worker.test.ts, src/source/worker.ts, src/source/worker_source.ts, src/source/worker_tile.test.ts, src/source/worker_tile.ts, src/style/style.test.ts, src/style/style.ts, src/ui/map.test.ts, src/util/actor.test.ts, src/util/actor.ts, src/util/actor_messages.ts, src/util/test/util.ts, src/util/web_worker_transfer.ts, test/bench/lib/tile_parser.ts, test/unit/lib/web_worker_mock.ts
I want to make sure that I don't mess things up so I'm keeping this PR open to see that the tests are passing.
I think I'll do most of the leftover improvements in this PR.
Let's see how big it gets.
=> More improvement to async `Actor` and replace more callbacks with promises 

.github/workflows/release.yml, .github/workflows/test-all.yml, .github/workflows/upload-benchmarks.yml
Node LTS just changed from 18 to 20 making the CI fail.
While there's a need to fix this and update node, this will make a simple place to change the version for all the CI related flows and to developers using nvm (which they should).
=> Use node version from .nvmrc file in CI

CHANGELOG.md, src/util/resolve_tokens.test.ts, src/util/resolve_tokens.ts
There is a bug in `resolve_tokens`. When the feature properties are null, the code breaks with `TypeError: Cannot use 'in' operator to search for 'name' in null`. This can easily happen with GeoJSON source, that has some feature with `properties: null`, which is valid value according to GeoJSON specification.
=> Fix null feature properties in resolve_tokens

src/index.test.ts, src/source/image_source.test.ts, src/source/image_source.ts, src/source/raster_dem_tile_source.ts, src/source/raster_tile_source.ts, src/source/rtl_text_plugin.ts, src/source/tile.ts, src/source/vector_tile_worker_source.ts, src/style/load_glyph_range.ts, src/style/load_sprite.test.ts, src/style/load_sprite.ts, src/ui/map.ts, src/util/actor.test.ts, src/util/ajax.test.ts, src/util/ajax.ts, src/util/image_request.test.ts, src/util/image_request.ts, src/util/test/util.ts, src/util/util.test.ts, src/util/util.ts, test/build/min.test.ts
The PR #3276 and its branch have too many changes and I can't seem to be able to fix the tests, I need to take slower steps still...
This is now ready for review
=> Move image queue to use promises, move getArrayBuffer to use promises

CHANGELOG.md, src/style/style.test.ts, src/style/style.ts, src/ui/map.test.ts, src/ui/map.ts
Closes https://github.com/maplibre/maplibre-gl-js/issues/3277. Adds a getter for Style's _order "private" property to Style and Map.
=> Add getLayersOrder() to Map and Style

CHANGELOG.md, test/examples/fullscreen.html
Fixes #3306 
In the issue https://github.com/maplibre/maplibre-gl-js/issues/3306 I discovered and described that the fullscreen mode example does not work on iOS because an iframe is used which prevents the map from scaling. I have therefore extended the description of this example accordingly.
=> Add note on pseudo fullscreen mode on iOS

docs/plugins.md
A url of `maplibre-gl-temporal-control` is missing because I've transfered it to organization [mug-jp](https://github.com/mug-jp), then replaced it.
=> fix: replace missing url of my plugin to newest

src/data/dem_data.ts, src/data/feature_index.ts, src/render/glyph_manager.test.ts, src/render/image_atlas.ts, src/source/geojson_worker_source.test.ts, src/source/geojson_worker_source.ts, src/source/rtl_text_plugin.ts, src/source/vector_tile_source.test.ts, src/source/vector_tile_worker_source.test.ts, src/source/vector_tile_worker_source.ts, src/source/worker_source.ts, src/source/worker_tile.test.ts, src/source/worker_tile.ts, src/style/style.test.ts, src/style/style_glyph.ts, src/ui/handler/dblclick_zoom.test.ts, src/ui/map.test.ts, src/util/actor.test.ts, src/util/actor.ts, src/util/actor_messages.ts, src/util/ajax.test.ts, src/util/ajax.ts, src/util/image.ts, src/util/image_request.test.ts, src/util/util.ts, test/bench/lib/tile_parser.ts, typedoc.json
This is PR is intended to fix all the docs issues, remove the TODOs, simplify ajax method a bit.
I've opened the relevant issues to track things I found in the code.
Changes here are syntactic mostly.
=> Async actor docs additions

.github/workflows/release.yml, build/bump-version-changelog.js, developer-guides/release-process.md
This does the following steps in the release workflow:
1. Add a required input of the version number
2. Updates the changelog and package.json (and lock) files.
3. Commits the changes to main branch
4. Continues with the regular flow of the release.
This removes the need to create a PR with a version bump which is very manual and redundant.
The changelog changes is done in a new script I added as part of this PR.
=> Removes manual steps in creating a version

.github/workflows/release.yml
Uses a more popular GitHub action, also does the tag push in the same action, which makes more sense...
=> Use a more popular push and commit GitHub action

.github/workflows/create-bumb-version-pr.yml, .github/workflows/release.yml, developer-guides/release-process.md
This changes the release process to do the following steps:
1. Allow creating a bump version PR from the workflows manual run menu, allowing to set the version number.
2. Checks every commit to see if the `package.json` file had changed, if so, it will publish a version to npm and github automatically.
I tried to do it in one step but there are problems with permissions etc and I didn't want to create a PAT just for this.
While it's not ideal, we'll be able to push version more easily now.
=> Automate release

.github/workflows/release.yml, developer-guides/release-process.md
Seems like GitHub Actions workflow runner doesn't have the right permissions to use org level secrets, so this needs to be manual again to have the right permissions, unfortunately...
I've updated the workflow and the relevant readme.
=> Revert release.yml to original version

CHANGELOG.md, src/util/actor.test.ts, src/util/actor.ts, src/util/util.ts
Fixes #3239.
It also builds the infrastructure need in order to resolve the problems described here: https://github.com/maplibre/maplibre-gl-js/pull/2707#issuecomment-1797847191
cc: @neodescis, @clementmas, @JannikGM 
This is an addition on top of the async actor branch ATM as I assume it will be merged soon.
=> Fix Actor XSS, introduce subscribe

.github/workflows/release.yml
Hopefully this would solve the issue.
If now, I can try and revert to the previous definition of the node version, it might help, IDK...
Based on this:
https://github.com/npm/cli/issues/6184#issuecomment-1544496444
=> Add registry url to allow publishing npm package

.github/workflows/release.yml, developer-guides/release-process.md
This allows the release to run on main every time there's a push.
It will check if the current version is the same, if not, it will publish a release to npm and all the other release stuff.
I've tested this to work on ngx-maplibre-gl, so I'm confidant that this is possible now.
=> Allow release to run on every commit to main

docs/README.md, docs/guides/large-data.md
Resolves #2823
The pull request:
- adds a 'Guides' section to the documentation
- adds a guide on working with large GeoJSON datasets, following the discussion in https://github.com/maplibre/maplibre-gl-js/issues/2823
=> Add a guide on working with large datasets

src/source/geojson_worker_source.test.ts, src/source/vector_tile_worker_source.ts, src/source/video_source.ts, src/style/style.ts, src/ui/map.test.ts, src/ui/map.ts, src/util/ajax.ts, test/bench/lib/create_map.ts
Removes more places that use cancelable in favor of abort controller.
Changes getVideo to return a promise instead of callback/cancelable.
Improve usage in async in tests and added a spy.
=> Async actor remove cancelables

src/ui/map.ts, test/examples/canvas-source.html
The following example looks broken, at least on Firefox. This PR fixes it.
https://maplibre.org/maplibre-gl-js/docs/examples/canvas-source/
Before
After
=> Fix the canvas-source example

src/geo/transform.ts, src/render/terrain.test.ts, src/render/terrain.ts, test/build/min.test.ts
Fixes #3048.
Zoom was incorrect when mouse position and map center were on the opposite sides of 180 meridian. (With terrain 3d enabled).
To solve this, mercator coordinate has to be outside [0,1] range:
a) negative if mouse was on the left of 180
b) >1 if mouse was on the right of 180
(It's how it works in no-3d mode).
=> Fix zoom around 180 meridian (#3048)

.github/workflows/release.yml
Last pre-release (4.0.0-pre.1) was not published to npm due to an issue with the action.
I have removed the action and written the code instead.
Relevant issue:
https://github.com/EndBug/version-check/issues/158
=> Fix issue with pre-release check in CI

src/source/geojson_source.ts, src/style/light.ts, src/util/util.ts
This adds proper typings to the `extend` method.
To be honest, I'm not sure if this method is the same as `Object.assign`, so I'm not sure it's actually needed.
But, just in case it's not, I improved the typings on it.
=> Improve `extend` typings

CHANGELOG.md, src/util/image_request.ts, src/util/util.ts
This PR tries to solve the issue of multiple errors in case of loading raster tiles from server responding 204s with no content.
Related to #160 and #1586, but a different approach.
There are currently two ways of loading the image data (ArrayBuffer):
- `arrayBufferToImage` ("legacy" way which uses `Image` under the hood) 
- the newer `arrayBufferToImageBitmap` (which requires [createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap)).
The legacy path has [always](https://github.com/maplibre/maplibre-gl-js/commit/f183b416b152868c2f787dbfa78f173fccfadb78#diff-bb4eb119021870bc4f2e7fcd6b535235bad4b6316c2d23ff218b5f5f2614fbabR67) been able to handle 204s correctly by load a transparent image instead: https://github.com/maplibre/maplibre-gl-js/blob/859b1a7c1d88a111 …
=> Handle loading of empty raster tiles (204 No Content)

CHANGELOG.md, src/ui/popup.test.ts, src/ui/popup.ts
Fixes #3405
The ".maplibregl-track-pointer" CSS class get's added to the map when a popup uses its `trackPointer` method. This makes sure the map displays a pointer cursor. The issue is that when you disable the popup using its `remove` method it doesn't remove this CSS class from the map causing the cursor to be shown as a pointer indefinitely.
When using a popup's `remove` method it will make sure to remove the ".maplibregl-track-pointer" CSS class from the map.
Before:
After:
=> Fix popup.trackPointer pointer cursor bug

CHANGELOG.md, test/integration/render/tests/text-variable-anchor-offset/pitched/style.json, test/integration/render/tests/text-variable-anchor/pitched/style.json
In continue to #3452, where I forgot to add this...
=> Update CHANGELOG.md with node upgrade

test/examples/contour-lines.html
Bump maplibre contour to 0.5.0 in the examples directory so that it will work with either maplibre v3 or v4 (https://github.com/onthegomap/maplibre-contour/pull/128)
See this example running against maplibre v4: https://onthegomap.github.io/maplibre-contour
vs. this example running against maplibre v3: https://onthegomap.github.io/maplibre-contour/maplibre-v3.html
=> Bump maplibre contour to 0.5.0

CHANGELOG.md, src/index.ts, src/source/add_protocol.ts, src/source/protocol_crud.ts, src/source/source.test.ts, src/source/source.ts, src/source/worker.test.ts, src/source/worker.ts, src/util/actor_messages.ts, src/util/ajax.ts, src/util/image_request.ts, src/util/web_worker.ts, test/integration/render/tests/text-variable-anchor-offset/pitched-offset/style.json, test/integration/render/tests/text-variable-anchor-offset/pitched-with-map/style.json, test/unit/lib/web_worker_mock.ts
This allows adding a protocol in the worker thread by exposing an addProtocol method in the workers code and allowing to import a code into the workers.
One issue I noticed is that the `raster` source is not using the worker thread at all since all it does it fetch an image and convert it to pixels, so there's not much work in the works anyway, which means that if you add a protocol in the worker thread but use a raster source it won't be called.
This means that the developer needs to know where to add the method, which is OK, as the default is in the main thread and only if you'd like to optimize things you can move it to the worker thread.
The rest is the same.
I've also removed the import of the script when adding a source type, so that importing a script has only one entry point.
cc: …
=> Allow `addProtocol` in the worker code

test/bench/components/RegressionPlot.tsx, test/bench/components/StatisticsPlot.tsx
the code for adapting the benchmark graphs to parent width busy loops for me.
the width of the parent is hardcoded anyway so I just hardcoded it here also and removed the offending code.
I think for the benchmarks simpler code and less react knowledge is more important than the unused feature.
- [+] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
=> hardcode width to avoid busy loop after benchmark is run

docs/plugins.md
This is only adding a reference to the documentation concerning the maplibre integrations
=> Update plugins.md: add jekyll integration

test/integration/render/tests/text-variable-anchor/pitched-with-map/style.json, test/integration/render/tests/text-variable-anchor/pitched/style.json
This adds a few waits to flickering tests.
I believe that there's a race condition in these tests that prevents them from succeeding, but I don't have a good idea how to solve it, and this is the simplest solution.
=> Improve tests reliability

src/ui/map.ts
As noted by @HarelM in https://github.com/maplibre/maplibre-gl-js/pull/3558#issuecomment-1883814307, the change in https://github.com/maplibre/maplibre-gl-js/pull/3545 (presumably when combined with the changes in https://github.com/maplibre/maplibre-gl-js/pull/3515) resulted in a failing browser test, where "idle" events aren't being correctly fired.
This is caused by terrain tiles getting stuck in the "updating" state.  This happens when `sourceCache.reload()` is called needlessly, i.e. when terrain is set on a map that already has terrain, as happens in the render test.
This fix ensures that the tile reloading only happens when terrain is added to a map that previously had no terrain.
=> Fix failing browser test by updating tiles only when adding new terrain

.github/workflows/release.yml, package.json
This fixes the prepare script to be more robust due to recent changes that require the types to be present while transpiling the rest of the project.
=> Fixes prepare script

test/examples/animate-a-line.html, test/examples/change-building-color-based-on-zoom-level.html, test/examples/fitbounds.html, test/examples/flyto-options.html, test/examples/flyto.html, test/examples/language-switch.html, test/examples/mouse-position.html, test/examples/render-world-copies.html
some examples has overlay button, but they are render with wrong position.
so fixed the wrong positioning of the overlay buttons in the example.
https://maplibre.org/maplibre-gl-js/docs/examples/language-switch/
=> Fix example button position

README.md
Fixed broken link in README that previously lead to not found page in `react-map-gl` docs
=> Fix broken React bindings link

.github/workflows/test-all.yml, package-lock.json, package.json, test/integration/render/run_render_tests.ts
In order to solve the coverage issues introduced with v8 and the render test a different coverage tool is needed apparently.
See here:
https://github.com/cenfun/monocart-coverage-reports/issues/4
And here:
https://github.com/istanbuljs/v8-to-istanbul/issues/238
=> Replace v8 with monocart for coverage

src/index.ts, src/ui/events.ts
This was exported in previous version, and it seems like I forgot it, it was also missing in the docs in the relevant part.
This is in continue to:
- #3601
=> Added MapMouseEvent type to export

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts, test/build/min.test.ts
Implements https://github.com/maplibre/maplibre-gl-js/issues/3458
A small caveat here.
This solution means that all users have to provide an array of 2 strings. (2nd string is the reduced opacity when marker is behind the terrain).
But in most cases (without 3d terrain) this second string will be useless and just an incovenience.
Perhaps it makes sense to split this single option and method to:
'opacity/setOpacity' and 'reducedOpacity/setReducedOpacity'
=> Add Marker's "opacity" option and "setOpacity" method

build/generate-docs.ts, package.json, src/geo/lng_lat.ts, src/geo/lng_lat_bounds.ts, src/geo/mercator_coordinate.ts, src/index.ts, src/source/protocol_crud.ts, src/ui/camera.ts, src/ui/control/attribution_control.ts, src/ui/control/fullscreen_control.ts, src/ui/control/geolocate_control.ts, src/ui/control/logo_control.ts, src/ui/control/navigation_control.ts, src/ui/control/scale_control.ts, src/ui/control/terrain_control.ts, src/ui/events.ts, src/ui/handler/cooperative_gestures.ts, src/ui/map.ts, src/ui/marker.ts, src/ui/popup.ts, src/util/global_worker_pool.ts, src/util/worker_pool.ts, test/integration/render/tests/text-offset/line-collision/style.json, typedoc.json
This is in continue to:
- https://github.com/Gerrit0/typedoc-plugin-missing-exports/issues/23
This removes the maplibregl module from the docs and remove this prefix.
It is available in the examples, but when using this with a bundler (which is the most used case nowadays) you should not use this prefix and just import what you need.
=> Remove maplibregl prefix from docs

src/ui/marker.test.ts
Concludes https://github.com/maplibre/maplibre-gl-js/issues/3458
=> Test opacity of a partly visible marker

src/render/render_to_texture.test.ts, test/build/min.test.ts
try to fix the sky2 branch 'Unit tests and Coverage' calculateFogMatrix error
```
Error: TypeError: painter.transform.calculateFogMatrix is not a function
at drawTerrain (src/render/draw_terrain.ts:88:45)
at RenderToTexture.renderLayer (src/render/render_to_texture.ts:[18](https://github.com/maplibre/maplibre-gl-js/actions/runs/7742575082/job/21112014472?pr=3645#step:6:19)7:24)
at Object.<anonymous> (src/render/render_to_texture.test.ts:1[19](https://github.com/maplibre/maplibre-gl-js/actions/runs/7742575082/job/21112014472?pr=3645#step:6:20):[20](https://github.com/maplibre/maplibre-gl-js/actions/runs/7742575082/job/21112014472?pr=3645#step:6:21))
Error: TypeError: painter.transform.calculateFogMatrix is not a function
at drawTerrain (src/render/draw_terrain.ts:88:45)
at …
```
=> fix sky2 calculateFogMatrix error and build error

src/ui/map.ts
The docs for [`setFeatureState`](https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/#setfeaturestate) include a list but that list is not formatted as such. That makes it hard to read.
> <img width="708" alt="image" src="https://github.com/maplibre/maplibre-gl-js/assets/111561/35d87e9b-9cc7-4513-977c-06593038700d">
I am not sure how the Markdown formatting of the doc comments work exactly but I am assuming that a new line before the list starts and `*` for the list might solve the issue.
=> Docs: Format list for `setFeatureState`

src/geo/mercator_coordinate.ts, src/source/tile.ts, src/style/style_layer/custom_style_layer.ts, src/ui/map.ts, src/ui/popup.ts
This is a follow up to https://github.com/maplibre/maplibre-gl-js/pull/3655 but looks at all the other places where a list was used without an empty line above. The missing empty line is what breaks the markdown processing.
The list style that is used consistently in this PR is `-` which makes the list easier to read than the `*` I used in #3655.
=> Docs: Improve list styles

build/generate-docs.ts, docs/README.md
One commit adds a hin on how to add lists on the docs so they are formatted as html list (see https://github.com/maplibre/maplibre-gl-js/pull/3657).
Another commit streamlines the use of "npm run start-docs" which made it easier for me to understand the whole setup.
=> Docs: Hint at how to add lists and streamline commands

build/generate-docs.ts
The `!` moves on level up so this error goes away:
=> Docs: Fix a type warning on `generateMarkdownForExample`

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts, test/integration/browser/browser.test.ts
Fixes https://github.com/maplibre/maplibre-gl-js/issues/3646
https://github.com/maplibre/maplibre-gl-js/assets/11789697/4a68acdd-a41e-4c36-9088-138eb6cd6604
On resize Marker was updated **before** map._render.
When marker is updated, it reads the depthTexture to figure out the terrainDistance.
At this moment depthTexture was **empty** because it was just re-initialized due to resize. It was populated only later as part of map._render.
So the order of events on each resize was: _resize -> destroy depthTexture -> read it -> populate it_.
My idea is to delay opacity-related code using requestAnimationFrame (because map render is delayed so). It ensures that marker's opacity is updated **after** map render and after drawDepth.
From my understanding, this fix is untestable because …
=> Fix marker opacity after resize

.github/workflows/test-all.yml
Reverts #3661 as we don't get coverage report in version 4.
This is because version 4 requires codecov token, and there's still a discussion around how dependabot will use it:
https://github.com/codecov/feedback/issues/264
I generally would like to avoid adding a secret if possible.
=> Revert "Bump codecov/codecov-action from 3 to 4"

CHANGELOG.md, src/source/raster_tile_source.test.ts, src/source/raster_tile_source.ts
This PR adds the `setUrl` function to RasterTileSource:
- Add `setUrl` to RasterTileSource
- Add unit test to confirm tilejson url update
- Changelog entry
=> Adds RasterTileSource#setUrl method

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts, src/ui/popup.test.ts, src/ui/popup.ts, src/util/smart_wrap.test.ts, src/util/smart_wrap.ts
Fixes https://github.com/maplibre/maplibre-gl-js/issues/2871
The problem here is smartWrap.
It's not designed for 3d world.
It measures distances between points **based on their screen position**. The goal is to provide smooth transition of a Marker/Popup from central globe to the side globes.
This technique is safe only when there is no terrain and no high pitch/bearing.
Now there are many scenarios in which smartWrap will cause quirky behaviour. (Though they are very unlikely to happen for a sensible user).
https://github.com/maplibre/maplibre-gl-js/issues/2871 is only one of such cases. Another one for [example](https://github.com/maplibre/maplibre-gl-js/assets/11789697/9042dcfb-895d-46c6-919f-194f03af5b47).
All these quirks are reproducible for **Popups too**.
They mostly happen when …
=> Fix marker flying off near horizon

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts, src/ui/popup.ts
Fixes https://github.com/maplibre/maplibre-gl-js/issues/2775
Idea is to set lngLat every time the popup is opened (when Popup.addTo is called) and to reset the previous position.
This prevents smartWrap from doing its bad job.
https://github.com/maplibre/maplibre-gl-js/assets/11789697/fe6eadd0-1931-40f2-ae07-7e537513bca5
=> Fix popup position around marker that was moved to side globe

CHANGELOG.md, src/css/maplibre-gl.css
Set the text color to ensure readability/contrast of the attribution pill.
| before | after |
| --- | --- |
| ![before](https://github.com/maplibre/maplibre-gl-js/assets/7001/a3209868-e3cd-4882-993c-ecf643b2a358) | ![after](https://github.com/maplibre/maplibre-gl-js/assets/7001/9dc38358-beaf-4126-8ca6-84937a7489bb) |
(In the example above, the page's **text** has a light color, to contrast with the dark background. This percolates to the attribution text, which is set on a light background.)
Only the text color needs to be specified. The background is specified in 
https://github.com/maplibre/maplibre-gl-js/blob/0aeb2c0f926fcb4f922791642f0e3ee8119043a2/src/css/maplibre-gl.css#L448
and the link color is specified in 
https://github.com/maplibre/maplibre-gl-js/blob/0aeb2c0f926fcb4f922791642f …
=> set text color in the attribution pill

CHANGELOG.md, src/source/worker.test.ts, src/source/worker.ts, src/style/style.ts, src/ui/map.test.ts, src/util/actor_messages.ts
=> Fix memory leak in Worker when map is removed (#3733)

build/generate-struct-arrays.ts
- #2053 
Fixes #2053 
As described in the issue, this warning is not helpful and no one seems to be looking at it, also it seems that maplibre-gl is working as expected, so I'm not sure this warning is still relevant.
Warnings:
```
Warning: The layout StructArrayLayout3i6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout3ui6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout3i6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout3ui6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout1ui2 is not aligned to 4-bytes boundaries.
```
=> Remove the "The layout Struct..." warning in code generation 

CHANGELOG.md, src/geo/transform.test.ts, src/geo/transform.ts, src/ui/camera.test.ts, src/ui/camera.ts
I know there's a lot to review now so don't haste with this )
This PR involves several methods that animate the map's scale and center:
- `flyTo` (and therefore `fitBounds` and `fitScreenCoordinates`)
- `easeTo `(and therefore `panTo `and `panBy`)
These methods don't animate well when the destination point is near the bounds: those set by maxBounds, by vertical edges of the world, by antimeridian on single-globe map.
What is apparently incorrect in current easeTo and flyTo algorithms is that they don't apply these constraints when deciding on the destination. They just take the destination lngLat as it was provided by a user.
The result is that this "optimistic" animation hits the bounds somewhere in the process, and a smooth curve breaks into something more linear.
This PR fixes this …
=> Fix bad curve on easeTo/flyTo in constrained space

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts
Currently popups do not change opacity when hidden by terrain.
It looks especially bad when a popup is attached to a marker. Marker becomes semi-transparent, and popup doesn't.
By this PR I suggest to hide a "dependent" popup when its marker is behind terrain.
It's not the only possible solution but **1)** it's simple  and **2)** it actually seems more adequate than making a popup semi-transparent because such semi-transparent popup will create a lot of visual noise.
So here I make sure that
1) when marker gets hidden, it will close its popup
2) when marker is hidden, click will not open its popup
https://github.com/maplibre/maplibre-gl-js/assets/11789697/e48cc6f8-9abf-4551-be44-a8e977fc454c
This solution does not affect independent popups. They will still be fully opaque behind terrain. …
=> Remove popup when marker is behind terrain

CHANGELOG.md, src/render/glyph_manager.ts, src/style/style.ts, src/ui/map.ts
close #3895 
This PR make no changes on behavior or functionality, only on type defnition of 
TypeScript.
=> fix: typedef localIdeographFontFamily #3895

CHANGELOG.md, src/ui/popup.test.ts, src/ui/popup.ts
This moves the line that fires close events to be inside the map section. This means that close events won't be fired for popups that weren't open when the popup was removed. The popup close events are currently fired for example when removing a marker that is linked to a popup from the map.
=> Fix close events being fired for popups that aren't open

CHANGELOG.md, src/render/terrain.test.ts, src/render/terrain.ts
When the map canvas is large - >2048px, probably* - the coords canvas stops growing with the map due to web GL limitations. This means that a screen-pixel is no longer 1:1 with a coords-canvas pixel. It needs to be scaled using the ratio of devicePixelRatio and painter.pixelRatio, which are no longer equal when the map is large.
*This might depend on your machine and its willingness to create webgl textures larger than 2048 x 2048.
Fixes https://github.com/maplibre/maplibre-gl-js/issues/3935
https://github.com/maplibre/maplibre-gl-js/assets/7425442/d3fbde71-7de6-4237-ac2d-07eda8846576
https://github.com/maplibre/maplibre-gl-js/assets/7425442/9f1dba0f-71ae-4e17-a7ce-1f09b9af79c7
=> Fix for #3935 - pan-jump when map is large

.github/workflows/test-all.yml
Disable codecov search as was suggested here:
https://github.com/codecov/codecov-action/issues/1354
Looks like the report is returning the expected number of line in the code.
=> Disable search as was suggested

test/integration/render/run_render_tests.ts
This PR makes two changes to render tests that improve the developer's experience when creating/updating render tests:
- Messages for errored tests are printed with a different shade of red, making them more visible at a glance (they now look different than failed tests).
- When updating render tests, it print a slightly different message with the count of errored tests after all tests are finished running.
Rationale: when creating a new render test and iterating it, it is very easy to overlook that your test image is not getting updated, because the test is instead timing out, for example because there is an error in the style.json. These changes make such errored (unupdated) tests much more visible.
Before:
After:
Assumption: tests that result in error are not actually updated. But it …
=> Render tests: better visibility of errors when updating expected images

CHANGELOG.md, src/source/image_source.test.ts, src/source/image_source.ts
This fixes image sources not being marked as loaded when loading of the image fails. 
This behavior changed as a result of https://github.com/maplibre/maplibre-gl-js/commit/859b1a7c1d88a111031f3938f1c329604120f1e0#diff-d4cf28d025bceded1ecd0f4b0b3095b831e34317b61f25611d3cf44e82d64c14 as the new try/catch approach doesn't change the `_loaded` variable on error.
=> Fix image sources not being marked as loaded on error

test/integration/render/run_render_tests.ts
Fixes a bug in https://github.com/maplibre/maplibre-gl-js/pull/3980 where the number of errored tests was only printed when at least one test *failed* (was updated), instead of when at least one test *errored*.
Before:
After:
=> Fix printing of errored render test count

CHANGELOG.md, src/ui/control/scale_control.ts
Before this CL, the following would generate an error:
```ts
const scaleCtrl = new ScaleControl():
```
because options is not marked as optional.
=> Fix scale control default parameters

CHANGELOG.md, src/source/source_cache.test.ts, src/source/source_cache.ts, src/ui/map.ts
This PR creates an opt-out behaviour for the changes which were introduced here since version 3.0:
https://github.com/maplibre/maplibre-gl-js/pull/2377
Now there is a new map option (which can also be changed during runtime) that determines whether pending (still loading) tiles from previous (farther) zoom levels are going to be canceled as we zoom in.
The change is backwards compatible, since the default behavior is just as before.
However if we disable the pending tile cancelation, we get the original (pre v3) behavior, which helps to progressively unveil map details when zooming into areas where tiles are not yet cached. For modern devices this could be the desired behavior.
Behavior with tile canceling (now the default, and active since v3): …
=> New map option to decide whether to cancel previous pending tiles while zooming in

README.md
We can link directly to https://visgl.github.io/react-map-gl/docs/get-started now that there is a react-map-gl/maplibre export.
also changed this:
to this:
=> Improve link to react wrapper

src/render/terrain.ts, src/source/terrain_source_cache.ts
fixes markdown syntax. These two classes are internal so it doesn't change anything public
=> Fix docs markdown

build/banner.ts, build/generate-doc-images.ts, build/generate-docs.ts, src/data/bucket/symbol_bucket.test.ts, src/index.ts, src/source/vector_tile_source.test.ts, src/ui/map.ts, test/bench/benchmarks/filter_create.ts, test/bench/benchmarks/filter_evaluate.ts, test/bench/benchmarks/layers.ts, test/bench/benchmarks/paint_states.ts, test/bench/benchmarks/remove_paint_state.ts, test/bench/styles/index.ts, test/bench/versions/index.ts, test/build/min.test.ts, test/build/sourcemaps.test.ts, test/integration/symbol-shaping/shaping.test.ts
The JSON modules / import attribute syntax has been changed from `assert` to `with`, which it appear to finally stabilize on.
https://github.com/tc39/proposal-json-modules
https://github.com/tc39/proposal-import-attributes/
=> use `with` for json modules instead of `assert`

CHANGELOG.md, src/ui/camera.ts
Closes #3760 "map.cameraForBounds returns undefined which is not mentioned in type definition"
map.cameraForBounds and related internal methods return undefined (which is actually mentioned in the documentation), but the TypeScript type signature didn't match. This is a simple fix to add the undefined type to the type signature.
=> Add undefined return type to map.cameraForBounds

package-lock.json
The `maplibre-gl-js` install currently fails on arm64 macs when running Node >= 21.
The error is:
```
../../nan/nan.h:2546:8: error: no matching member function for call to 'SetAccessor'
tpl->SetAccessor(
```
The context is that `maplibre-gl-js` depends on `node-canvas@2.x` which has a dependency on the `nan` package and `nan` 2.17 had a bug that surfaced with node v21: https://github.com/nodejs/nan/pull/966.
Additionally `node-canvas` does not currently provide pre-compiled binaries for Arm64, so a source compile is needed.
So, the solution here is to upgrade the `nan` version to the latest release which fixes support with recent node.
=> Fix node-canvas source compile for node >= v21

CHANGELOG.md, package-lock.json, package.json
Fixes #967 - remove `json-stringify-pretty-compact` from devDependencies.
=> #967 remove json-stringify-pretty-compact from devDependencies

CHANGELOG.md, src/ui/map.ts
The use case is to delegate the style setting to a layer switcher control.
Note that is is already possible to set the style to null using `Map#setStyle(null)`. This PR updates the MapOptions interface to also allow that when a map instance is created.
Supersedes #4003
- [n/a] Link to related issues.
- [n/a] Include before/after visuals or gifs if this PR includes visual changes.
- [n/a] Write tests for all new functionality.
- [n/a] Document any changes to public APIs - documentation is the type
- [n/a] Post benchmark scores.
- [n/a] Add an entry to `CHANGELOG.md` under the `## main` section.
=> Fix MapOptions#style is optional in the Map constructor

test/bench/gl-stats.html, test/examples/filter-within-layer.html, test/examples/timeline-animation.html
- Link labels to inputs
- Add missing title and viewport to GL Stats page
=> Fix a few minor accessibility issues with examples

ARCHITECTURE.md, CONTRIBUTING.md, README.md, build/readme.md, developer-guides/release-process.md, docs/guides/mapbox-migration-guide.md, docs/index.md
- Remove duplicate empty lines - these are ignored and rendered as 1 empty line anyway.
- Change NPM to npm (its always lower-case)
- Add a h1 title to CONTRIBUTING
- All headers should be followed by a line break
P.S. could consider adding a markdownlint config and/or using Prettier?
=> Markdown formatting fixes

tsconfig.json
Set: `forceConsistentCasingInFileNames` rule to true (tsconfig)
This is recommended by Typescript:
https://typescriptlang.org/tsconfig/#forceConsistentCasingInFileNames
I've had this option set locally for and lint and test scripts complete without issues
I discovered this by using [WebHint VS Code extension](https://webhint.io/docs/user-guide/extensions/vscode-webhint/) which also recommend using it. 
https://webhint.io/docs/user-guide/hints/hint-typescript-config/consistent-casing
=> Set: `forceConsistentCasingInFileNames` rule to true (tsconfig)

CHANGELOG.md, src/ui/map.ts
@birkskyum Similar fix was necessary to get `plotly.js` working with `virtual-webgl` (v1).
See https://github.com/plotly/mapbox-gl-js/commit/71e2cfcc875e7a06d81154ba7d419ff3ecee92e4
This is for your brilliant pull request https://github.com/plotly/plotly.js/pull/7015
if you could possibly test a build with `make-baselines-virtual-webgl` to see if it passes on CircleCI 
or alternatively add the following script to the top of plotly.js `devtools/test_dashboard/index.js` and then `npm start` to test interactively.
```html
<script src="https://unpkg.com/browse/virtual-webgl@1.0.6/src/virtual-webgl.js"></script>
```
=> Ensure `loseContext` exists before calling it

build/generate-docs.ts, docs/README.md
+ Add lazy loading to the map examples page
REF: https://squidfunk.github.io/mkdocs-material/reference/images/?h=loading#image-lazy-loading
(Not tested this locally, Docker not working).
=> Docs typo fixes

test/examples/pmtiles.html
The `pmtiles` package v3 is compatible with the new maplibre v4 addProtocol so it does not need the Promise wrapper.
Also updated text formatting and URLs.
=> Update test/examples/pmtiles.html URLs and latest addProtocol API.

docs/plugins.md
A small plugin to use Google Maps with MapLibre. We had a lot of requests to integrate it in our own open source project and I think it will be useful for many others.
=> Add Google Maps plugin link

CHANGELOG.md, src/css/maplibre-gl.css
Fixes #4193: -ms-high-contrast vendor prefix is being deprecated, as per: https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/
This PR merges to main, but note in the linked issue that it is suggested this may be a breaking change...? I don't believe it is a breaking change - the behaviour for MS Edge remains unchanged, and the PR fixes a previously unknown issue with Firefox (potentially other browsers).
Used Windows in high contrast mode to test.
Console warning is no longer present.
Note that Firefox did not appear to be working correctly beforehand (contrast of button elements too low):
=> Apply new contrast feature syntax

docs/index.md
Related to https://github.com/maplibre/maplibre-gl-js/issues/4228. I added how to npm install maplibre-gl on intro page.
=> Update document:  add how to npm i maplibre-gl on intro page

.gitignore, mkdocs.yml, src/index.ts
- #4274
Fixes #4274 
Before:
After:
=> Fixes lazy loading in docs

CHANGELOG.md, src/ui/marker.ts
A memory leak is caused when adding and removing markers.  `.on('terrain', this._update)` event listener is added when Marker's `addTo` is called, but `off` call is missing from the `remove` method.
=> Fix terrain listener memory leak when removing Marker

test/examples/filter-within-layer.html, test/examples/geocoder.html, test/examples/mapbox-gl-draw.html, test/examples/mouse-position.html
- Remove unnecessary `type="text/css"` - not needed for HTML5 and not recommended. (e.g. https://google.github.io/styleguide/htmlcssguide.html#type_Attributes )
- Update `@maplibre/maplibre-gl-geocoder` to latest version on the demo (seems to work fine)
- Accessibility fix for filter-within-layers example with radio matching the labels.
=> Docs: Example minor fixes

test/examples/disable-rotation.html
The `disable-rotation` example currently disables camera rotation via right click + drag and touch gestures. However, keyboard-based rotation remains enabled.
Let's ensure that rotation via keyboard input is also disabled such that we provide a comprehensive example of how to fully disable map rotation.
This fixes: https://github.com/maplibre/maplibre-gl-js/issues/4330.
=> examples: disable kbd rotation (#4330)

test/examples/sky-with-fog-and-terrain.html
- HTML Fix: Table now has a closing `</table>`
- Change font to a nicer looking sans-serif
- Inputs now have matching labels for screen reader support
Preview:
=> Fix, improve accessibility issue with Sky, Fog, Terrain example

CHANGELOG.md, src/geo/transform.test.ts, src/geo/transform.ts, src/render/draw_custom.test.ts, src/render/draw_custom.ts, src/style/style_layer/custom_style_layer.ts
Closes https://github.com/maplibre/maplibre-gl-js/issues/3080, closes #4044 
- https://github.com/maplibre/maplibre-gl-js/issues/3080
- #4044 
@Pessimistress , is this what you had in mind?
=> Expose projection matrix parameters

docs/plugins.md
This PR add the [Allmaps Maplibre](https://github.com/allmaps/allmaps/tree/main/packages/maplibre) plugin to the plugin list.
(also removes an extra 'enter' near the Terra Draw plugin)
(example might be coming in future PR)
=> Add Allmaps as available plugin

CHANGELOG.md, src/ui/hash.test.ts, src/ui/hash.ts
Fixes #4375 
https://i.gyazo.com/d78de26968289b6814e4852fbf913175.gif
=> #4375 remove hash string when hash remove

.github/workflows/test-all.yml
Uploads the test results even in case of failure.
This will hopefully allow in the future to take note of flickering tests.
=> Upload test results in case of failure

test/examples/change-case-of-labels.html
the "Change the case of labels" references `dog_park_11` which isn't a valid icon in the style, this updates it to `dog_park`.
before:
after:
=> fix missing icon ref in example

CHANGELOG.md, src/ui/handler/cooperative_gestures.test.ts, src/ui/handler/cooperative_gestures.ts, src/ui/handler/scroll_zoom.ts, test/build/min.test.ts
Enables pinching on a trackpad to zoom the map while `cooperativeGestures` is enabled.
Fixes #4463
A pinch on a trackpad is actually a `wheel` event but with `ctrlKey: true`. This change adds a new method to the `CooperativeGesturesHandler` called `shouldPreventWheelEvent` which is used internally for deciding whether to show the cooperative gestures message, and from the `ScrollZoomHandler::wheel` method, to determine whether or not to handle the gesture in the map.
=> Allow pinch trackpad gesture while cooperative gestures is enabled

CHANGELOG.md, src/util/actor.test.ts, src/util/actor.ts
=> Fix GeckoView tile loading android assets folder

docs/plugins.md
Added a link to the [maplibre-gl-dates](https://github.com/OpenHistoricalMap/maplibre-gl-dates/) plugin to the Plugins page. This plugin is [recommended](https://wiki.openstreetmap.org/wiki/OpenHistoricalMap/Reuse#Rendering_a_map) for any MapLibre GL JS map based on OpenHistoricalMap vector tiles, though technically it also works with any OSM vector tiles that expose the same tags.
=> Add maplibre-gl-dates to plugin directory

CHANGELOG.md
Fixed a bad conflict resolution on my part in #4536 that put the changelog entry under the wrong heading.
=> Move changelog entry for Arabic Extended-B fix

package.json
In Jan 2023, I noticed we had a security bug, in a dependency `postcss-inline-svg`, because of a dependency it had.
There was already a ticket in the repo to update said deps:
- https://github.com/TrySound/postcss-inline-svg/pull/103
But until it got merged/released, we could fix it locally by using overrides.
This has now been fixed upstream since v6 of postcss-inline-svg, which we already use. This version use the exact same versions of nested deps as we set in the overrides (can be verified in the [package.json](https://github.com/TrySound/postcss-inline-svg/blob/master/package.json), and by the fact our lockfile doesn't change after this), so it's now ready to be cleaned up.
=> Remove postcss-inline-svg overrides because of upsteam fix

CHANGELOG.md, src/source/geojson_source.test.ts, src/source/geojson_source.ts
closes #2691
> `clusterMaxZoom`: Max zoom on which to cluster points if clustering is enabled. Defaults to one zoom less than maxzoom (so that last zoom features are not clustered). Clusters are re-evaluated at integer zoom levels so setting clusterMaxZoom to 14 means the clusters will be displayed until z15.
If you set `clusterMaxZoom` to 18, clusters will continue to display >=18 <19 (up to 18.99...). To ensure you're still rending the source unclustered at z19 you need to have the source `maxzoom` set to at least 19.
If you the source `maxzoom` is less than or equal to the `clusterMaxZoom` then it won't stop clustering in the way you might expected based on your set `clusterMaxZoom` in this case we should emit a warning.
=> omit a warning if maxzoom <= clusterMaxZoom for geojson sources

CHANGELOG.md, src/geo/transform.test.ts, src/geo/transform.ts
Fixes an issue noticeable when using `transformCameraUpdate` and `maxBounds` together. Due to a bug with cloning `Transform` instances, the longitude range on the transform was lost. As `transformCameraUpdate` receives a clone of the transform object, the constraining that happens afterwards misses the longitude constraint.
=> Fix missing `lngRange` when cloning Transform instances

build/banner.ts
Closes #4547 
The  with/assert { type: "json" } stuff for JSON modules is quite the headache - in fact, this is the third consecutive (18, 20, 22) node release where it's been rather time-consuming to debug and resolve. The banner has a `with {type:"json"}` but rollup still breaks with an error about hitting an `assert` as if it is somehow auto-transformed into an `assert {type:'json'}` in the process... and removing the `with/assert {type:"json"}` will give an error that it's absent.
Until the JSON module feature works properly, we can in this case readily fall back to the old-school way of just reading the package.json with the 'fs' module, and parsing it.
=> Fix Node 22 and Deno build error

package.json
This makes the dev server examples load properly - they tile servers are open to calls from exactly `localhost` , not 0.0.0.0  or similar alternatives.
Before:
After:
=> Swap 0.0.0.0 with localhost on dev server

test/examples/maplibre-gl-terradraw.html
I did some interface changes on [maplibre-gl-terradraw](https://github.com/watergis/maplibre-gl-terradraw) to make the plugin for flexible and customizable. I updated the example page for the plugin.
- before
It collapsed the plugin menu as default
- after
now it can expand the menu as default. I added `open` property in the option.
=> doc: updated maplibre-gl-terradraw plugin example

build/generate-docs.ts, docs/index.md
Closes #4273
- #4273
This PR automatically sets the version in the unpkg script the latest such as `^4.7.0` allowing for minor/patch updates. 
Before
After
=> improve unpkg instructions

CHANGELOG.md, src/ui/hash.test.ts, src/ui/hash.ts
Closes #4732 
- #4732 
I've added a test for this, and a fix which is to modify the regex that recognize the hash. The section following the hashtag should be zero/one/more chars (.*), instead of one/more chars (.+).
Result before this PR:
`http://localhost:9966/test/examples/cluster.html##3/40.67/-103.59`
Result after this PR:
`http://localhost:9966/test/examples/cluster.html#3/40.67/-103.59`
=> Fix hash router for urls ending with a hash

CHANGELOG.md, src/ui/map.ts
When using a profiler it was evident that the memory leak was coming from a unregistered event when removing the map.
- #4811
- #4650
Fixes #4811
Fixes #4650
After - using 10 map remove.
=> Fix memory leak by removing listener

CHANGELOG.md, package-lock.json, package.json
Fixes #3516
Incorporates the following PR from style-spec repo:
- https://github.com/maplibre/maplibre-style-spec/pull/519
Fixes:
- #3516
This basically updates the spec package.
=> Update package to support multi features

test/examples/add-3d-model-threejs-with-shadow.html, test/examples/add-3d-model-with-terrain.html, test/examples/add-3d-model.html, test/examples/globe-3d-model.html
This updates all the Three.js examples to the latest version 0.169.0
This requires the examples to be updated to ESM / importmap, which is the only distribution of Three.js since 0.160.0.
Resolves the issues mentioned in #4885 :
- remove `map = window.map`
- write "using three.js" instead of "with three.js"
- latest three.js version 0.169.0 instead of 2y old 0.147.0
=> Use ESM and latest three.js 0.169.0

CHANGELOG.md
Changelog entry for https://github.com/maplibre/maplibre-gl-js/pull/4838 was merged into the changelog for already released pre3, this PR fixes that.
=> Fix globe depth changelog entry being in the wrong version

test/examples/globe-custom-tiles.html
Fixes a typo in the globe-custom-tiles example that causes the tile mesh not to be rendered. Should be overscaledTileID
https://github.com/maplibre/maplibre-gl-js/blob/9ba25c6d6cf2a15c542be6c919338928bab8b194/test/examples/globe-custom-tiles.html#L265
=> Fix globe-custom-tiles example

test/examples/hybrid-terrain.html
The globe atmosphere looks really bad in this example.
I realized the style spec has a [recommendation to interpolate](https://maplibre.org/maplibre-style-spec/sky/#atmosphere-blend) which looks much better:
> interpolate this expression when using globe projection.
Maybe we should even change the default value to a good looking interpolation, instead of 0.8.
I changed the projection to globe too (it has toggle), because we can finally render that correctly when this
- #4977
=> interpolate atmosphere in hybrid-terrain example

build/rollup_plugins.ts
Pointed out [here](https://github.com/maplibre/maplibre-gl-js/pull/4906#issuecomment-2455656279), we're missing a flag that makes only the prod build minified.
https://github.com/maplibre/maplibre-gl-js/commit/a3f67eb29448c1fd2abec0e6845a368f369b5170#diff-1925b6790595de2a8e9305249f59ea6cc5eb109c15c6013ae09de2f30132cc7aL34
Currently, we minify the dev build as well.
https://github.com/maplibre/maplibre-gl-js/blob/6eeafe9c5ebd625d511e7f5e540b19924a99d5a4/build/rollup_plugins.ts#L34-L40
cc @NathanMOlson
=> Dev bundle should not minify

src/geo/projection/covering_tiles.ts, src/geo/projection/mercator_transform.test.ts
This fixes an issue I found when testing `main` after #4779 was merged. `overscaledZ` was sometimes smaller than `z`, causing a silent exception in `map._render()`
=> Make sure overscaledZ is at least as big as tile Z

CHANGELOG.md, package-lock.json, package.json, src/geo/projection/globe_transform.ts, src/geo/projection/projection_factory.ts
Allow using projection `{ "type": "vertical-perspective" }` at all zoom levels.
See [Style Spec docs](https://maplibre.org/maplibre-style-spec/projection/), for all projection options.
Implemented by passing an adaptive flag to the GlobeTransform.
https://github.com/user-attachments/assets/e384c650-63ea-4a8d-a42e-34955d12e1ee
=> Add Vertical Perspective projection

CHANGELOG.md, src/css/maplibre-gl.css
This pull request addresses an issue where the MobileHelpText for cooperative gestures is incorrectly displayed when a map is embedded in an iFrame with a width smaller than 480px, even if the user is on a desktop device.
This PR closes #5052
=> Updated CSS media query to better detect touch devices

CHANGELOG.md, src/source/geojson_source.test.ts, src/source/geojson_source.ts
The calculation for `superclusterOptions.radius` in `GeoJSONSource.setClusterOptions` was missing the necessary scaling, resulting in incorrect values.
For reference, see the relevant initialization code:
https://github.com/maplibre/maplibre-gl-js/blob/bc432051b36bb3425a3c70cab79124698976934d/src/source/geojson_source.ts#L160  
https://github.com/maplibre/maplibre-gl-js/blob/bc432051b36bb3425a3c70cab79124698976934d/src/source/geojson_source.ts#L185
Note: `setClusterOptions` was introduced in #1998.
=> Fix cluster radius scaling in setClusterOptions

CHANGELOG.md, src/ui/camera.ts, src/ui/control/navigation_control.ts, src/ui/handler/drag_handler.ts, src/ui/handler/drag_rotate.test.ts, src/ui/handler/mouse.ts, src/ui/handler/mouse_handler_interface.test.ts, src/ui/handler/one_finger_touch_drag.ts, src/ui/handler/one_finger_touch_drag_handler_interface.test.ts, src/util/util.test.ts, src/util/util.ts, test/build/min.test.ts
This changes the drag-rotate on desktop to be around the center and respect the distance from the center.
It also improves the roll pixel factor.
The following comment started this:
https://github.com/maplibre/maplibre-gl-js/pull/4780#discussion_r1803869111
Before:
https://github.com/user-attachments/assets/1b35b4e3-cf90-4b78-819e-b4186a850e84
After:
https://github.com/user-attachments/assets/54faaecc-501e-41dc-a4f3-a385ac29b408
=> Improve rotate UX

package-lock.json, package.json
on `npm ci` i get
```sh
npm warn deprecated @types/cssnano@5.1.3: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
```
=> remove @types/cssnano

src/util/actor.test.ts, test/unit/lib/web_worker_mock.ts
This is in continue to the following PR to fix a flaky test:
- #4728 
It also simplifies the test initialization.
=> Fix actor flaky test

.gitignore, build/generate-docs.ts, package-lock.json, package.json
This is a replacement to 
- #4329
By doing the image conversion as part of the build and not as part of the repo content due to github limitation on presenting those images.
=> Convert images to webp when building the docs

.github/workflows/release.yml
This fixes a bug I introduced in last CI change where pre-release message was not added and a github version was not created:
- #5085
For version 5.0.0-pre.8 I did this manually to workaround this bug.
=> Publish pre-release to github

docs/index.md, test/examples/maplibre-gl-terradraw.html
I updated maplibre-gl-terradraw version from v0.1.1 to the latest version (v0.6.4) since it has quite a lot of changes on plugin interface.
=> doc: updated maplibre-gl-terradraw version to 0.6.4

CHANGELOG.md, src/ui/map.ts, src/ui/map_tests/map_canvas.test.ts, test/integration/query/query.test.ts, test/integration/render/run_render_tests.ts
This PR fixes https://github.com/maplibre/maplibre-gl-js/issues/5135 by adding a `contextAttributes` property to the map constructor that supports all [WebGLContextAttributes](https://registry.khronos.org/webgl/specs/latest/1.0/#5.2), so now you can do something like:
```js
const map = new maplibregl.Map({
container: 'map',
style: 'https://demotiles.maplibre.org/style.json',
center: [0, 0],
zoom: 2,
contextAttributes: {
powerPreference: 'default',
antialias: true
});
```
Note that some `WebGLContextAttributes` can't be overwritten because Maplibre relies on it. These are `alpha`, `depth`, `stencil` and `premultipliedAlpha` which are always set to `true`.
This PR also sets the default WebGL `powerPreference` to `high-performance` instead of `default`, which defaults to using dedicated GPUs …
=> Add contextAttributes map option

CHANGELOG.md, src/ui/handler/drag_move_state_manager.ts
See https://github.com/maplibre/maplibre-gl-js/discussions/5195 for discussion.
I think the regression was caused by "TouchEvent" only being defined on Chromium-derived and/or touchscreen-equipped browsers, such that the drag handler would fail on Firefox and Safari on my Mac laptop.
This PR does two things:
* Adds a `typeof TouchEvent !== 'undefined'` check to prevent a runtime error when it's undefined.
* Consolidates the type checks into an `_onMouseEventOrTouchEvent` method to reduce duplication, possibly at the cost of clarity.
=> Fix NavigationControl compass regression

test/examples/3d-buildings.html, test/examples/3d-extrusion-floorplan.html, test/examples/add-3d-model-babylon.html, test/examples/add-3d-model-threejs-with-shadow.html, test/examples/add-3d-model-with-terrain.html, test/examples/add-3d-model.html, test/examples/center-point.html, test/examples/custom-style-layer.html, test/examples/geocoder.html, test/examples/globe-3d-model.html, test/examples/globe-custom-simple.html, test/examples/globe-custom-tiles.html
This PR updates some examples that were still using the old syntax to set canvas context attributes
- In continue to #5196
=> Update examples related to WebGL configuration changes

package.json
In https://github.com/maplibre/maplibre-gl-js/pull/4728 `jest` was replaced with `vitest` but the `jest` script was removed instead of updated. That made `npm run test` to fail.
This PR fixes it by adding a new entry to `package.json` called `vitest`.
=> Add `vitest` script to package.json

CHANGELOG.md, src/ui/map.ts, src/ui/map_tests/map_webgl.test.ts
Following https://github.com/maplibre/maplibre-gl-js/pull/5198, this PR allows to use a desired WebGL version by setting `contextType` inside the `canvasContextAttributes` option on Map creation.
=> Allow choosing webgl version

package.json
This PR adds the `generate-shaders` step to `build-dist`.
I've been bitten multiple times by this. I understand `build-dist` as the building script for the whole package but it was not using the latest version of shaders.
=> Generate shaders when building

test/integration/render/run_render_tests.ts, tsconfig.jest.json, tsconfig.vitest.json
This PR removes the `tsconfig.jest.json` file. 
It is unnecessary it has been replaced from Jest to Vitest 2. (https://github.com/maplibre/maplibre-gl-js/pull/4728)
=> Remove unnecessary jest configuration file

CHANGELOG.md, src/source/source_cache.test.ts, src/source/source_cache.ts
This PR fixes https://github.com/maplibre/maplibre-gl-js/issues/5248
Looking at it, when globe is being used, some tileIDs coordinates are wrapped and we were only using unwrapped tile ids to check if a parent tile had loaded children. The fix here is just to add a check for the canonical key, in addition to the existing one.
Before
https://github.com/user-attachments/assets/fabfc02b-ae6f-410e-840c-f5f052efa242
After
https://github.com/user-attachments/assets/9d2769c3-eb47-4b57-9cbf-fb33df747cb7
=> Fix children not retained when wrapped

CHANGELOG.md, src/shaders/symbol_icon.vertex.glsl, test/integration/render/run_render_tests.ts
This PR closes https://github.com/maplibre/maplibre-gl-js/issues/5090
I haven't been able to create a test that captures the issue because it only appears when looking down from the north pole and I can't get it to happen while running a render test.
Before
https://github.com/user-attachments/assets/534a158c-5f4c-40c4-958c-e28223b3fc1a
After
https://github.com/user-attachments/assets/b26b099c-3a00-49c7-84bb-342d5038f0f3
=> Fix symbol size increase

build/release-notes.js
Release note generation message has been with a bug for a long time now.
I just saw it and fixed manually a lot of the release notes in github, but not all of them.
This will at least solve the next release notes
=> Fix invalid link in release notes

CHANGELOG.md, src/css/maplibre-gl.css
Applying hover effect on touch devices has an undesired effect: The element gets set to hover state on touch and stays like that until the next touch event.  Using the :active state gives a nicer feedback by highlighting the button only for the duration of the touch. (fixes https://github.com/maplibre/maplibre-gl-js/issues/5284)
Before: 
https://github.com/user-attachments/assets/4ae6b618-f900-4099-bc97-152f6bdc67a6
After: 
https://github.com/user-attachments/assets/3484d1dc-80e4-4c93-9f6e-46db14d280bd
- [/] Write tests for all new functionality.
- [/] Document any changes to public APIs.
- [/] Post benchmark scores.
- [/] Add an entry to `CHANGELOG.md` under the `## main` section.
=> Only apply css hover effect on non-touch devices

test/examples/mapbox-gl-draw.html
As raised via a comment in #5138, the [mapbox-gl-draw example](https://maplibre.org/maplibre-gl-js/docs/examples/mapbox-gl-draw/) currently provides an example of using mapbox-gl-draw however the description mentioned maplibre-gl-draw.
This PR updates the description to match the example given.
We also update to mapbox-gl-draw 1.5.0 since from this version the CANVAS class is exposed which we need to override to match the maplibre class. This is necessary for the delete a vertex feature to work and possibly other features.
Is this done for examples as well?
=> update mapbox gl draw example

test/examples/popup-on-hover.html
This PR fixes this issue https://github.com/maplibre/maplibre-gl-js/issues/5327
The documentation example Display a popup on hover.
The Popup doesn't change when moving to another overlapping feature. This is caused by the mouseenter event not triggered again because we didn't leave the layer while moving to the other feature.
As a fix we are using mousemove instead of mouseenter event and check if the mouse is over another feature and the popup content needs to change.
=> Fix example not changing popup when mouse moves to another overlapping feature

test/examples/maplibre-gl-terradraw.html
maplibre-gl-terradraw is now v1.0.1, I have updated the plugin version in the example page
=> docs: upgrade maplibre-gl-terradraw to v1.0.1

CHANGELOG.md, src/ui/hash.test.ts, src/ui/hash.ts
Bearing rotation of the map has range: -180 to 180. In this PR: #5241 URL hash validation was introduced, however the allowed bearing range is set to 0 - 180. This PR fixes the value, and added tests to cover bearing range below zero.
Related to #5461 .
=> Fix URL hash bearing validation range

src/geo/projection/globe_utils.ts, src/geo/transform_interface.ts
=> Docs: Fix a couple of typos

docs/guides/leaflet-migration-guide.md, docs/guides/openlayers-migration-guide.md
This adds two new migration guides to maplibre's guides.
=> Add leaflet and openlayers migration guides

CHANGELOG.md, src/index.ts
After I upgraded my app to use the latest version I saw that there's a problem with the types.
This fixes it.
=> Add GeoJSONFeature missing export

test/bench/lib/tile_parser.ts
Quick little PR to fix an issue with the Layout benchmarks. Trying to load the style would result in a silent exception that made the test just sit there and spin.
=> add migrateProjection to bench StubMap

src/ui/camera.ts
It seems that when `queryTerrainElevation` was updated for 5.x in https://github.com/maplibre/maplibre-gl-js/pull/3854, its description was not updated accordingly, so the generated documentation is now incorrect. This PR updates the description to what it does now. Also, I have verified that what's said in the new description about the exaggeration value is true.
=> Update queryTerrainElevation description

CHANGELOG.md, src/ui/control/attribution_control.test.ts, src/ui/control/attribution_control.ts
In one of my projects I noticed a weird flickering on the attribution control that seemed to be related to rapid data updates. Notably, it only occurred in Firefox and not in Chromium, so I started to investigate.
Since attribution strings can include untrusted HTML, PR #5057 introduces a bit of input sanitization to mitigate potential XSS attacks trough the `attribution` field. The attribution control includes a mechanism to suppress excessive re-renders, but #5057 introduced a bug: The suppression logic compares the cached **sanitized** result with the new **unsanitized** result. This will lead to excessive DOM updates if the sanitized attribution actually differs from the unsanitized one, for instance if it contains a `&copy;` HTML entity that gets transformed into a `©` literal.
This …
=> Fix excessive attribution control rerendering

README.md
PR to add [MapTiler logo to sponsor list](https://maplibre.org/news/2025-03-31-maptiler-announcement/) in the readme file.
=> Addition to sponsor section

src/ui/events.ts
This changes an old definition that was later on changed, but the docs were not updated to reflect it.
=> Improves projection event type docs

CHANGELOG.md, src/ui/marker.test.ts, src/ui/popup.test.ts, src/ui/popup.ts
- This reverts #5564
- Fixes #5718
- Fixes #5576
It adds the relevant test to make sure this won't break in the future, hopefully.
CC: @kamil-sienkiewicz-asi 
Looking at the code and at the fix I think the removeevent and addevent are not symmetrical, which is what is causing the issue. The creation of the button is not done when adding to the map and so the removal can't be done when removing from the map.
I'll be happy to review a different fix to this issue.
=> Revert popup close memory leak fix attempt

src/source/source_cache.test.ts
- This is in continue to #5777
This removes the top level promise from the tests and make the tests more async style.
=> Move source cache tests to use async

CHANGELOG.md, src/source/source_cache.test.ts, src/source/source_cache.ts, src/ui/map.ts, src/ui/map_tests/map_refresh_tiles.test.ts
This PR adds `refreshTiles()` to the map public API.
- resolves #3419 
- resolves #415 
This allows tiles to be force-reloaded from outside MapLibre. The use case I've got in mind is that when tiles on the server change, a WebSocket message is sent to the client (using a to-be-developed plugin) notifying it of changed tiles. The plugin can then call `map.refreshTiles()` with the modified tile IDs, causing the map to reload the tiles and display the new data.
You can check out a demo [here](https://nathanmolson.github.io/live_tiles). Clicking on a tile will call `map.refreshTiles()` on the tile. I'm using `addProtocol()` to draw a timestamp (from `performance.now()`) on each tile, representing the time it was loaded. Zoom all the way out to see that it behaves correctly for wrapped tiles …
=> Add refreshTiles() to map public API

CHANGELOG.md, src/ui/marker.test.ts, src/ui/marker.ts
This PR fixes https://github.com/maplibre/maplibre-gl-js/issues/5829
Looking into the issue I found when terrain is enabled, _opacityWhenCovered is only applied when terrain is blocking and not if occluded (which if i understand correctly is when the tile is not visible)
This reworks the opacity so it always first checks if the marker is 'occluded ' first. If it is, the _opacityWhenCovered  value is always applied. If it is not, it does the existing checks to see if it behind terrain.
Example with v5.4.0
https://stackblitz.com/edit/web-platform-6xsbznqb?file=index.html
Example with this PR code
https://stackblitz.com/edit/web-platform-mrytnhfv?file=index.html 
When globe is enabled and terrain is enabled, it does not apply _opacityWhenCovered  when the marker is behind terrain. this is …
=> fix: opacityWhenCovered not working to hide the marker behind the globe if terrain is enabled

CHANGELOG.md, src/source/source_cache.ts, src/ui/map.ts, src/ui/map_tests/map_refresh_tiles.test.ts
Fixes #5806 to get `refreshTiles()` to work for an entire vector layer (before this change, `refreshTiles()` worked on vector layers only when provided a list of tiles to refresh).
Before, `SourceCache::_reloadTile()` was called with `state = 'reloading'`. This caused `VectorTileSource::reloadTile()` to be called, instead of the desired `VectorTileSource::loadTile()`. According to the docs, `WorkerSource::reloadTile()` "re-parses a tile that has already been loaded", which is why `loadTile()` must be called instead.
After this change, `SourceCache::_reloadTile()` is called with `state = 'expired'`. This results in the tile being re-requested, just as it already was when a list of tile IDs was provided to `refreshTiles()`.
=> Fix vector tile reload

rollup.config.ts
This PR removes an outdated comment in rollup.config.ts that refers to a build-tsc npm script which no longer exists.
- Removed comment line suggesting to run `build-tsc` before rollup
- The comment was obsolete since this script no longer exists in package.json
- Checked package.json scripts to confirm build-tsc doesn't exist
- Verified current build process uses @rollup/plugin-typescript directly
- Confirmed that existing build commands (build-dev, build-prod) already handle TypeScript transpilation 
- Examined other comments in the file and found no other issues
- Reduces confusion for new contributors (as reported in issue #5651)
- No functional changes to the codebase
- Only removes outdated documentation
Close: #5651
---
Thank you for developing such great software!
This is my first …
=> fix: remove old comment from rollup.config.ts

src/shaders/color_relief.fragment.glsl
This change is required to get the `color_relief` feature to work in the LINZ test environment.
The same code is used in `hillshade_prepare.fragment.glsl`, which also gets elevation from raster DEM tiles.
=> Fix Hypsometric Tint float precision

src/ui/camera.ts
- this change is entirely new
This PR updates the comments in `camera.ts` to correct outdated information about the camera's field of view (FOV). The previous comment incorrectly assumed a fixed FOV of "2 arctan ½ ≈ 53°", but the current implementation allows users to set custom FOV values using the `getVerticalFieldOfView()`/`setVerticalFieldOfView()` APIs.
This PR updates the old comment to more accurately state that it "uses the current vertical field of view setting," ensuring the code documentation matches its actual behavior.
This PR closes Issue #5078.
- Close: #5078
No changes to public APIs, only code comments were updated.
=> chore: Update comment to clarify field of view setting in Camera class

CHANGELOG.md, src/shaders/hillshade.fragment.glsl
Addresses the use of a WebGL 2.0 reserved keyword as reported in #5970
=> fix: Don't use incompatible GLSL `switch` statement

src/style/style_layer/custom_style_layer.ts
fixes #5987 
Here i am Explicitly typing both `map: Map, gl: WebGLRenderingContext | WebGL2RenderingContext` and destructuring `modelViewProjectionMatrix: Float32Array` in the example
@HarelM If anything needs to be change please let me know, i will love to address those.
=> Corrected parameters in example for CustomLayerInterface

.cspell.json, mkdocs.yml
Added a Bluesky icon and link to the social section in mkdocs.yml to provide users with an additional way to connect. Also removed trailing whitespace in the theme section.
=> Add Bluesky social link to mkdocs config

README.md
GitHub has had a feature to [Specify theme context for images in Markdown](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) for a while (works with GitHub hosted images).
Since we have a MapLibre logo for a dark background... I think it looks nice.
Light mode
Dark mode
If this is approved I will change it for Native too.
Also fixes that the logo is super tiny on hidpi screens, **current**:
=> Use high contrast MapLibre logo for dark mode

package-lock.json, package.json
This package was added to run the lint-css (stylelint) in this [PR](https://github.com/maplibre/maplibre-gl-js/pull/1485#discussion_r945254545).
It's been few years, and it doesn't appear necessary any longer.
=> Remove unnecessary global-prefix dep

postcss.config.js
This is probably related to some recent changes in post css and nano so this configuration change is no longer needed, as far as I can tell...
=> Fix postcss warnings

src/style/style.test.ts
fixes writing to `stderr` which was a symptom of the problem
https://github.com/maplibre/maplibre-gl-js/pull/6215#issuecomment-3198061607
- [] Add an entry to `CHANGELOG.md` under the `## main` section.
=> execute unit tests for global state with correct relevant parameters

.github/workflows/test-all.yml, package-lock.json, package.json, test/integration/query/query.test.ts, test/integration/render/run_render_tests.ts
- This is a left over from #6338 
- Which needed the following fix: https://github.com/cenfun/monocart-coverage-reports/issues/118
It is using the correct method that was fixed in last build of monocart coverage report.
=> Use built-in method for absolute path in tests

test/integration/render/tests/high-pitch/pitch95-roll135/style.json, test/integration/render/tests/high-pitch/pitch95/style.json, test/integration/render/tests/sky/basic/style.json, test/integration/render/tests/sky/roll10/style.json, test/integration/render/tests/sky/roll180/style.json, test/integration/render/tests/sky/roll45-with-text/style.json, test/integration/render/tests/sky/roll90/style.json, test/integration/render/tests/terrain/fog-no-sky-blend-roll/style.json, test/integration/render/tests/terrain/fog-no-sky-blend/style.json, test/integration/render/tests/terrain/fog-sky-blend-globe/style.json, test/integration/render/tests/terrain/fog-sky-blend-roll/style.json, test/integration/render/tests/terrain/fog-sky-blend/style.json, test/integration/render/tests/terrain/fog/style.json, test/integration/render/tests/terrain/symbol-add-terrain/style.json
`timeout` needs to be under `metadata > test` to be effective. Otherwise it defaults to [40 seconds](https://github.com/maplibre/maplibre-gl-js/blob/22bdc59aa3434e1857db22ea518bc373069b6c86/test/integration/render/run_render_tests.ts#L715) which seems to be too little for some tests (i.e. [terrain/fog](https://github.com/maplibre/maplibre-gl-js/blob/main/test/integration/render/tests/terrain/fog/style.json)) when executed on `github`.
=> Fix timeout for render tests

CHANGELOG.md, src/source/raster_tile_source.test.ts, src/source/raster_tile_source.ts, src/source/vector_tile_source.test.ts, src/source/vector_tile_source.ts, src/ui/map_tests/map_events.test.ts
- Fixes #5430
When source TileJSON fails to load it is already ignored. However the source is treated as not loaded yet which causes events `load` and `idle` to be withheld.
The `load` event is used to signal that the map is ready. Specifically it means that map style can be modified. This condition is met after TileJSON fails to load, so the `load` event can be triggered in that case. Similarly the `idle` event means that there are no outstanding repaints, which again is true after TileJSON fails to load and map is fully repainted.
This PR marks sources with TileJSON that failed to load as loaded, enabling `load` and `idle` events to trigger.
=> Fix #5430 - when TileJSON fails to load ignore source but trigger load and idle events

.github/dependabot.yml
This PR enables Dependabot cooldown feature.
This potentially allows our tooling to spot security issues instead of noticing them after the merge.
Related to: 
- https://github.com/maplibre/maplibre-gl-js/pull/6421
=> chore(deps): add a cooldown setting to dependabot

CHANGELOG.md, src/source/source_cache.test.ts, src/source/source_cache.ts, src/source/tile_id.ts, test/build/min.test.ts
**Summary**
This PR fixes an issue where parent tiles were being retained/requested even when deeper descendant tiles already covered the missing ideal tile.
**Background**
Previously, _updateRetainedTiles only checked one level of children before falling back to parent tiles. Meanwhile, _retainLoadedChildren correctly seeks descendants up to maxCoveringZoom (e.g. 4, 16, 64 tiles for successive generations). This mismatch causes unnecessary parent retainment.
**Change**
Instead of duplicating multi-generation logic in _updateRetainedTiles, the function now relies on _retainLoadedChildren to report ideal tiles with incomplete descendants. This keeps the logic consistent and prevents redundant parent retainment/requests.
=> Fix issue where parent tiles are retained when deeper descendant tiles already cover the missing ideal tile.

.github/workflows/release.yml
This PR adds release attestation for the `dist.zip` we attach to our releases
=> chore(security): add release attestation for `dist.zip`

CHANGELOG.md, src/ui/handler_manager.test.ts, src/ui/handler_manager.ts
Closes #5839
- #5839
Closes https://github.com/maplibre/maplibre-gl-js/issues/5026
- https://github.com/maplibre/maplibre-gl-js/issues/5026
Rotating a globe with terrain enabled used to “zoom toward the poles” because the mercator-specific terrain pan logic bypassed the globe helper’s zoom compensation.
This PR redirects all globe+terrain drags through the globe pan helper so the apparent radius stays constant, while keeping the old pixel-delta path for mercator terrain users.
Before
https://github.com/user-attachments/assets/5611978c-8eec-43bb-af5b-5d0578c37d06
After
https://github.com/user-attachments/assets/5dfbbe04-29d5-4b51-a7f5-46fcc98fa89e
=> Fix zoom issue with globe + terrain when dragging to poles
